api/src/main/java/org/apache/cxf/attachment/AttachmentUtil.java
See JIRA issue for further details
=> [CXF-6484] Regression in Content-id format

rt/transports/http/src/main/java/org/apache/cxf/transport/http/auth/AbstractSpnegoAuthSupplier.java
This commit implements an additional property,
useCanonicalHostname, which is supported by the AbstractSpnegoAuthSupplier,
and therefore available to SpnegoAuthSupplier and
KerberosAuthOutInterceptor.
The default behavior is not modified.  If useCanonicalHostname is set,
then the service principal will be created using the canonical name of the
remote host.
For example, if there is a CNAME DNS record for host.example.com which
refers to an A record host-a-b-c.example.com, the default behavior would
be to generate a service principal HTTP/host.example.com. When
useCanonicalHostname is set to true, the service principal would be HTTP/
host-a-b-c.example.com. Most browsers and many other HTTP user agents
perform this kind of canonicalization.
=> Implement optional hostname canonicalization for kerberos (SPNEGO)

rt/databinding/jaxb/src/main/java/org/apache/cxf/jaxb/JAXBContextInitializer.java
https://issues.apache.org/jira/browse/CXF-6799
=> CXF-6799: handle arrays of generics

rt/transports/jms/src/main/java/org/apache/cxf/transport/jms/JMSConduit.java, rt/transports/jms/src/main/java/org/apache/cxf/transport/jms/JMSConfiguration.java, systests/transport-jms/src/test/java/org/apache/cxf/systest/jms/JMSClientServerTest.java
See https://issues.apache.org/jira/browse/CXF-7008
=> [CXF-7008] Regression: CXF-5788 - JMS replyToDestination doesn't work

distribution/src/main/release/samples/jax_rs/description_swagger2_osgi/README.txt
https://issues.apache.org/jira/browse/CXF-7045
=> [CXF-7045] Update sample description_swagger2_osgi README.txt file

rt/transports/http-hc/src/main/java/org/apache/cxf/transport/http/asyncclient/AsyncHTTPConduit.java
=> Fix AsyncHTTPConduit read timeout with exhausted connection pool

core/src/main/java/org/apache/cxf/common/jaxb/JAXBContextCache.java, core/src/main/java/org/apache/cxf/common/util/CacheMap.java, core/src/test/java/org/apache/cxf/common/util/CacheMapTest.java
https://issues.apache.org/jira/browse/CXF-7339
=> [CXF-7339] Fix NPE due to weak reference being GC-ed

rt/rs/security/xml/src/main/java/org/apache/cxf/rs/security/xml/SignatureProperties.java, rt/rs/security/xml/src/main/java/org/apache/cxf/rs/security/xml/XmlSecOutInterceptor.java
Note that this depends on a newer version of xmlsec, probably won't compile until that is released and used.
=> CXF-7345 Use the new properties to control generation of the resulting XML document

integration/jca/src/main/java/org/apache/cxf/jca/outbound/CXFConnectionSpec.java, integration/jca/src/main/java/org/apache/cxf/jca/outbound/ManagedConnectionFactoryImpl.java, maven-plugins/codegen-plugin/src/main/java/org/apache/cxf/maven_plugin/AbstractCodegenMoho.java, maven-plugins/java2ws-plugin/src/main/java/org/apache/cxf/maven_plugin/Java2WSMojo.java, maven-plugins/wadl2java-plugin/src/main/java/org/apache/cxf/maven_plugin/wadlto/AbstractCodeGeneratorMojo.java, osgi/karaf/features/src/main/resources/features.xml, parent/pom.xml, systests/databinding/src/test/java/org/apache/cxf/systest/jaxb/model/ExtendedWidget.java, systests/databinding/src/test/java/org/apache/cxf/systest/jaxb/model/Widget.java, tools/common/pom.xml, tools/common/src/main/java/org/apache/cxf/tools/common/VelocityGenerator.java, tools/javato/ws/src/main/java/org/apache/cxf/tools/java2wsdl/processor/internal/build.xml.vm, tools/javato/ws/src/main/java/org/apache/cxf/tools/java2wsdl/processor/internal/jaxws/generator/template/javafirst-impl.vm, tools/javato/ws/src/main/java/org/apache/cxf/tools/java2wsdl/processor/internal/jaxws/generator/template/javafirst-sei.vm, tools/javato/ws/src/main/java/org/apache/cxf/tools/java2wsdl/processor/internal/simple/generator/template/impl.vm, tools/javato/ws/src/main/java/org/apache/cxf/tools/java2wsdl/processor/internal/simple/generator/template/sei.vm, tools/wsdlto/core/src/main/java/org/apache/cxf/tools/wsdlto/core/AbstractGenerator.java, tools/wsdlto/frontend/jaxws/src/main/java/org/apache/cxf/tools/wsdlto/frontend/jaxws/customization/JAXWSBindingParser.java, tools/wsdlto/frontend/jaxws/src/main/java/org/apache/cxf/tools/wsdlto/frontend/jaxws/generators/SEIGenerator.java, tools/wsdlto/frontend/jaxws/src/main/java/org/apache/cxf/tools/wsdlto/frontend/jaxws/generators/ServiceGenerator.java, tools/wsdlto/frontend/jaxws/src/main/java/org/apache/cxf/tools/wsdlto/frontend/jaxws/jaxws-toolspec.xml, tools/wsdlto/frontend/jaxws/src/main/java/org/apache/cxf/tools/wsdlto/frontend/jaxws/processor/internal/ServiceProcessor.java, tools/wsdlto/frontend/jaxws/src/main/java/org/apache/cxf/tools/wsdlto/frontend/jaxws/template/build.vm, tools/wsdlto/frontend/jaxws/src/main/java/org/apache/cxf/tools/wsdlto/frontend/jaxws/template/client.vm, tools/wsdlto/frontend/jaxws/src/main/java/org/apache/cxf/tools/wsdlto/frontend/jaxws/template/fault.vm, tools/wsdlto/frontend/jaxws/src/main/java/org/apache/cxf/tools/wsdlto/frontend/jaxws/template/impl.vm, tools/wsdlto/frontend/jaxws/src/main/java/org/apache/cxf/tools/wsdlto/frontend/jaxws/template/sei.vm, tools/wsdlto/frontend/jaxws/src/main/java/org/apache/cxf/tools/wsdlto/frontend/jaxws/template/server.vm, tools/wsdlto/frontend/jaxws/src/main/java/org/apache/cxf/tools/wsdlto/frontend/jaxws/template/service.vm
Initial proposal for fixing CXF-7405. Two notes:
1) I had to build Velocity from sources from its 2.0 tag at https://github.com/apache/velocity-engine.git ; can we push the binaries to the maven repo?
2) I'm not sure what to do with the logger at tools/common/src/main/java/org/apache/cxf/tools/common/VelocityGenerator.java , see commented code there.
=> [CXF-7405] Removal of commons-lang dependency and upgrade to Velocity 2

rt/transports/http/src/main/java/org/apache/cxf/transport/http/auth/HttpAuthHeader.java
`authTypeIsNegotiate` looks wrong to me
=> Fix probable bug

rt/frontend/jaxrs/src/main/java/org/apache/cxf/jaxrs/utils/ResourceUtils.java, rt/rs/description/src/test/java/org/apache/cxf/jaxrs/model/wadl/WadlGeneratorTest.java
https://issues.apache.org/jira/browse/CXF-7545
=> Update TypeVariable check ResourceUtils.java

core/src/main/java/org/apache/cxf/interceptor/MessageSenderInterceptor.java, core/src/main/java/org/apache/cxf/interceptor/Messages.properties
=> Revert "When failing to close conduit, distinct read faults from write faults"

rt/rs/security/oauth-parent/oauth2/src/main/java/org/apache/cxf/rs/security/oauth2/services/AuthorizationMetadataService.java
Default port should be removed from
issuer and endpoints in discovery
documents.
aka
"issuer":"https://authorization-server:443"
should be
"issuer":"https://authorization-server"
=> [CXF-7572] default port in OAuth discovery doc

rt/rs/microprofile-client/src/main/java/org/apache/cxf/microprofile/client/CxfTypeSafeClientBuilder.java, rt/rs/microprofile-client/src/main/java/org/apache/cxf/microprofile/client/Messages.properties, rt/rs/microprofile-client/src/main/java/org/apache/cxf/microprofile/client/MicroProfileClientConfigurableImpl.java, rt/rs/microprofile-client/src/main/java/org/apache/cxf/microprofile/client/Validator.java, rt/rs/microprofile-client/src/main/java/org/apache/cxf/microprofile/client/cdi/RestClientBean.java, rt/rs/microprofile-client/src/main/java/org/apache/cxf/microprofile/client/config/ConfigFacade.java, rt/rs/microprofile-client/src/test/java/org/apache/cxf/microprofile/client/ValidatorTest.java
Checks:
- that the passed-in type is an interface
- that each method has, at most, one HTTP method annotation
- that URI template variables in @Path annotations are resolved by
@PathParam annotations
=> MP Rest Client interface validation and tests

rt/ws/security/src/main/java/org/apache/cxf/ws/security/wss4j/WSS4JInInterceptor.java
=> [CXF-7598] Update warning log

core/src/main/java/org/apache/cxf/common/jaxb/JAXBUtils.java, rt/databinding/jaxb/src/main/java/org/apache/cxf/jaxb/JAXBDataBinding.java, rt/databinding/jaxb/src/main/java/org/apache/cxf/jaxb/io/DataWriterImpl.java, rt/javascript/javascript-tests/src/test/resources/deserializationTests.js, rt/ws/addr/src/main/java/org/apache/cxf/ws/addressing/soap/MAPCodec.java, testutils/src/main/java/org/apache/cxf/testutil/common/ServerLauncher.java
…uple of test failures; Fix javascript test
=> [CXF-7520]:Set NoEscapeHandler for fastinfoset content type;Fix couple of test failures

rt/frontend/jaxrs/src/main/java/org/apache/cxf/jaxrs/impl/UriBuilderImpl.java, rt/frontend/jaxrs/src/main/java/org/apache/cxf/jaxrs/utils/JAXRSUtils.java, rt/frontend/jaxrs/src/test/java/org/apache/cxf/jaxrs/Customer.java, rt/frontend/jaxrs/src/test/java/org/apache/cxf/jaxrs/utils/JAXRSUtilsTest.java, systests/jaxrs/src/test/java/org/apache/cxf/systest/jaxrs/JAXRS20ClientServerBookTest.java
=> [CXF-7652] UriBuilderImpl: null-empty differentiation for query/matrix

rt/ws/security/src/main/java/org/apache/cxf/ws/security/wss4j/WSS4JStaxOutInterceptor.java
=> Make WSS4JStaxOutInterceptor always run after LoggingOutInterceptor

core/src/main/java/org/apache/cxf/common/classloader/ClassLoaderUtils.java
=> no need of instantiating so much objects when security manager is null

rt/frontend/jaxrs/src/main/java/org/apache/cxf/jaxrs/model/URITemplate.java, rt/frontend/jaxrs/src/test/java/org/apache/cxf/jaxrs/model/URITemplateTest.java
=> CXF-7765 - URITemplate.compareTemplates returns inconsistent results

osgi/karaf/features/src/main/resources/features.xml
=> [CXF-7773] Upgrade pax-cdi to 1.0.0 (master)

osgi/karaf/features/src/main/resources/features.xml
Upgrade cxf karaf features to use pax-cdi 1.0.0
=> [CXF-7773] Upgrade to pax-cdi 1.0.0 (3.2.x)

rt/databinding/jaxb/src/main/java/org/apache/cxf/jaxb/JAXBEncoderDecoder.java, systests/databinding/pom.xml, systests/databinding/src/test/java/org/apache/cxf/systest/jaxb/TestServiceTest.java, systests/databinding/src/test/java/org/apache/cxf/systest/jaxb/service/ErrorData.java, systests/databinding/src/test/java/org/apache/cxf/systest/jaxb/service/PropertyOrderException.java, systests/databinding/src/test/java/org/apache/cxf/systest/jaxb/service/TestService.java, systests/databinding/src/test/java/org/apache/cxf/systest/jaxb/service/TestServiceImpl.java
=> [CXF-7823]:JAXBEncoderDecoder doesn't respect @XmlType's propOrder in Exception class

rt/frontend/jaxrs/src/main/java/org/apache/cxf/jaxrs/impl/RequestPreprocessor.java
Signed-off-by: PK Søreide <per.kristian.soreide@gmail.com>
=> Add openapi.json & openapi.yaml to skipped paths

rt/frontend/jaxrs/src/main/java/org/apache/cxf/jaxrs/utils/InjectionUtils.java
…otherwise it just swallows the error for end user
=> [CXF-7808] Ensure injectThroughMethod reports its error in the log

rt/rs/microprofile-client/pom.xml, rt/rs/microprofile-client/src/main/java/org/apache/cxf/microprofile/client/MicroProfileClientFactoryBean.java, rt/rs/microprofile-client/src/main/java/org/apache/cxf/microprofile/client/cdi/RestClientBean.java, rt/rs/microprofile-client/src/main/java/org/apache/cxf/microprofile/client/proxy/MicroProfileClientProxyImpl.java, rt/rs/microprofile-client/src/test/java/org/apache/cxf/jaxrs/client/WebClientUtil.java, rt/rs/microprofile-client/src/test/java/org/apache/cxf/microprofile/client/CxfTypeSafeClientBuilderTest.java, rt/rs/microprofile-client/src/test/java/org/apache/cxf/microprofile/client/cdi/RestClientCdiTest.java, rt/rs/microprofile-client/src/test/java/org/apache/cxf/microprofile/client/mock/MockConfigProviderResolver.java, rt/rs/microprofile-client/src/test/resources/META-INF/services/org.eclipse.microprofile.config.spi.ConfigProviderResolver
Registers the providers specified via MP Config.
=> Issue 7868: Ensure providers registered via MP Config are honored

rt/transports/http-hc/src/main/java/org/apache/cxf/transport/http/asyncclient/AsyncHTTPConduitFactory.java
Motivation: if connections are contended towards a slow target, it may make sense
to set connectionTimeout and connectionRequestTimeout to values much lower than
the receiveTimeout. Expected client behavior is to receive an error if a connection
does not become available within connectionRequestTimeout. Current behavior however
is that the error is only received after up to receiveTimeout has passed, when a
current request to the target has finished and the connection is released or returned
to the pool.
Fix: instead of only checking expired leases when a connection becomes available,
periodically check them in the same thread that checks idle connections as
well. This makes sure that an error is returned to the client after
a maximum of connectionRequestTimeout + selectTimeout.
As a side …
=> [CXF-7883] fix: handle connectionRequestTimeout in AsyncHTTPConduitFactory

parent/pom.xml
https://issues.apache.org/jira/browse/CXF-7893
=> CXF-7893 Add guava entry to cxf-parent

core/src/main/java/org/apache/cxf/common/util/PackageUtils.java, core/src/main/java/org/apache/cxf/common/util/StringUtils.java, core/src/test/java/org/apache/cxf/common/util/StringUtilsTest.java, rt/frontend/jaxrs/src/main/java/org/apache/cxf/jaxrs/impl/HttpHeadersImpl.java, rt/frontend/jaxrs/src/test/java/org/apache/cxf/jaxrs/impl/HttpHeadersImplTest.java, rt/transports/http/src/main/java/org/apache/cxf/transport/http/AbstractHTTPDestination.java
=> CXF-7923 String.split via fastpath instead of precompiled Pattern

core/src/test/java/org/apache/cxf/workqueue/AutomaticWorkQueueTest.java, tools/corba/src/main/java/org/apache/cxf/tools/corba/processors/wsdl/WSDLToIDLAction.java, tools/corba/src/test/java/org/apache/cxf/tools/corba/IDLToWSDLTest.java, tools/corba/src/test/java/org/apache/cxf/tools/corba/WSDLToIDLTest.java, tools/corba/src/test/java/org/apache/cxf/tools/corba/common/ToolTestBase.java
this tests sometimes failed localy while rebuild whole project
=> improve tests stability

core/src/main/java/org/apache/cxf/common/util/PackageUtils.java, core/src/test/java/org/apache/cxf/common/util/PackageUtilsTest.java
=> [cxf-core] back PackageUtils.getPackageNameByNameSpaceURI logic from

rt/transports/http-undertow/src/main/java/org/apache/cxf/transport/http_undertow/blueprint/UndertowHTTPServerEngineFactoryHolder.java
Issue: https://jira.apache.org/jira/browse/CXF-7973
Adding protection from NPE which could occur.
=> CXF-7973 Add NPE guard for jetty and undertow threads configuration

parent/pom.xml
=> add cxf-rt-rs-security-http-signature to parent

parent/pom.xml, rt/bindings/pom.xml, systests/uncategorized/pom.xml, systests/uncategorized/src/test/java/org/apache/cxf/systest/corba/CorbaTimeoutTest.java
https://issues.apache.org/jira/browse/CXF-7953
=> CXF-7953 re-enable the corba binding and make sure it works with the JDK 11

rt/rs/security/http-signature/src/main/java/org/apache/cxf/rs/security/httpsignature/MessageSigner.java, rt/rs/security/http-signature/src/main/java/org/apache/cxf/rs/security/httpsignature/TomitribeSignatureCreator.java, rt/rs/security/http-signature/src/main/java/org/apache/cxf/rs/security/httpsignature/filters/AbstractSignatureOutFilter.java, rt/rs/security/http-signature/src/main/java/org/apache/cxf/rs/security/httpsignature/provider/PrivateKeyProvider.java, rt/rs/security/http-signature/src/test/java/org/apache/cxf/rs/security/httpsignature/MessageVerifierTest.java, rt/rs/security/http-signature/src/test/java/org/apache/cxf/rs/security/httpsignature/SpecExamplesTest.java, systests/rs-security/src/test/java/org/apache/cxf/systest/jaxrs/security/httpsignature/JAXRSHTTPSignatureTest.java, systests/rs-security/src/test/java/org/apache/cxf/systest/jaxrs/security/httpsignature/PrivateKeyProviderTestHelper.java, systests/rs-security/src/test/resources/org/apache/cxf/systest/jaxrs/security/httpsignature/server.xml
=> add a PrivateKeyProvider

rt/rs/security/http-signature/src/main/java/org/apache/cxf/rs/security/httpsignature/filters/CreateSignatureFilter.java, rt/rs/security/http-signature/src/main/java/org/apache/cxf/rs/security/httpsignature/filters/VerifySignatureClientFilter.java, rt/rs/security/http-signature/src/main/java/org/apache/cxf/rs/security/httpsignature/filters/VerifySignatureFilter.java
As discussed on mailinglist:
http://cxf.547215.n5.nabble.com/VerifySignatureFilter-phase-td5796123.html
=> Drop @PreMatching - no need for it

rt/rs/security/oauth-parent/oauth2/src/main/java/org/apache/cxf/rs/security/oauth2/client/OAuthClientUtils.java, rt/rs/security/oauth-parent/oauth2/src/test/java/org/apache/cxf/rs/security/oauth2/client/OAuthClientUtilsTest.java
avoid `java.lang.StringIndexOutOfBoundsException: String index out of range: -1`
=> cxf-rt-rs-security-oauth2: check response mediatype

rt/security/src/main/java/org/apache/cxf/rt/security/SecurityConstants.java, rt/ws/security/src/main/java/org/apache/cxf/ws/security/wss4j/AbstractWSS4JInterceptor.java, rt/ws/security/src/main/java/org/apache/cxf/ws/security/wss4j/AbstractWSS4JStaxInterceptor.java, systests/ws-security/src/test/resources/org/apache/cxf/systest/ws/x509/server.xml
This can't be merged until we release WSS4J 2.2.3
=> Adding support to configure the cert constaints separator.

rt/frontend/jaxrs/src/main/java/org/apache/cxf/jaxrs/spring/AbstractSpringConfigurationFactory.java
=> parse cxf.jaxrs.extensions like it done in CXFNonSpringJaxrsServlet

rt/features/logging/src/main/java/org/apache/cxf/ext/logging/LoggingOutInterceptor.java, rt/features/logging/src/main/java/org/apache/cxf/ext/logging/LoggingOutputStream.java, systests/jaxrs/src/test/java/org/apache/cxf/systest/jaxrs/logging/LoggingServer.java, systests/jaxrs/src/test/java/org/apache/cxf/systest/jaxrs/logging/LoggingTest.java
https://issues.apache.org/jira/browse/CXF-8079
=> CXF-8032 - Adding LoggingFeature enables chunking response

rt/frontend/jaxrs/src/main/java/org/apache/cxf/jaxrs/impl/RequestPreprocessor.java, rt/frontend/jaxrs/src/test/java/org/apache/cxf/jaxrs/impl/RequestPreprocessorTest.java, systests/jaxrs/src/test/java/org/apache/cxf/systest/jaxrs/JAXRSClientServerSpringBookTest.java
=> CXF-8133 - Disable JAX-RS HTTP method overriding by default

rt/transports/http/pom.xml
I'm having trouble building cxf behind a firewall and would like to add a property so that I can change the URL address to something my proxy will accept
=> Build behind firewall

distribution/pom.xml
Add a property for tarLongFileMode so we can build cxf with posix tarLongFileMode
=> Add a property for tarLongFileMode

osgi/itests/pom.xml, parent/pom.xml
Update to Jackson Databind 2.9.10.1
=> CXF-8157: Update to Jackson Databind 2.9.10.1

rt/rs/security/jose-parent/jose/src/main/java/org/apache/cxf/rs/security/jose/jwe/AesCbcContentEncryptionAlgorithm.java, rt/rs/security/jose-parent/jose/src/main/java/org/apache/cxf/rs/security/jose/jwe/AesCbcHmacJweEncryption.java, rt/rs/security/jose-parent/jose/src/main/java/org/apache/cxf/rs/security/jose/jwe/JweUtils.java, rt/rs/security/jose-parent/jose/src/test/java/org/apache/cxf/rs/security/jose/jwe/JweJsonProducerTest.java
Fixed:
- System.arraycopy src position
- exposed AesCbcContentEncryptionAlgorithm to make cek and iv reusable for all recipients
=> [CXF-8162] JWE with multiple recipients does not work for AES CBC Encryption

README.md
=> add GitHub badges

rt/transports/jms/src/test/java/org/apache/cxf/transport/jms/JMSDestinationTest.java
Changes in test case from https://github.com/apache/cxf/pull/603
=> [CXF-8161] test case with parallel error handling in JMSDestination and PollingMessageListenerContainer

rt/frontend/jaxrs/src/main/java/org/apache/cxf/jaxrs/utils/JAXRSUtils.java
Should fix:
allParamsInParamTest_from_standalone
allParamsOnFieldTest_from_standalone
formParamInParamTest_from_standalone
formParamOnFieldTest_from_standalone
=> CXF-7996: TCK: Resolves FormParam-related failures

osgi/karaf/features/src/main/resources/features.xml, parent/pom.xml, rt/features/metrics/pom.xml, rt/features/metrics/src/main/java/org/apache/cxf/metrics/codahale/CodahaleMetricsProvider.java, systests/jaxrs/src/test/java/org/apache/cxf/systest/jaxrs/metrics/JAXRSClientMetricsTest.java, systests/jaxrs/src/test/java/org/apache/cxf/systest/jaxrs/metrics/JAXRSServerMetricsTest.java, systests/jaxws/pom.xml
Update to Dropwizard Metrics 4.x
=> CXF-8102: Update to Dropwizard Metrics 4.x

distribution/src/main/release/samples/jax_rs/tracing_brave/pom.xml, parent/pom.xml
This is mainly to help someone on support who's trying to use latest stuff and having trouble aligning versions.
cc @timpeeters as he did a great job updating this last time in #639
=> Bumps to latest brave

core/pom.xml, distribution/javadoc/pom.xml, distribution/src/main/release/samples/jax_rs/description_swagger2_web/pom.xml, integration/spring-boot/autoconfigure/pom.xml, integration/spring-boot/starter-jaxrs/pom.xml, integration/spring-boot/starter-jaxws/pom.xml, osgi/itests/pom.xml, osgi/karaf/features/src/main/resources/features.xml, parent/pom.xml, rt/frontend/jaxrs/pom.xml, rt/rs/description-swagger/pom.xml, systests/cdi/base/pom.xml, systests/cdi/cdi-owb/pom.xml, systests/cdi/cdi-weld/pom.xml, systests/cdi/pom.xml, systests/jaxrs/pom.xml, systests/spring-boot/pom.xml, tools/wadlto/jaxrs/pom.xml
=> [CXF-8151] Upgrade to Bean Validation 2.x and Hibernate Validator 6.1.0

rt/transports/jms/src/main/java/org/apache/cxf/transport/jms/JMSDestination.java
CC @ffang 
Discussion thread: https://github.com/apache/cxf/pull/603/files#diff-fcece95462c2633e642f31c76583896c
=> CXF-8259: Blocked thread of JMS transport during jboss shutdown

osgi/karaf/features/src/main/resources/features.xml, parent/pom.xml
Depends on: https://github.com/apache/cxf/pull/638
Need to wait until the OpenSAML bundle is released.
=> Updating to OpenSAML bundle 3.4.5_2

rt/frontend/jaxrs/src/main/java/org/apache/cxf/jaxrs/model/URITemplate.java, rt/frontend/jaxrs/src/test/java/org/apache/cxf/jaxrs/model/URITemplateTest.java
=> Only add parenthesese to regex pattern when needed.

parent/pom.xml, rt/rs/microprofile-client/pom.xml, rt/rs/microprofile-client/src/main/java/org/apache/cxf/microprofile/client/CxfTypeSafeClientBuilder.java, rt/rs/microprofile-client/src/main/java/org/apache/cxf/microprofile/client/Utils.java, rt/rs/microprofile-client/src/main/java/org/apache/cxf/microprofile/client/sse/SseEventBuilder.java, rt/rs/microprofile-client/src/main/java/org/apache/cxf/microprofile/client/sse/SseMessageBodyReader.java, rt/rs/microprofile-client/src/main/java/org/apache/cxf/microprofile/client/sse/SsePublisher.java, rt/rs/microprofile-client/src/main/java/org/apache/cxf/microprofile/client/sse/SseSubscription.java, rt/rs/microprofile-client/src/main/java/org/apache/cxf/microprofile/client/sse/SseTypeSafeProcessor.java, rt/rs/microprofile-client/src/main/java/org/apache/cxf/microprofile/client/sse/SseTypeSafeSubscription.java, rt/rs/microprofile-client/src/test/java/org/apache/cxf/microprofile/client/sse/SseSubscriptionTest.java, systests/microprofile/client/weld/pom.xml, systests/microprofile/client/weld/testng.xml
Hi All - if you have time, could you review my changes for SSE support in MP Rest Client 2.0?  I developed this at the same time as the spec/API changes so there may need to be some tweaks to this implementation if the MP community requests changes to the spec/API.  
The relevant MP API issue is https://github.com/eclipse/microprofile-rest-client/issues/11 and my proposed spec/API/TCK changes are at https://github.com/eclipse/microprofile-rest-client/pull/266
Thanks!
=> [CXF-8263] Support SSEs in MP Rest Client 2.0

osgi/karaf/features/src/main/resources/features.xml, parent/pom.xml, systests/jaxrs/src/test/java/org/apache/cxf/systest/jaxrs/AtomBookStore.java, systests/jaxrs/src/test/java/org/apache/cxf/systest/jaxrs/AtomBookStore2.java, systests/jaxrs/src/test/java/org/apache/cxf/systest/jaxrs/AtomBookStore3.java
Updating to Swagger Core 2.1.3 and Jackson 2.11.1
=> CXF-8313: Updated to Swagger Core 2.1.3 / 1.6.2, Jackson 2.11.1

parent/pom.xml
Updating to Swagger Core 2.1.4
=> Updating to Swagger Core 2.1.4

parent/pom.xml
=> Update to Swagger 2.1.5

parent/pom.xml
Update to Apache Karaf 4.2.10 and Pax Exam 4.13.4
=> Update to Apache Karaf 4.2.10 and Pax Exam 4.13.4

rt/features/logging/src/main/java/org/apache/cxf/ext/logging/MaskSensitiveHelper.java, rt/features/logging/src/test/java/org/apache/cxf/ext/logging/MaskSensitiveHelperTest.java
Fixed mask for XML elements containing attributes
=> CXF-8359: fixed mask for XML elements containing attributes

rt/frontend/jaxrs/src/main/java/org/apache/cxf/jaxrs/utils/JAXRSUtils.java, systests/jaxrs/src/test/java/org/apache/cxf/systest/jaxrs/JAXRSMultipartLocalTransportTest.java, systests/jaxrs/src/test/java/org/apache/cxf/systest/jaxrs/MultipartStore.java
@andymc12 mind please to take a look, thanks!
=> CXF-8356: JAXRS Multipart-Handling broken for InputStream/Datasource parameters

distribution/src/main/release/samples/jax_rs/spring_boot/src/test/java/sample/rs/service/SampleRestApplicationTest.java, distribution/src/main/release/samples/jax_rs/spring_boot_scan/application/src/test/java/sample/rs/service/SampleRestApplicationTest.java, distribution/src/main/release/samples/jax_rs/spring_boot_scan/eureka-registry/pom.xml, distribution/src/main/release/samples/jaxws_spring_boot/pom.xml, distribution/src/main/release/samples/pom.xml, parent/pom.xml, pom.xml, systests/transports/pom.xml, tools/javato/ws/src/test/java/org/apache/cxf/tools/java2wsdl/processor/JavaToProcessorTest.java
Update to Spring Boot 2.4.0 
Update to Spring Framework 5.3.1
Update to Spring Security 5.4.1
Update to Project Reactor 3.4.0 
Update to Micrometer 1.6.1
=> Update to Spring Boot 2.4.0 / Spring Framework 5.3.1 / Spring Security 5.4.1 / Reactor 3.4.0 / Micrometer 1.6.1

rt/frontend/jaxrs/src/main/java/org/apache/cxf/jaxrs/impl/UriBuilderImpl.java, rt/frontend/jaxrs/src/test/java/org/apache/cxf/jaxrs/impl/UriBuilderImplTest.java
Signed-off-by: James Carman <jwcarman@gmail.com>
=> CXF-8376: Misleading Error Message From UriBuilder.path(Method)

parent/pom.xml
=> Update to Swagger UI 3.37.0

rt/rs/extensions/rx2/src/main/java/org/apache/cxf/jaxrs/rx2/server/ReactiveIOInvoker.java, rt/rs/extensions/rx3/src/main/java/org/apache/cxf/jaxrs/rx3/server/ReactiveIOInvoker.java, systests/jaxrs/src/test/java/org/apache/cxf/systest/jaxrs/reactive/JAXRSRxJava2MaybeTest.java, systests/jaxrs/src/test/java/org/apache/cxf/systest/jaxrs/reactive/JAXRSRxJava3MaybeTest.java, systests/jaxrs/src/test/java/org/apache/cxf/systest/jaxrs/reactive/RxJava2MaybeServer.java, systests/jaxrs/src/test/java/org/apache/cxf/systest/jaxrs/reactive/RxJava2MaybeService.java, systests/jaxrs/src/test/java/org/apache/cxf/systest/jaxrs/reactive/RxJava3MaybeServer.java, systests/jaxrs/src/test/java/org/apache/cxf/systest/jaxrs/reactive/RxJava3MaybeService.java, systests/jaxrs/src/test/java/org/apache/cxf/systest/jaxrs/reactor/MonoReactorTest.java
We do support `Flowable` / `Observale` / `Single` but not `Maybe`
=> CXF-8357: RxJava2/RxJava3: Add support of Maybe type

parent/pom.xml, systests/jaxrs/src/test/java/org/apache/cxf/systest/jaxrs/AtomBookStore.java, systests/jaxrs/src/test/java/org/apache/cxf/systest/jaxrs/AtomBookStore2.java, systests/jaxrs/src/test/java/org/apache/cxf/systest/jaxrs/AtomBookStore3.java, systests/jaxrs/src/test/java/org/apache/cxf/systest/jaxrs/nonspring/JAXRSNonSpringJaxrsServletTest.java
=> Update to Swagger Core 2.1.6

parent/pom.xml, rt/rs/microprofile-client/src/test/java/org/apache/cxf/microprofile/client/mock/MockConfig.java, rt/rs/microprofile-client/src/test/java/org/apache/cxf/microprofile/client/mock/MockConfigProviderResolver.java, systests/microprofile/client/jaxrs/src/test/java/org/apache/cxf/systest/microprofile/rest/client/MockConfig.java, systests/microprofile/client/jaxrs/src/test/java/org/apache/cxf/systest/microprofile/rest/client/MockConfigProviderResolver.java, systests/microprofile/client/weld/testng.xml
Update to MicroProfile 2.0.0-RC3
=> Update to MicroProfile 2.0.0-RC3

rt/transports/http/src/main/java/org/apache/cxf/transport/http/ReferencingAuthenticator.java
The `ReferencingAuthenticator` aggressively uses reflection over `java.net.Authenticator` class, which becomes closed by default with upcoming JDK16 release as part of `java.net` package sealing (see please https://openjdk.java.net/jeps/396 and summary https://cr.openjdk.java.net/~mr/jigsaw/jdk8-packages-denied-by-default).
This is an attempt to refactor the code using publicly available APIs only. 
@jimma @dkulp could you please take a look guys? 
Thanks a lot in advance!
=> CXF-8407: Incorporate changes caused by JEP-396 integration into JDK-16+ (part 2)

rt/features/logging/src/main/java/org/apache/cxf/ext/logging/MaskSensitiveHelper.java, rt/features/logging/src/test/java/org/apache/cxf/ext/logging/MaskSensitiveHelperTest.java
Fix the match pattern xml template for multiple elements in xml
=> Cxf 3891 regex for add sensitive element names is replace only the last element

core/src/main/java/org/apache/cxf/message/MessageUtils.java, rt/features/metrics/src/main/java/org/apache/cxf/metrics/micrometer/provider/StandardTags.java, rt/frontend/jaxrs/src/main/java/org/apache/cxf/jaxrs/JAXRSInvoker.java, rt/frontend/jaxrs/src/main/java/org/apache/cxf/jaxrs/interceptor/JAXRSInInterceptor.java, rt/frontend/jaxrs/src/main/java/org/apache/cxf/jaxrs/model/URITemplate.java, rt/frontend/jaxrs/src/main/java/org/apache/cxf/jaxrs/utils/JAXRSUtils.java, systests/spring-boot/src/test/java/org/apache/cxf/systest/jaxrs/applications/LibraryApplication.java, systests/spring-boot/src/test/java/org/apache/cxf/systest/jaxrs/resources/Catalog.java, systests/spring-boot/src/test/java/org/apache/cxf/systest/jaxrs/resources/Library.java, systests/spring-boot/src/test/java/org/apache/cxf/systest/jaxrs/spring/boot/SpringJaxrsApplicationTest.java
Tagging the URI template (`/api/library/{id}`) instead of exact URI (`/api/library/100`) for JAX-RS resources
=> CXF-8424: Use template URL instead of actual path values for JAX-RS micrometer metrics

bom/pom.xml
Add missing artifact to bom: https://github.com/apache/cxf/blob/master/rt/rs/security/xml/pom.xml#L22
=> Add missing cxf-rt-rs-security-xml dep to bom

osgi/bundle/pom.xml, osgi/bundle/servlet-compatible/pom.xml, osgi/karaf/features/pom.xml, osgi/karaf/features/src/main/resources/features.xml, osgi/karaf/features/src/main/resources/org.apache.karaf.features.xml, parent/pom.xml
=> CXF-8377: Update to Apache Karaf 4.3.1

rt/databinding/jaxb/src/main/java/org/apache/cxf/jaxb/JAXBDataBinding.java
Creates a reordered JAXBDataBinding implementation that permits expanding internal class list
=> [CXF-8450] Creates a CachedJAXBDataBinding

integration/cdi/src/main/java/org/apache/cxf/cdi/JAXRSCdiResourceExtension.java, integration/cdi/src/test/java/org/apache/cxf/cdi/JAXRSCdiResourceExtensionTest.java, systests/cdi/base/src/main/java/org/apache/cxf/systests/cdi/base/AbstractCdiMultiAppTest.java, systests/cdi/base/src/main/java/org/apache/cxf/systests/cdi/base/contract/BookStore.java, systests/cdi/base/src/main/java/org/apache/cxf/systests/cdi/base/contract/BookStoreImpl.java, systests/cdi/cdi-owb/cdi-multiple-apps-owb/src/test/java/org/apache/cxf/systest/jaxrs/BookStoreCustomApplication.java, systests/cdi/cdi-weld/cdi-multiple-apps-weld/src/test/java/org/apache/cxf/systest/jaxrs/BookStoreCustomApplication.java
JAXRS CDI extension ignores interfaces annotations
=> CXF-7921: JAXRS CDI extension ignores interfaces annotations

parent/pom.xml
Update to Jackson Core and Jackson Databind to 2.12.3 #781
=> Update to Jackson Core and Jackson Databind to 2.12.3

parent/pom.xml
Update Dropwizard Metrics to 4.1.21
=> Update Dropwizard Metrics to 4.1.21

parent/pom.xml
=> Update Ehcache to 3.9.3

parent/pom.xml
Incorporate changes caused by JEP-396 integration into JDK-16+
=> CXF-8407: Incorporate changes caused by JEP-396 integration into JDK-16+

rt/rs/sse/src/main/java/org/apache/cxf/jaxrs/sse/client/SseEventSourceImpl.java
Fixing SseEventSource isOpen() semantics (addressing JAX-RS TCK failures) #796
=> Fixing SseEventSource isOpen() semantics (addressing JAX-RS TCK failures)

parent/pom.xml
Update Spring LDAP to 2.3.4.RELEASE
=> Update Spring LDAP to 2.3.4.RELEASE

parent/pom.xml
Update Jetty to 9.4.41.v20210516
=> Update Jetty to 9.4.41.v20210516

parent/pom.xml
=> Update Netty to 4.1.65.Final

distribution/src/main/release/samples/pom.xml, parent/pom.xml
Update to Spring Boot 2.5.0 and Spring Security 5.5.0
=> CXF-8528: Update to Spring Boot 2.5.0

parent/pom.xml
=> Update to Dropwizard 4.2.0

parent/pom.xml, rt/rs/security/http-signature/pom.xml, rt/rs/security/http-signature/src/test/java/org/apache/cxf/rs/security/httpsignature/SpecExamplesTest.java
=> CXF-8548: Get rid of Powermock usage

systests/transports/src/test/java/org/apache/cxf/systest/http/BadGreeterImpl.java, systests/transports/src/test/java/org/apache/cxf/systest/http/BadServer.java, systests/transports/src/test/java/org/apache/cxf/systest/http/HTTPConduitIoExceptionsTest.java
Adding test cases for HTTPConduit handlin 503/404 w/o IO exceptions
=> Adding test cases for HTTPConduit handling 503/404 w/o IO exceptions

rt/frontend/jaxrs/src/main/java/org/apache/cxf/jaxrs/utils/JAXRSUtils.java, systests/jaxrs/src/test/java/org/apache/cxf/systest/jaxrs/JAXRS20ClientServerBookTest.java
Fixing CXF-8514 & CXF-8515, NPE during ResourceContext contextual injection
=> Fixing CXF-8514 & CXF-8515, NPE during ResourceContext contextual injection

systests/rs-sse/rs-sse-base/src/main/java/org/apache/cxf/systest/jaxrs/sse/AbstractSseTest.java, systests/rs-sse/rs-sse-base/src/main/java/org/apache/cxf/systest/jaxrs/sse/BookStore.java, systests/rs-sse/rs-sse-base/src/main/java/org/apache/cxf/systest/jaxrs/sse/BookStore2.java
Create a failing test to show that SSE doesn't work for POST resource methods
=> [CXF-8544] JAX-RS server-side SSE using POST

rt/rs/sse/src/main/java/org/apache/cxf/jaxrs/sse/client/InboundSseEventProcessor.java, rt/rs/sse/src/main/java/org/apache/cxf/jaxrs/sse/client/SseEventSourceImpl.java, rt/rs/sse/src/test/java/org/apache/cxf/jaxrs/sse/client/SseEventSourceImplTest.java
According to the specification [1]:
> Once the end of the file is reached, any pending data must be discarded. (If the file ends in the middle of an event, before the final empty line, the incomplete event is not dispatched.)
[1] https://html.spec.whatwg.org/multipage/server-sent-events.html#parsing-an-event-stream
=> CXF-8561: SseEventSource sometimes sends partial events when being closed

parent/pom.xml
Added `cxf.bundle.activation.policy` property to provide the ability to override bundle activation policy
=> Added cxf.bundle.activation.policy property to provide the ability to override bundle activation policy

parent/pom.xml
=> Update Netty to 4.1.67.Final

parent/pom.xml
=> Update Mockito to 3.12.4

parent/pom.xml
=> Update Jackson to 2.12.5

rt/bindings/soap/src/main/java/org/apache/cxf/binding/soap/interceptor/SoapHeaderInterceptor.java
It seems like we don't need to check the schema enabled flag and get schema on every iteration for a SoapHeder.
Removing these actions outside of the loop can provide a slight performance improvement if multiple headers are present in the request.
=> CXF-8587: Don't check the validation flag and get the schema on every iteration for SoapHeader.

parent/pom.xml
=> Update Netty to 4.1.68.Final

parent/pom.xml
=> Update JUnit to 5.8.0

distribution/src/main/release/samples/pom.xml, parent/pom.xml, rt/rs/description-swagger-ui/src/main/java/org/apache/cxf/jaxrs/swagger/ui/SwaggerUiConfig.java
Adds `tryItOutEnabled` configuration option
=> CXF-8600: Swagger2Feature : Upgrade SwaggerUiConfig to add more configs (tryItOutEnabled)

parent/pom.xml
Update Swagger to 1.6.3 and Swagger2 to 2.1.11
=> Update Swagger to 1.6.3 and Swagger2 to 2.1.11

parent/pom.xml, systests/transports/src/test/resources/org/apache/cxf/systest/http_jetty/jettyBasicAuthServer.xml
Update Jetty to 9.4.44.v20210927
=> Update Jetty to 9.4.44.v20210927

rt/rs/security/oauth-parent/oauth2/src/main/java/org/apache/cxf/rs/security/oauth2/provider/AbstractOAuthDataProvider.java, systests/rs-security/src/test/java/org/apache/cxf/systest/jaxrs/security/oauth2/filters/OAuth2JwtFiltersTest.java, systests/rs-security/src/test/java/org/apache/cxf/systest/jaxrs/security/oauth2/grants/AuthorizationGrantTest.java
https://datatracker.ietf.org/doc/html/rfc8693#section-4.2
=> cxf-rt-rs-security-oauth2: fix 'scope' jwt claim format

parent/pom.xml, rt/features/metrics/pom.xml
Minor dependency updates and alignments
=> Minor dependency updates and alignments

parent/pom.xml
=> Update Mockito to 4.1.0

parent/pom.xml, rt/rs/microprofile-client/pom.xml, systests/microprofile/client/async/pom.xml, systests/microprofile/client/nocdi/pom.xml
Minor wiremock and mockwebserver dependency updates
=> Minor wiremock and mockwebserver dependency updates

parent/pom.xml, pom.xml
Update maven-javadoc-plugin to 3.3.1
=> Update maven-javadoc-plugin to 3.3.1

distribution/src/main/release/samples/pom.xml, osgi/karaf/features/src/main/resources/features.xml, parent/pom.xml
=> Update Netty to 4.1.72.Final

parent/pom.xml
Update Swagger to 1.6.4 and 2.1.12
=> Update Swagger to 1.6.4 and 2.1.12

parent/pom.xml, systests/cdi/pom.xml
Update Apache Openwebbeans to 2.0.25
=> Update Apache Openwebbeans to 2.0.25

core/src/main/java/org/apache/cxf/staxutils/transform/InTransformReader.java, core/src/test/java/org/apache/cxf/staxutils/transform/InTransformReaderTest.java
StaxTransformFeature deep-dropping doesn't work with any element
=> CXF-8632: StaxTransformFeature deep-dropping doesn't work with any element

parent/pom.xml
Update Apache HttpClient 4.x and 5.x
=> Update Apache HttpClient 4.x and 5.x

core/src/main/java/org/apache/cxf/interceptor/security/NameDigestPasswordCallbackHandler.java, core/src/main/java/org/apache/cxf/interceptor/security/NamePasswordCallbackHandler.java, core/src/test/java/org/apache/cxf/interceptor/security/NamePasswordCallbackHandlerTest.java, rt/transports/http/src/main/java/org/apache/cxf/transport/servlet/servicelist/ServiceListJAASAuthenticator.java
https://issues.apache.org/jira/projects/CXF/issues/CXF-8641
=> [CXF-8641] NPE on NamePasswordCallbackHandler

systests/jaxrs/src/test/java/org/apache/cxf/systest/jaxrs/BookServer20.java, systests/jaxrs/src/test/java/org/apache/cxf/systest/jaxrs/BookStore.java, systests/jaxrs/src/test/java/org/apache/cxf/systest/jaxrs/JAXRS20ClientServerBookTest.java
Added test case for response entity with annotations
=> Added test case for response entity with annotations

distribution/src/main/release/samples/pom.xml, parent/pom.xml
Update Jetty to 9.4.45.v20220203
=> Update Jetty to 9.4.45.v20220203

osgi/karaf/features/src/main/resources/features.xml, parent/pom.xml
=> Update Swagger to 1.6.5

parent/pom.xml
=> Update Swagger to 2.1.13

rt/frontend/jaxrs/src/main/java/org/apache/cxf/jaxrs/ext/MessageContextImpl.java, rt/frontend/jaxrs/src/test/java/org/apache/cxf/jaxrs/ext/MessageContextImplTest.java
Headers are copied as case sensitive in `MessageContextImpl`
=> CXF-8657: Headers are copied as case sensitive in MessageContextImpl

distribution/src/main/release/samples/pom.xml, parent/pom.xml
=> Update Tika to 2.3.0

rt/transports/http/pom.xml
Update download-maven-plugin to 1.6.8
=> Update download-maven-plugin to 1.6.8

Jenkinsfile, benchmark/performance/base/pom.xml, benchmark/performance/soap_http_doc_lit/pom.xml, distribution/src/main/release/samples/jax_rs/basic_http2_jetty/pom.xml, distribution/src/main/release/samples/pom.xml, maven-plugins/archetypes/cxf-jaxrs-service/src/main/resources/archetype-resources/pom.xml, maven-plugins/archetypes/cxf-jaxws-javafirst/src/main/resources/archetype-resources/pom.xml, maven-plugins/archetypes/cxf-jaxws-wsdlfirst/src/main/resources/archetype-resources/pom.xml, maven-plugins/codegen-plugin/src/it/jaxb-xjc-runtime-sources/pom.xml, maven-plugins/codegen-plugin/src/it/jdk-cxf-with-toolchain/pom.xml, maven-plugins/codegen-plugin/src/it/mark-generated/pom.xml, maven-plugins/codegen-plugin/src/it/wsdl-artifact-resolution/pom.xml, maven-plugins/wadl2java-plugin/src/it/wadl-generate-rx/pom.xml, maven-plugins/wadl2java-plugin/src/it/wsdl-artifact-resolution/pom.xml, parent/pom.xml, pom.xml, systests/transports/pom.xml, systests/wsdl_maven/codegen/src/it/it-parent/pom.xml
Set minimum JDK baseline to 11
=> CXF-8660: Set minimum JDK baseline to 11

pom.xml
Update major Maven plugins to latest versions
=> Update major Maven plugins to latest versions

parent/pom.xml
=> Update to Mockito 4.4.0

parent/pom.xml, rt/transports/http-hc/src/main/java/org/apache/cxf/transport/http/asyncclient/AsyncHTTPConduit.java
Bump httpasyncclient version to 4.1.5
=> CXF-8673: Bump httpasyncclient version to 4.1.5

rt/transports/http/pom.xml
OSGi: temporary exclude org/apache/cxf/transport/http/osgi/**.java from compilation
=> OSGi: temporary exclude org/apache/cxf/transport/http/osgi/**.java from compilation

distribution/src/main/release/samples/pom.xml, parent/pom.xml
Update Jetty to 9.4.46.v20220331
=> Update Jetty to 9.4.46.v20220331

parent/pom.xml, rt/rs/security/oauth-parent/oauth2-saml/src/main/java/org/apache/cxf/rs/security/oauth2/saml/SamlOAuthValidator.java, rt/rs/security/sso/saml/src/main/java/org/apache/cxf/rs/security/saml/sso/SAMLProtocolResponseValidator.java, rt/rs/security/sso/saml/src/main/java/org/apache/cxf/rs/security/saml/sso/SAMLSSOResponseValidator.java, rt/rs/security/sso/saml/src/main/java/org/apache/cxf/rs/security/saml/sso/SamlpRequestComponentBuilder.java, rt/rs/security/sso/saml/src/test/java/org/apache/cxf/rs/security/saml/sso/AbstractSAMLCallbackHandler.java, rt/rs/security/sso/saml/src/test/java/org/apache/cxf/rs/security/saml/sso/CombinedValidatorTest.java, rt/rs/security/sso/saml/src/test/java/org/apache/cxf/rs/security/saml/sso/SAML2PResponseComponentBuilder.java, rt/rs/security/sso/saml/src/test/java/org/apache/cxf/rs/security/saml/sso/SAMLResponseValidatorTest.java, rt/rs/security/sso/saml/src/test/java/org/apache/cxf/rs/security/saml/sso/SAMLSSOResponseValidatorTest.java, rt/security-saml/src/main/java/org/apache/cxf/rt/security/saml/xacml2/DefaultXACMLRequestBuilder.java, rt/security-saml/src/main/java/org/apache/cxf/rt/security/saml/xacml2/SamlRequestComponentBuilder.java, rt/security-saml/src/test/java/org/apache/cxf/rt/security/saml/xacml2/RequestComponentBuilderTest.java, services/sts/sts-core/src/main/java/org/apache/cxf/sts/token/provider/SAMLTokenProvider.java, services/sts/sts-core/src/main/java/org/apache/cxf/sts/token/renewer/SAMLTokenRenewer.java, services/sts/sts-core/src/main/java/org/apache/cxf/sts/token/validator/SAMLTokenValidator.java, services/sts/systests/advanced/src/test/resources/org/apache/cxf/systest/sts/custom/cxf-sts.xml, services/sts/systests/basic/src/test/resources/org/apache/cxf/systest/sts/rest/cxf-rest-sts.xml, services/sts/systests/pom.xml, services/xkms/pom.xml, systests/rs-security/src/test/java/org/apache/cxf/systest/jaxrs/security/oauth2/common/SamlCallbackHandler.java, systests/rs-security/src/test/java/org/apache/cxf/systest/jaxrs/security/saml/SamlCallbackHandler.java, systests/rs-security/src/test/resources/org/apache/cxf/systest/jaxrs/security/jose/jwejws/server.xml, systests/rs-security/src/test/resources/org/apache/cxf/systest/jaxrs/security/jose/jwejws/serverJwsJson.xml, systests/rs-security/src/test/resources/org/apache/cxf/systest/jaxrs/security/oauth2/filters/filters-server.xml, systests/rs-security/src/test/resources/org/apache/cxf/systest/jaxrs/security/oauth2/filters/filters-serverJwt.xml
Merge Opensaml4 to Jakarta EE branch
=> Merge Opensaml4 to Jakarta EE branch

parent/pom.xml
Fix failures in karaf related scenarios
Signed-off-by: Raymond Augé <rotty3000@apache.org>
=> update to released karaf 4.4.0

osgi/karaf/features/src/main/resources/features.xml
Use the right version of the jakarta.jws-api in Karaf features
=> Use the right version of the jakarta.jws-api in Karaf features

parent/pom.xml
=> Upgrade tomitribe signing library

distribution/src/main/release/samples/pom.xml, parent/pom.xml, rt/rs/description-swagger-ui/src/main/java/org/apache/cxf/jaxrs/swagger/ui/SwaggerUiService.java, systests/jaxrs/src/test/java/org/apache/cxf/systest/jaxrs/description/SwaggerUiConfigurationQueryConfigTest.java, systests/jaxrs/src/test/java/org/apache/cxf/systest/jaxrs/description/SwaggerUiConfigurationTest.java
=> CXF-8683: Support SwaggerUI 4.10.3+

.github/workflows/codeql-analysis.yml
Adding 3.6.x-fixes to CodeQL analysis
=> Adding 3.6.x-fixes to CodeQL analysis

parent/pom.xml
=> Update to Swagger Core to 2.2.1

distribution/src/main/release/samples/pom.xml, parent/pom.xml
Update Jetty to 9.4.47.v20220610
=> Update Jetty to 9.4.47.v20220610

core/src/main/java/org/apache/cxf/message/MessageUtils.java, core/src/test/java/org/apache/cxf/message/MessageUtilsTest.java, rt/transports/http/src/main/java/org/apache/cxf/transport/http/HTTPConduit.java
"org.apache.cxf.transport.service_not_available" for 404 responses
=> CXF-8725: Allow RetryStrategy to optionally not retry for 404 responses

parent/pom.xml, rt/rs/extensions/search/src/test/resources/META-INF/persistence.xml, rt/rs/security/oauth-parent/oauth2/pom.xml, rt/rs/security/oauth-parent/oauth2/src/main/java/org/apache/cxf/rs/security/oauth2/grants/code/JPACodeDataProvider.java, rt/rs/security/oauth-parent/oauth2/src/main/java/org/apache/cxf/rs/security/oauth2/provider/JPAOAuthDataProvider.java, rt/rs/security/oauth-parent/oauth2/src/test/resources/META-INF/persistence.xml, rt/rs/security/sso/oidc/pom.xml, systests/rs-security/pom.xml
=> CXF-8736: Migration path for OpenJPA

core/pom.xml, distribution/src/main/release/samples/pom.xml, parent/pom.xml, pom.xml, rt/bindings/soap/pom.xml, rt/frontend/jaxrs/pom.xml, rt/frontend/jaxws/pom.xml, services/wsn/wsn-core/pom.xml
Switching from `com.sun.activation/jakarta.activation` to `org.eclipse.angus/angus-activation`
=> Switching from com.sun.activation/jakarta.activation to org.eclipse.angus/angus-activation (continued)

rt/rs/description-swagger-ui/src/main/java/org/apache/cxf/jaxrs/swagger/ui/SwaggerUiService.java
Fix check for queryConfigEnabled
=> [CXF-8738] fix check for queryConfigEnabled

osgi/itests/src/test/java/org/apache/cxf/osgi/itests/jaxrs/JaxRsServiceTest.java, osgi/itests/src/test/java/org/apache/cxf/osgi/itests/jaxrs/JaxRsTestActivator.java
Attempt to fix flaky JaxRsServiceTest tests (CXF-8750 post merge)
=> Attempt to fix flaky JaxRsServiceTest tests (CXF-8750 post merge)

osgi/itests/src/test/java/org/apache/cxf/osgi/itests/jaxrs/BookStore.java, osgi/itests/src/test/java/org/apache/cxf/osgi/itests/jaxrs/OpenApiBookStore.java, osgi/itests/src/test/java/org/apache/cxf/osgi/itests/jaxrs/OpenApiServiceTest.java, osgi/itests/src/test/java/org/apache/cxf/osgi/itests/jaxrs/OpenApiTestActivator.java
Attempt to fix flaky JaxRsServiceTest tests (CXF-8750 post merge): split into separate test cases
=> Attempt to fix flaky JaxRsServiceTest tests (CXF-8750 post merge): split into separate test cases

core/src/main/java/org/apache/cxf/message/MessageUtils.java, core/src/test/java/org/apache/cxf/message/MessageUtilsTest.java, rt/transports/http/src/main/java/org/apache/cxf/transport/http/HTTPConduit.java
https://issues.apache.org/jira/browse/CXF-8752
=> feat(CXF-8752): list of redirectable verbs configurable.

rt/transports/http/src/test/java/org/apache/cxf/transport/http/HTTPConduitURLEasyMockTest.java
Added test case for HTTPConduit's 'http.redirect.allowed.verbs' context property
=> Added test case for HTTPConduit's 'http.redirect.allowed.verbs' context property

parent/pom.xml
=> CXF-8756: Update to Swagger UI 4.14.0

rt/features/clustering/src/main/java/org/apache/cxf/clustering/AbstractStaticFailoverStrategy.java, rt/features/clustering/src/main/java/org/apache/cxf/clustering/RetryStrategy.java, rt/features/clustering/src/main/java/org/apache/cxf/clustering/SequentialStrategy.java, systests/jaxrs/src/test/java/org/apache/cxf/systest/jaxrs/failover/AbstractFailoverTest.java
Immediately switch to the next alternate (address or endpoint) if the
current one has already exceeded the maxNumberOfRetries
=> CXF-8712 One-off issue with retries

core/src/main/java/org/apache/cxf/bus/spring/SpringBeanLocator.java, parent/pom.xml, rt/frontend/jaxrs/src/main/java/org/apache/cxf/jaxrs/provider/JAXBElementProvider.java, rt/rs/microprofile-client/src/test/java/org/apache/cxf/microprofile/client/AsyncTest.java, rt/transports/jms/src/main/java/org/apache/cxf/transport/jms/JMSMessageHeadersType.java, systests/jaxrs/pom.xml, systests/jaxrs/src/test/java/org/apache/cxf/systest/jaxrs/JAXRS20ClientServerBookTest.java, systests/jaxrs/src/test/java/org/apache/cxf/systest/jaxrs/JAXRSRequestDispatcherTest.java, systests/jaxrs/src/test/java/org/apache/cxf/systest/jaxrs/JMSBookStore.java, systests/jaxrs/src/test/java/org/apache/cxf/systest/jaxrs/jms/JAXRSJmsTest.java, systests/jaxrs/src/test/java/org/apache/cxf/systest/jaxrs/metrics/JAXRSClientMetricsTest.java, systests/jaxrs/src/test/java/org/apache/cxf/systest/jaxrs/security/BookServerSecuritySpringClass.java, systests/jaxrs/src/test/resources/files/swagger.properties, systests/jaxrs/src/test/resources/jaxrs/WEB-INF/beans.xml, systests/jaxrs/src/test/resources/jaxrs_cors/WEB-INF/beans.xml, systests/jaxrs/src/test/resources/jaxrs_dispatch/WEB-INF/web.xml, systests/jaxrs/src/test/resources/jaxrs_jackson_provider/WEB-INF/beans.xml, systests/jaxrs/src/test/resources/jaxrs_non_spring/WEB-INF/web.xml, systests/jaxrs/src/test/resources/jaxrs_security/WEB-INF/beans.xml, systests/jaxrs/src/test/resources/jaxrs_security_cglib/WEB-INF/beans.xml, systests/jaxrs/src/test/resources/jaxrs_security_no_annotations/WEB-INF/beans.xml, systests/pom.xml
Include back `jaxrs` systests module
=> Include back jaxrs systests module

parent/pom.xml
Update EasyMock to 5.0.1 (part of CXF-8407)
=> Update EasyMock to 5.0.1 (part of CXF-8407)

parent/pom.xml
=> CXF-8755: Update to Slf4j 2.0

rt/frontend/jaxrs/src/test/java/org/apache/cxf/jaxrs/utils/InjectionUtilsTest.java, systests/jaxrs/src/test/java/org/apache/cxf/systest/jaxrs/BookStore.java, systests/jaxrs/src/test/java/org/apache/cxf/systest/jaxrs/JAXRSLocalTransportTest.java
Added more test for using factory methods as parameter converters
=> Added more test for using factory methods as parameter converters

parent/pom.xml, rt/rs/extensions/providers/src/main/java/org/apache/cxf/jaxrs/provider/jsrjsonb/JsrJsonbProvider.java, rt/rs/microprofile-client/pom.xml, rt/rs/microprofile-client/src/main/java/org/apache/cxf/microprofile/client/MicroProfileClientFactoryBean.java
Fix Microptofile Rest Client TCK by including JSONB provider by default
=> CXF-8782: Include JSONB provider in MicroProfile Rest Client by default

rt/rs/sse/pom.xml, rt/rs/sse/src/test/java/org/apache/cxf/jaxrs/sse/SseBroadcasterImplTest.java, rt/rs/sse/src/test/java/org/apache/cxf/jaxrs/sse/SseEventSinkContextProviderTest.java, rt/rs/sse/src/test/java/org/apache/cxf/jaxrs/sse/TestAsyncContext.java
Address tests failures due to Servlet 6.0 baseline in Spring Test
=> CXF-8792: Address tests failures due to Servlet 6.0 baseline in Spring Test

bom/pom.xml
Noticed there were some missing BOM entries for some of the CXF artifacts, and could not find cxf-services-sts-war.
=> Reconcile CXF bom with current artifacts

distribution/src/main/release/samples/jax_rs/search/pom.xml, distribution/src/main/release/samples/jax_rs/search/src/main/java/demo/jaxrs/search/server/Catalog.java, distribution/src/main/release/samples/pom.xml, parent/pom.xml, rt/rs/extensions/search/pom.xml, systests/jaxrs/pom.xml, systests/jaxrs/src/test/java/org/apache/cxf/systest/jaxrs/extraction/BookCatalog.java
=> CXF-8794: Update to Lucene 9.4.x

parent/pom.xml
=> Update Spring LDAP to 3.0.0

parent/pom.xml
Update Spring Security to 5.8.0
=> Update Spring Security to 5.8.0

distribution/src/main/release/samples/jax_rs/spring_boot_scan/application/src/main/java/sample/rs/service/SampleRestApplication.java, distribution/src/main/release/samples/jax_rs/spring_boot_scan/client/src/main/java/sample/rs/client/SampleRestClientApplication.java, distribution/src/main/release/samples/pom.xml, parent/pom.xml
Update Spring Framework to 6.0.2 and Spring Boot to 3.0.0
=> Update Spring Framework to 6.0.2 and Spring Boot to 3.0.0

core/src/main/java/org/apache/cxf/attachment/AttachmentUtil.java, core/src/test/java/org/apache/cxf/attachment/AttachmentDeserializerTest.java, systests/uncategorized/pom.xml, systests/uncategorized/src/test/java/org/apache/cxf/systest/mtom/request-url-attachment
CXF MTOM handler allow content injection
=> CXF-8706: CXF MTOM handler allow content injection

parent/pom.xml, tools/wadlto/jaxrs/pom.xml, tools/wadlto/jaxrs/src/test/java/org/apache/cxf/tools/wadlto/jaxrs/WADLToJavaTest.java
Migration path for jaxb2-basics to hisrc-basicjaxb
=> CXF-8774: Migration path for jaxb2-basics (to hisrc-basicjaxb)

rt/frontend/jaxrs/src/main/java/org/apache/cxf/jaxrs/model/OperationResourceInfo.java, rt/frontend/jaxrs/src/test/java/org/apache/cxf/jaxrs/model/OperationResourceInfoTest.java
` NameBinding` ignored when implementing interface
=> CXF-8797: NameBinding ignored when implementing interface

integration/jca/src/test/java/org/apache/cxf/jca/cxf/ConnectionFactoryImplTest.java, parent/pom.xml, rt/transports/http/src/test/java/org/apache/cxf/transport/https/HttpsURLConnectionFactoryTest.java
=> Update EasyMock to 5.1.0

distribution/src/main/release/samples/pom.xml, pom.xml
Update maven-surefire-plugin to 3.0.0-M8
=> Update maven-surefire-plugin to 3.0.0-M8

parent/pom.xml
=> Update Mockito to 5.1.0

parent/pom.xml, services/xkms/xkms-x509-handlers/pom.xml
Remove org.eclipse.tycho plugins since OSGi support is removed
=> CXF-8821: Remove org.eclipse.tycho plugins since OSGi support is removed

core/src/main/java/org/apache/cxf/bus/spring/SpringBus.java
The ApplicationListener, which redirects all ApplicationEvents to the SpringBus, now uses a WeakReference to allow a GC if the SpringBus is no longer in use because it's corresponding context has been closed.
=> [CXF-8745] ApplicationListener on SpringBus uses WeakReference

rt/transports/http-hc/src/test/java/org/apache/cxf/transport/http/asyncclient/AsyncHTTPConduitLargeResponseTest.java, rt/transports/http-hc5/src/main/java/org/apache/cxf/transport/http/asyncclient/hc5/SharedInputBuffer.java, rt/transports/http-hc5/src/test/java/org/apache/cxf/transport/http/asyncclient/hc5/AsyncHTTPConduitLargeResponseTest.java
AsyncHTTPConduit (hc5) - Unexpected EOF during response processing (tests contributed by https://github.com/magnho/cxf/pull/1)
=> CXF-8826: AsyncHTTPConduit (hc5) - Unexpected EOF during response processing

integration/spring-boot/autoconfigure/src/main/java/org/apache/cxf/spring/boot/autoconfigure/jaxws/CxfJaxwsAutoConfiguration.java, integration/spring-boot/autoconfigure/src/main/resources/META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports, systests/spring-boot/src/test/java/org/apache/cxf/systest/jaxrs/spring/boot/SpringClientOnlyJaxrsTest.java, systests/spring-boot/src/test/java/org/apache/cxf/systest/jaxrs/spring/boot/SpringJaxrsApplicationTest.java, systests/spring-boot/src/test/java/org/apache/cxf/systest/jaxrs/spring/boot/SpringJaxrsClassesScanningTest.java, systests/spring-boot/src/test/java/org/apache/cxf/systest/jaxrs/spring/boot/SpringJaxrsComponentScanningTest.java, systests/spring-boot/src/test/java/org/apache/cxf/systest/jaxrs/spring/boot/SpringJaxrsTest.java, systests/spring-boot/src/test/java/org/apache/cxf/systest/jaxrs/spring/boot/SpringSseEmitterTest.java, systests/spring-boot/src/test/java/org/apache/cxf/systest/jaxws/resources/HelloServiceWithContextImpl.java, systests/spring-boot/src/test/java/org/apache/cxf/systest/jaxws/spring/boot/SpringJaxwsInjectionTest.java, systests/spring-boot/src/test/java/org/apache/cxf/systest/jaxws/spring/boot/SpringJaxwsTest.java
JSR 250 annotations aren't disabled for jakarta.xml.ws.WebServiceContext for Spring Framework 6
=> CXF-8666: JSR 250 annotations aren't disabled for jakarta.xml.ws.WebServiceContext for Spring Framework 6

core/src/main/java/org/apache/cxf/transport/common/gzip/GZIPInInterceptor.java, core/src/test/java/org/apache/cxf/common/gzip/GZIPInInterceptorTest.java
GZIPInInterceptor, when processing HTTP 204 empty response,throws EOFException
=> CXF-8833: GZIPInInterceptor, when processing HTTP 204 empty response,throws EOFException

rt/transports/http-hc5/src/main/java/org/apache/cxf/transport/http/asyncclient/hc5/CXFHttpAsyncResponseConsumer.java, rt/transports/http-netty/netty-client/src/main/java/org/apache/cxf/transport/http/netty/client/NettyHttpClientHandler.java, rt/transports/http-netty/netty-client/src/main/java/org/apache/cxf/transport/http/netty/client/NettyHttpConduit.java, rt/transports/http-netty/netty-client/src/test/java/org/apache/cxf/transport/http/netty/client/NettyHttpConduitTest.java
Fix org.apache.cxf.transport.http.netty.client.NettyHttpConduitTest.testCallAsyncCallbackInvokedOnlyOnce
=> CXF-8830: Fix org.apache.cxf.transport.http.netty.client.NettyHttpConduitTest.testCallAsyncCallbackInvokedOnlyOnce

parent/pom.xml
Supercedes https://github.com/apache/cxf/pull/1248
=> Upgrading to Jackson 2.15.0

rt/transports/http-hc5/src/main/java/org/apache/cxf/transport/http/asyncclient/hc5/AsyncHTTPConduit.java, rt/transports/http-hc5/src/main/java/org/apache/cxf/transport/http/asyncclient/hc5/CXFHttpAsyncRequestProducer.java, systests/transport-hc5/pom.xml, systests/transport-hc5/src/test/java/org/apache/cxf/systest/hc5/http/auth/DigestAuthSupplierSpringTest.java, systests/transport-hc5/src/test/java/org/apache/cxf/systest/hc5/http/auth/DigestAuthTest.java, systests/transport-hc5/src/test/java/org/apache/cxf/systest/hc5/http/auth/DigestServer.java, systests/transport-hc5/src/test/java/org/apache/cxf/systest/hc5/http/auth/GreeterImpl.java, systests/transport-hc5/src/test/java/org/apache/cxf/systest/hc5/http/auth/jetty-realm.properties, systests/transport-hc5/src/test/resources/digestauth/WEB-INF/beans.xml, systests/transport-hc5/src/test/resources/digestauth/WEB-INF/web.xml, systests/transport-hc5/src/test/resources/logging.properties, systests/transport-hc5/src/test/resources/org/apache/cxf/systest/hc5/http/greeting.wsdl
Apache HttpClient 5 async conduit does not handle authentication
=> CXF-8882: Apache HttpClient 5 async conduit does not handle authentication

parent/pom.xml, services/sts/sts-core/pom.xml, services/sts/sts-core/src/main/java/org/apache/cxf/sts/claims/mapper/JexlClaimsMapper.java
=> CXF-8884: Update commons-jexl3 to 3.3

rt/transports/websocket/pom.xml, rt/ws/addr/pom.xml, rt/ws/eventing/pom.xml, rt/ws/mex/pom.xml, rt/ws/policy/pom.xml, rt/ws/rm/pom.xml, rt/ws/security/pom.xml, rt/wsdl/pom.xml, services/sts/sts-core/pom.xml, services/ws-discovery/ws-discovery-api/pom.xml, services/ws-discovery/ws-discovery-service/pom.xml, services/wsn/wsn-api/pom.xml, services/wsn/wsn-core/pom.xml, services/wsn/wsn-osgi/pom.xml, services/xkms/xkms-client/pom.xml, services/xkms/xkms-common/pom.xml, services/xkms/xkms-x509-handlers/pom.xml, testutils/pom.xml, tools/common/pom.xml, tools/corba/pom.xml, tools/javato/ws/pom.xml, tools/validator/pom.xml, tools/wsdlto/core/pom.xml, tools/wsdlto/frontend/jaxws/pom.xml
OSGi bundle manifest are broken (fixing a few missed ones)
=> CXF-8879: OSGi bundle manifest are broken (fixing a few missed ones)

core/pom.xml, core/src/test/java/org/apache/cxf/attachment/AttachmentUtilTest.java, core/src/test/java/org/apache/cxf/bus/CXFBusImplTest.java, core/src/test/java/org/apache/cxf/bus/managers/EndpointResolverRegistryImplTest.java, core/src/test/java/org/apache/cxf/bus/managers/ServiceContractResolverRegistryImplTest.java, core/src/test/java/org/apache/cxf/bus/spring/BusApplicationListenerTest.java, core/src/test/java/org/apache/cxf/bus/spring/SpringBusFactoryTest.java, core/src/test/java/org/apache/cxf/buslifecycle/CXFBusLifeCycleManagerTest.java, core/src/test/java/org/apache/cxf/common/annotation/AnnotationProcessorTest.java, core/src/test/java/org/apache/cxf/common/injection/ResourceInjectorTest.java, core/src/test/java/org/apache/cxf/common/logging/LogUtilsTest.java, core/src/test/java/org/apache/cxf/common/util/ClassHelperTest.java, core/src/test/java/org/apache/cxf/helpers/ServiceUtilsTest.java, core/src/test/java/org/apache/cxf/interceptor/LoggingInInterceptorTest.java, core/src/test/java/org/apache/cxf/interceptor/LoggingOutInterceptorTest.java, core/src/test/java/org/apache/cxf/interceptor/OutgoingChainInterceptorTest.java, core/src/test/java/org/apache/cxf/interceptor/ServiceInvokerInterceptorTest.java, core/src/test/java/org/apache/cxf/interceptor/security/JAASLoginInterceptorTest.java, core/src/test/java/org/apache/cxf/interceptor/security/OperationInfoAuthorizingInterceptorTest.java, core/src/test/java/org/apache/cxf/interceptor/security/SecureAnnotationsInterceptorTest.java, core/src/test/java/org/apache/cxf/interceptor/security/SimpleAuthorizingInterceptorTest.java, core/src/test/java/org/apache/cxf/io/CachedStreamTestBase.java, core/src/test/java/org/apache/cxf/phase/PhaseInterceptorChainTest.java, core/src/test/java/org/apache/cxf/staxutils/validation/Stax2ValidationUtilsTest.java, core/src/test/java/org/apache/cxf/transport/ChainInitiationObserverTest.java, core/src/test/java/org/apache/cxf/transport/common/gzip/GZIPAcceptEncodingTest.java
Get rid of EasyMock in `cxf-core`
=> CXF-8842: Get rid of EasyMock in cxf-core

rt/frontend/jaxrs/src/main/java/org/apache/cxf/jaxrs/model/doc/JavaDocProvider.java
Support scraping javadocs generated by Java 17 (restore more strict visibility levels)
=> CXF-8886: Support scraping javadocs generated by Java 17 (restore more strict visibility levels)

parent/pom.xml
Some Apache Maven profile leftovers we haven't cleaned up
=> CXF-8889: Compilation of CXF fails due to a jakarta... vs. 'javax...' issue

rt/bindings/soap/pom.xml, rt/bindings/soap/src/test/java/org/apache/cxf/binding/soap/RPCInInterceptorTest.java, rt/bindings/soap/src/test/java/org/apache/cxf/binding/soap/RPCOutInterceptorTest.java, rt/bindings/soap/src/test/java/org/apache/cxf/binding/soap/ServiceModelUtilTest.java, rt/bindings/soap/src/test/java/org/apache/cxf/binding/soap/SoapBindingFactoryTest.java, rt/bindings/soap/src/test/java/org/apache/cxf/binding/soap/TestBase.java, rt/bindings/soap/src/test/java/org/apache/cxf/binding/soap/interceptor/SoapActionInInterceptorTest.java, rt/bindings/soap/src/test/java/org/apache/cxf/binding/soap/interceptor/SoapPreProtocolOutInterceptorTest.java, rt/bindings/soap/src/test/java/org/apache/cxf/binding/soap/jms/interceptor/SoapFaultFactoryTest.java
Get rid of EasyMock in cxf-rt-bindings-soap
=> CXF-8846: Get rid of EasyMock in cxf-rt-bindings-soap

rt/management/pom.xml, rt/management/src/test/java/org/apache/cxf/management/counters/CounterRepositoryTest.java, rt/management/src/test/java/org/apache/cxf/management/interceptor/AbstractMessageResponseTestBase.java, rt/management/src/test/java/org/apache/cxf/management/interceptor/ResponseTimeMessageInInterceptorTest.java, rt/management/src/test/java/org/apache/cxf/management/interceptor/ResponseTimeMessageInvokerInterceptorTest.java, rt/management/src/test/java/org/apache/cxf/management/interceptor/ResponseTimeMessageOutInterceptorTest.java
Get rid of EasyMock in cxf-rt-management
=> CXF-8865: Get rid of EasyMock in cxf-rt-management

rt/frontend/jaxrs/pom.xml, rt/frontend/jaxrs/src/test/java/org/apache/cxf/jaxrs/SelectMethodCandidatesTest.java, rt/frontend/jaxrs/src/test/java/org/apache/cxf/jaxrs/ext/MessageContextImplTest.java, rt/frontend/jaxrs/src/test/java/org/apache/cxf/jaxrs/impl/AsyncResponseImplTest.java, rt/frontend/jaxrs/src/test/java/org/apache/cxf/jaxrs/impl/RequestPreprocessorTest.java, rt/frontend/jaxrs/src/test/java/org/apache/cxf/jaxrs/impl/ResponseImplTest.java, rt/frontend/jaxrs/src/test/java/org/apache/cxf/jaxrs/impl/UriInfoImplTest.java, rt/frontend/jaxrs/src/test/java/org/apache/cxf/jaxrs/lifecycle/PerRequestResourceProviderTest.java, rt/frontend/jaxrs/src/test/java/org/apache/cxf/jaxrs/model/OperationResourceInfoTest.java, rt/frontend/jaxrs/src/test/java/org/apache/cxf/jaxrs/provider/AbstractConfigurableProviderTest.java, rt/frontend/jaxrs/src/test/java/org/apache/cxf/jaxrs/provider/JAXBElementProviderTest.java, rt/frontend/jaxrs/src/test/java/org/apache/cxf/jaxrs/provider/ProviderFactoryTest.java, rt/frontend/jaxrs/src/test/java/org/apache/cxf/jaxrs/provider/XSLTJaxbProviderTest.java, rt/frontend/jaxrs/src/test/java/org/apache/cxf/jaxrs/springmvc/SpringViewResolverProviderTest.java, rt/frontend/jaxrs/src/test/java/org/apache/cxf/jaxrs/utils/FormUtilsTest.java, rt/frontend/jaxrs/src/test/java/org/apache/cxf/jaxrs/utils/HttpUtilsTest.java, rt/frontend/jaxrs/src/test/java/org/apache/cxf/jaxrs/utils/InjectionUtilsTest.java, rt/frontend/jaxrs/src/test/java/org/apache/cxf/jaxrs/utils/JAXRSUtilsTest.java
Get rid of EasyMock in cxf-rt-frontend-jaxrs
=> CXF-8856: Get rid of EasyMock in cxf-rt-frontend-jaxrs

rt/rs/description/pom.xml, rt/rs/description/src/test/java/org/apache/cxf/jaxrs/model/wadl/WadlGeneratorJsonTest.java, rt/rs/description/src/test/java/org/apache/cxf/jaxrs/model/wadl/WadlGeneratorTest.java
Get rid of EasyMock in cxf-rt-rs-service-description
=> CXF-8866: Get rid of EasyMock in cxf-rt-rs-service-description

rt/ws/security/src/main/java/org/apache/cxf/ws/security/wss4j/policyhandlers/AsymmetricBindingHandler.java
java.lang.NullPointerException at AsymmetricBindingHandler.java
=> CXF-8907:  java.lang.NullPointerException at AsymmetricBindingHandler.java

rt/bindings/coloc/pom.xml, rt/bindings/coloc/src/test/java/org/apache/cxf/binding/coloc/ColocMessageObserverTest.java, rt/bindings/coloc/src/test/java/org/apache/cxf/binding/coloc/ColocOutInterceptorTest.java, rt/bindings/coloc/src/test/java/org/apache/cxf/binding/coloc/ColocUtilTest.java
Get rid of EasyMock in cxf-rt-bindings-coloc
=> CXF-8844: Get rid of EasyMock in cxf-rt-bindings-coloc

rt/frontend/js/pom.xml, rt/frontend/js/src/test/java/org/apache/cxf/js/rhino/AbstractDOMProviderTest.java, rt/frontend/js/src/test/java/org/apache/cxf/js/rhino/ProviderFactoryTest.java, rt/frontend/js/src/test/java/org/apache/cxf/js/rhino/ServerAppTest.java
Get rid of EasyMock in cxf-rt-frontend-js
=> CXF-8858: Get rid of EasyMock in cxf-rt-frontend-js

parent/pom.xml, rt/rs/microprofile-client/pom.xml, systests/microprofile/client/async/pom.xml, systests/microprofile/client/nocdi/pom.xml
Update Wiremock to 3.0.0-beta-15
=> Update Wiremock to 3.0.0-beta-15

rt/transports/http/src/main/java/org/apache/cxf/transport/http/HttpClientHTTPConduit.java
The SelectorManager thread of the WebClient would normally shut down after the HttpClient's outer shell, the `HttpClientFacade` has been garbage collected. Unfortunately the `ProxySelector` instance created in `HttpClientHTTPConduit` is a non-static (anonymous) subclass, so it retains a hard reference to the enclosing `HttpClientHTTPConduit` instance and therefore also its `client` field. This gives the SelectorManager thread a hard reference to the `HttpClientFacade`, so the facade can never be garbage collected and the thread never shuts down. Making the class static solves the problem.
=> [CXF-8885] Eliminate hidden reference to `HttpClient` in `ProxySelector`

rt/rs/security/jose-parent/jose/src/main/java/org/apache/cxf/rs/security/jose/jws/JwsUtils.java
My previous change was not complete, now I'm running into the same issue again that I had before.
=> [CXF-8837] Avoid instanceof checking completely

rt/rs/security/oauth-parent/oauth2/pom.xml, rt/rs/security/oauth-parent/oauth2/src/test/java/org/apache/cxf/rs/security/oauth2/client/OAuthClientUtilsTest.java, rt/rs/security/oauth-parent/oauth2/src/test/java/org/apache/cxf/rs/security/oauth2/grants/jwt/AbstractJwtHandlerTest.java, rt/rs/security/oauth-parent/oauth2/src/test/java/org/apache/cxf/rs/security/oauth2/tokens/hawk/HawkAccessTokenValidatorTest.java, rt/rs/security/oauth-parent/oauth2/src/test/java/org/apache/cxf/rs/security/oauth2/tokens/hawk/NonceVerifierImplTest.java
Get rid of EasyMock in cxf-rt-rs-security-oauth
=> CXF-8872: Get rid of EasyMock in cxf-rt-rs-security-oauth2

integration/jca/pom.xml, integration/jca/src/test/java/org/apache/cxf/jca/core/resourceadapter/ManagedConnectionImplTest.java, integration/jca/src/test/java/org/apache/cxf/jca/cxf/AssociatedManagedConnectionFactoryImplTest.java, integration/jca/src/test/java/org/apache/cxf/jca/cxf/ConnectionFactoryImplTest.java, integration/jca/src/test/java/org/apache/cxf/jca/cxf/JCABusFactoryTest.java, integration/jca/src/test/java/org/apache/cxf/jca/cxf/ManagedConnectionFactoryImplTest.java, integration/jca/src/test/java/org/apache/cxf/jca/cxf/ManagedConnectionImplTest.java, integration/jca/src/test/java/org/apache/cxf/jca/cxf/ManagedConnectionTestBase.java, integration/jca/src/test/java/org/apache/cxf/jca/cxf/ResourceAdapterImplTest.java, integration/jca/src/test/java/org/apache/cxf/jca/cxf/handlers/HandlerTestBase.java, integration/jca/src/test/java/org/apache/cxf/jca/outbound/ManagedConnectionImplTest.java
Get rid of EasyMock in cxf-integration-jca
=> CXF-8843: Get rid of EasyMock in cxf-integration-jca

rt/transports/jms/pom.xml, rt/transports/jms/src/test/java/org/apache/cxf/transport/jms/continuations/JMSContinuationProviderTest.java, rt/transports/jms/src/test/java/org/apache/cxf/transport/jms/continuations/JMSContinuationTest.java
Get rid of EasyMock in cxf-rt-transports-jms
=> CXF-8864: Get rid of EasyMock in cxf-rt-transports-jms

rt/rs/microprofile-client/pom.xml, rt/rs/microprofile-client/src/test/java/org/apache/cxf/microprofile/client/cdi/RestClientCdiTest.java
Get rid of EasyMock in cxf-rt-rs-mp-client
=> CXF-8871: Get rid of EasyMock in cxf-rt-rs-mp-client

rt/rs/extensions/providers/pom.xml, rt/rs/extensions/providers/src/test/java/org/apache/cxf/jaxrs/provider/dom4j/DOM4JProviderTest.java
Get rid of EasyMock in cxf-rt-rs-extension-providers
=> CXF-8868: Get rid of EasyMock in cxf-rt-rs-extension-providers

parent/pom.xml
=> CXF-8549: Get rid of EasyMock

distribution/src/main/release/samples/pom.xml, parent/pom.xml, rt/transports/websocket/src/main/java/org/apache/cxf/transport/websocket/jetty10/Jetty10WebSocketDestination.java
=> Update Jetty to 10.0.16

bom/pom.xml
Add `cxf-integration-tracing-micrometer` to `cxf-bom`
=> [CXF-8937] Add cxf-integration-tracing-micrometer to cxf-bom

rt/transports/http-jetty/src/main/java/org/apache/cxf/transport/http_jetty/JettyContextHandler.java, rt/transports/http-jetty/src/main/java/org/apache/cxf/transport/http_jetty/JettyHTTPHandler.java, rt/transports/http-jetty/src/main/java/org/apache/cxf/transport/http_jetty/JettyHTTPServerEngine.java
Fix Unimplemented getRequestCharacterEncoding() - use org.eclipse.jetty.servlet.ServletContextHandler
=> CXF-8894: Unimplemented getRequestCharacterEncoding()

core/src/main/java/org/apache/cxf/endpoint/ClientImpl.java, core/src/main/java/org/apache/cxf/interceptor/OneWayInterceptor.java, integration/tracing/tracing-brave/src/main/java/org/apache/cxf/tracing/brave/AbstractBraveClientInterceptor.java, integration/tracing/tracing-micrometer/src/main/java/org/apache/cxf/tracing/micrometer/AbstractObservationClientInterceptor.java, integration/tracing/tracing-opentelemetry/src/main/java/org/apache/cxf/tracing/opentelemetry/AbstractOpenTelemetryClientInterceptor.java, integration/tracing/tracing-opentracing/src/main/java/org/apache/cxf/tracing/opentracing/AbstractOpenTracingClientInterceptor.java
The client out interceptor chain is not called in case of oneway operation
=> [JAX-WS] The client out interceptor chain is not called in case of oneway operation

distribution/src/main/release/samples/jax_rs/websocket/pom.xml, parent/pom.xml, systests/rs-http-sci/pom.xml, systests/rs-sse/rs-sse-jetty/pom.xml
Streamline Jetty version management (follow up on https://github.com/apache/cxf/pull/1500)
=> Streamline Jetty version management

distribution/src/main/release/samples/pom.xml, integration/tracing/tracing-micrometer/src/main/java/org/apache/cxf/tracing/micrometer/ObservationTracerContext.java, parent/pom.xml
Move to Spring Boot 3.2.0 baseline
=> Move to Spring Boot 3.2.0 baseline

core/src/main/java/org/apache/cxf/configuration/jsse/TLSClientParameters.java, core/src/main/java/org/apache/cxf/configuration/jsse/TLSParameterBase.java, core/src/main/java/org/apache/cxf/configuration/jsse/TLSServerParameters.java, core/src/test/java/org/apache/cxf/configuration/jsse/TLSClientParametersTest.java, rt/transports/http-undertow/src/main/java/org/apache/cxf/transport/http_undertow/UndertowHTTPServerEngine.java, rt/transports/http/src/main/java/org/apache/cxf/transport/http/HttpClientHTTPConduit.java
Better support of the HTTPS protocol versions used by client/server conduits
=> CXF-8953: Better support of the HTTPS protocol versions used by client/server conduits

distribution/javadoc/pom.xml, parent/pom.xml, rt/rs/security/jose-parent/jose/pom.xml, rt/ws/security/pom.xml, services/sts/systests/advanced/pom.xml, systests/jaxrs/pom.xml, systests/kerberos/pom.xml, systests/ldap/pom.xml, systests/rs-security/pom.xml, systests/transports/pom.xml, systests/ws-security/pom.xml
Update Bouncycastle from unsupported xxx-jdk15on to xxx-jdk18on (addressing CVEs)
=> CXF-8964: Update Bouncycastle from unsupported xxx-jdk15on to xxx-jdk18on (addressing CVEs)

.github/workflows/pull-request-build.yml
Add Windows and MacOS builds to GA workflow
=> Add Windows build to GA workflow

rt/frontend/jaxrs/src/main/java/org/apache/cxf/jaxrs/impl/HttpHeadersImpl.java, rt/frontend/jaxrs/src/test/java/org/apache/cxf/jaxrs/impl/HttpHeadersImplTest.java, systests/jaxrs/src/test/java/org/apache/cxf/systest/jaxrs/BookStore.java, systests/jaxrs/src/test/java/org/apache/cxf/systest/jaxrs/JAXRS20ClientServerBookTest.java
Content-Type header created with collection containing 'null' value
=> CXF-8812: Content-Type header created with collection containing 'null' value

rt/transports/http-hc/src/main/java/org/apache/cxf/transport/http/asyncclient/AsyncHTTPConduit.java, rt/transports/http-hc5/src/main/java/org/apache/cxf/transport/http/asyncclient/hc5/AsyncHTTPConduit.java, systests/transport-hc5/src/test/java/org/apache/cxf/systest/hc5/http/timeout/ClientTimeoutTest.java, systests/transport-hc5/src/test/java/org/apache/cxf/systest/hc5/http/timeout/DelayedService.java, systests/transport-hc5/src/test/java/org/apache/cxf/systest/hc5/http/timeout/DelayedServiceImpl.java, systests/transports/src/test/java/org/apache/cxf/systest/http/timeout/ClientTimeoutTest.java, systests/transports/src/test/java/org/apache/cxf/systest/http/timeout/DelayedService.java, systests/transports/src/test/java/org/apache/cxf/systest/http/timeout/DelayedServiceImpl.java
Custom timeout with Message.RECEIVE_TIMEOUT not working with hc5 / hc
=> CXF-8955: Custom timeout with Message.RECEIVE_TIMEOUT not working with hc5 / hc

rt/frontend/jaxrs/src/main/java/org/apache/cxf/jaxrs/springmvc/SpringWebUtils.java, rt/frontend/jaxrs/src/main/java/org/apache/cxf/jaxrs/utils/HttpUtils.java, systests/spring-boot/src/test/java/org/apache/cxf/systest/jaxrs/spring/boot/SpringJaxrsWebObservabiityTest.java
URI is always unknown in server request metrics (Spring Web + Spring Actuator instrumentation)
=> CXF-8963: URI is always unknown in server request metrics

distribution/src/main/release/samples/pom.xml, parent/pom.xml
Update Apache Tomcat to 10.0.20
=> Update Apache Tomcat to 10.1.20

systests/microprofile/pom.xml
Cleanup Arquillian + Weld dependencies to get rid of *-alpha artifacts
=> Cleanup Arquillian + Weld dependencies to get rid of *-alpha artifacts

core/src/main/java/org/apache/cxf/staxutils/StaxSource.java, core/src/test/java/org/apache/cxf/staxutils/StaxUtilsTest.java
NPE when using com.ctc.wstx.returnNullForDefaultNamespace=true
=> CXF-9037: NPE when using com.ctc.wstx.returnNullForDefaultNamespace=true

distribution/src/main/release/samples/performance/jaxrs/README.txt, distribution/src/main/release/samples/performance/jaxrs/pom.xml, distribution/src/main/release/samples/performance/jaxrs/src/main/java/org/apache/cxf/performance/https/client/Client.java, distribution/src/main/release/samples/performance/jaxrs/src/main/java/org/apache/cxf/performance/https/server/Server.java
Update to the Client and Server scripts to make using 2 or most hosts easier.
=> [CXF-9045 Update client and server to accept host and protocol]

core/src/main/java/org/apache/cxf/common/jaxb/JAXBUtils.java
CXF will only accept org.glassfish.jaxb.runtime.v2.ContextFactory. Switching the discovery mechanism to ServiceLoader instead.
=> CXF-9041: CXF will only accept org.glassfish.jaxb.runtime.v2.ContextFactory

systests/transport-hc5/src/test/java/org/apache/cxf/systest/hc5/http/auth/DigestAuthSupplierSpringTest.java, systests/transport-hc5/src/test/java/org/apache/cxf/systest/hc5/jaxrs/FileStore.java, systests/transport-hc5/src/test/java/org/apache/cxf/systest/hc5/jaxrs/FileStoreServer.java, systests/transport-hc5/src/test/java/org/apache/cxf/systest/hc5/jaxrs/JAXRSAsyncClientChunkingTest.java, systests/transport-hc5/src/test/java/org/apache/cxf/systest/hc5/jaxws/JAXWSAsyncClientTest.java, systests/transport-hc5/src/test/resources/logging.properties
AsyncHTTPConduit (hc5) should support chunked request / response
=> CXF-8629: AsyncHTTPConduit (hc5) should support chunked request / response

core/src/main/java/org/apache/cxf/io/CachedConstants.java, core/src/main/java/org/apache/cxf/io/DelayedCachedOutputStreamCleaner.java, core/src/test/java/org/apache/cxf/io/DelayedCachedOutputStreamCleanerTest.java
Add forced cleanup on Bus shutdown
=> CXF-7396: CachedOutputStream doesn't delete temp files. Add forced cleanup on Bus shutdown

rt/rs/client/src/main/java/org/apache/cxf/jaxrs/client/ClientProviderFactory.java, systests/jaxrs/src/test/java/org/apache/cxf/systest/jaxrs/JAXRS31ClientServerBookTest.java
Add ContextResolver support on the JAX-RS client side (closing the Jakarta RESTful spec gaps).
=> Add ContextResolver support on the JAX-RS client side

core/src/main/java/org/apache/cxf/interceptor/ClientFaultConverter.java, systests/jaxws/src/test/java/org/apache/cxf/systest/jaxws/ClientServerExceptionServer.java, systests/jaxws/src/test/java/org/apache/cxf/systest/jaxws/ClientServerExceptionTest.java, systests/jaxws/src/test/java/org/apache/cxf/systest/jaxws/ExceptionService.java
Exception message is not unmarshalled with JDK17+
=> CXF-9076: Exception message is not unmarshalled with JDK17+

rt/transports/http-hc/src/main/java/org/apache/cxf/transport/http/asyncclient/AsyncHTTPConduit.java, rt/transports/http-hc/src/main/java/org/apache/cxf/transport/http/asyncclient/URLConnectionAsyncHTTPConduit.java, rt/transports/http-hc5/src/main/java/org/apache/cxf/transport/http/asyncclient/hc5/AsyncHTTPConduit.java, rt/transports/http-hc5/src/main/java/org/apache/cxf/transport/http/asyncclient/hc5/URLConnectionAsyncHTTPConduit.java, systests/jaxrs/src/test/java/org/apache/cxf/systest/jaxrs/BookStore.java, systests/jaxrs/src/test/java/org/apache/cxf/systest/jaxrs/JAXRSAsyncClientTest.java, systests/transports/pom.xml, systests/transports/src/test/java/org/apache/cxf/systest/hc/jaxrs/Book.java, systests/transports/src/test/java/org/apache/cxf/systest/hc/jaxrs/BookServerAsyncClient.java, systests/transports/src/test/java/org/apache/cxf/systest/hc/jaxrs/BookStore.java, systests/transports/src/test/java/org/apache/cxf/systest/hc/jaxrs/Chapter.java, systests/transports/src/test/java/org/apache/cxf/systest/hc/jaxrs/JAXRSAsyncClientTest.java, systests/transports/src/test/java/org/apache/cxf/systest/hc/jaxrs/RETRIEVE.java
AsyncHTTPConduit.java causing NullPointerException when closing
=> CXF-9078: AsyncHTTPConduit.java causing NullPointerException when closing

distribution/src/main/release/samples/pom.xml, parent/pom.xml, rt/transports/http-hc5/src/main/java/org/apache/cxf/transport/http/asyncclient/hc5/AsyncHTTPConduit.java, rt/transports/http-hc5/src/main/java/org/apache/cxf/transport/http/asyncclient/hc5/AsyncHTTPConduitFactory.java, rt/transports/http-hc5/src/main/java/org/apache/cxf/transport/http/asyncclient/hc5/URLConnectionAsyncHTTPConduit.java
Update Apache HttpClient5 to 5.4.1 and Apache HttpCore5 to 5.3.1
=> Update Apache HttpClient5 to 5.4.1 and Apache HttpCore5 to 5.3.1

parent/pom.xml, rt/rs/extensions/search/src/test/java/org/apache/cxf/jaxrs/ext/search/hibernate/SearchTypeContributor.java, rt/rs/extensions/search/src/test/resources/META-INF/services/org.hibernate.boot.model.TypeContributor
Update Hibernate to 6.6.2.Final
=> Update Hibernate to 6.6.2.Final

rt/transports/http/src/main/java/org/apache/cxf/transport/http/Headers.java, rt/transports/http/src/test/java/org/apache/cxf/transport/http/HeadersTest.java
* Fix any sensitive information is printed to the logs
https://issues.apache.org/jira/browse/CXF-9082
=> CXF-9082: Allow to modify sensitive header list

rt/transports/http/src/main/java/org/apache/cxf/transport/http/HttpClientHTTPConduit.java, systests/transports/src/test/java/org/apache/cxf/systest/jaxrs/FileStore.java, systests/transports/src/test/java/org/apache/cxf/systest/jaxrs/FileStoreServer.java, systests/transports/src/test/java/org/apache/cxf/systest/jaxrs/JAXRSClientChunkingTest.java
HttpClientHTTPConduit can't disable the http chunk mode. Drafting for now and working on test cases.
=> CXF-8931: HttpClientHTTPConduit can't disable the http chunk mode

core/src/main/java/org/apache/cxf/interceptor/AttachmentOutInterceptor.java, core/src/main/java/org/apache/cxf/message/Message.java, rt/bindings/soap/src/main/java/org/apache/cxf/binding/soap/interceptor/Soap11FaultOutInterceptor.java, rt/bindings/soap/src/main/java/org/apache/cxf/binding/soap/interceptor/Soap12FaultOutInterceptor.java, systests/jaxws/pom.xml, systests/jaxws/src/test/java/org/apache/cxf/systest/jaxws/AttachmentChunkingTest.java, systests/jaxws/src/test/resources/attachments/cxf9057.wsdl, systests/transports/src/test/java/org/apache/cxf/systest/http/jaxws/JAXWSAsyncClientTest.java
CXF-9057: Chunked Stream is closed regularly when Exception is thrown
=> CXF-9057: Chunked Stream is closed regularly when Exception is thrown

rt/frontend/jaxrs/src/main/java/org/apache/cxf/jaxrs/bootstrap/ConfigurationBuilderImpl.java, rt/frontend/jaxrs/src/main/java/org/apache/cxf/jaxrs/impl/RuntimeDelegateImpl.java, rt/frontend/jaxrs/src/main/java/org/apache/cxf/jaxrs/impl/UriBuilderImpl.java, systests/jaxrs/src/test/java/org/apache/cxf/systest/jaxrs/bootstrap/SeBootstrapTest.java, tck/Jenkinsfile, tck/cxf-tck/pom.xml
=> CXF-9039: Run Jakarta RESTful Web Services 3.1 TCK. Fix SeBootstrap test cases

systests/jaxrs/src/test/java/org/apache/cxf/systest/jaxrs/JAXRSMultipartTest.java, systests/jaxrs/src/test/java/org/apache/cxf/systest/jaxrs/MultipartStore.java, systests/jaxrs/src/test/java/org/apache/cxf/systest/jaxrs/validation/JAXRSMultipartValidationTest.java, systests/jaxrs/src/test/java/org/apache/cxf/systest/jaxrs/validation/MultipartBookStoreWithValidation.java
=> Add more @Multipart tests

parent/pom.xml, rt/transports/jms/pom.xml
Update ActiveMQ Artemis to 2.39.0
=> Update ActiveMQ Artemis to 2.39.0

core/src/main/java/org/apache/cxf/common/logging/LogUtils.java
Hard coded org.slf4j.impl.StaticLoggerBinder of slf4j 1.x in LogUtils
=> CXF-9094: Hard coded org.slf4j.impl.StaticLoggerBinder of slf4j 1.x in LogUtils

rt/transports/http/src/main/java/org/apache/cxf/transport/https/SSLUtils.java, rt/transports/http/src/test/java/org/apache/cxf/transport/https/SSLUtilsTest.java
StackOverflow Exception during execution of WebClient POST Request on SSLUtils class
=> CXF-9065: StackOverflow Exception during execution of WebClient POST Request on SSLUtils class

parent/pom.xml, rt/rs/extensions/providers/src/main/java/org/apache/cxf/jaxrs/provider/json/JSONProvider.java, systests/jaxrs/src/test/java/org/apache/cxf/systest/jaxrs/JAXRS20ClientServerBookTest.java, systests/rs-security/src/test/java/org/apache/cxf/systest/jaxrs/security/jose/jwejws/JAXRSJweJwsTest.java, systests/rs-security/src/test/java/org/apache/cxf/systest/jaxrs/security/jose/jwejws/JAXRSJwsJsonTest.java, systests/rs-security/src/test/java/org/apache/cxf/systest/jaxrs/security/jose/jwejws/JweJwsAlgorithmTest.java, systests/rs-security/src/test/java/org/apache/cxf/systest/jaxrs/security/jose/jwejws/JweJwsReferenceTest.java, systests/rs-security/src/test/java/org/apache/cxf/systest/jaxrs/security/jose/jwejws/JwsHTTPHeaderTest.java, systests/rs-security/src/test/java/org/apache/cxf/systest/jaxrs/security/jose/jwt/JWTAlgorithmTest.java, systests/rs-security/src/test/java/org/apache/cxf/systest/jaxrs/security/jose/jwt/JWTAuthnAuthzTest.java, systests/rs-security/src/test/java/org/apache/cxf/systest/jaxrs/security/jose/jwt/JWTPropertiesTest.java, systests/rs-security/src/test/resources/org/apache/cxf/systest/jaxrs/security/jose/jwejws/server.xml, systests/rs-security/src/test/resources/org/apache/cxf/systest/jaxrs/security/jose/jwejws/serverJwsJson.xml
=> Update Jackson to 2.18.2

rt/rs/extensions/providers/src/main/java/org/apache/cxf/jaxrs/provider/jsrjsonb/JsrJsonbProvider.java, tck/Jenkinsfile
Run Jakarta RESTful Web Services 3.1 TCK. Fixing test failures
=> CXF-9039: Run Jakarta RESTful Web Services 3.1 TCK. Fixing test failures

osgi/itests/pom.xml, osgi/itests/src/test/java/org/apache/cxf/osgi/itests/soap/JmsServiceTest.java, osgi/karaf/features/pom.xml, osgi/karaf/features/src/main/resources/features.xml, parent/pom.xml
=> Update to Apache Karaf 4.4.7

core/src/main/java/org/apache/cxf/phase/AbortedInvocationException.java, core/src/main/java/org/apache/cxf/phase/PhaseInterceptorChain.java, rt/bindings/soap/src/main/java/org/apache/cxf/binding/soap/interceptor/Soap11FaultOutInterceptor.java, rt/bindings/soap/src/main/java/org/apache/cxf/binding/soap/interceptor/Soap12FaultOutInterceptor.java, rt/transports/http/src/main/java/org/apache/cxf/transport/http/AbstractHTTPDestination.java, systests/jaxws/src/test/java/org/apache/cxf/systest/jaxws/AbstractAttachmentChunkingTest.java, systests/jaxws/src/test/java/org/apache/cxf/systest/jaxws/AttachmentMtomChunkingTest.java, systests/jaxws/src/test/resources/attachments/cxf9057.wsdl
Chunked Stream is closed regularly when Exception is thrown (MTOM)
=> CXF-9057: Chunked Stream is closed regularly when Exception is thrown (MTOM)

rt/transports/http-netty/netty-client/src/main/java/org/apache/cxf/transport/http/netty/client/NettyHttpConduit.java, systests/transport-netty/src/test/java/org/apache/cxf/systest/http2/netty/jaxws/JAXWSAsyncClientTest.java
LEAK: ByteBuf.release() was not called before it's garbage-collected
=> CXF-9121: LEAK: ByteBuf.release() was not called before it's garbage-collected

rt/databinding/jaxb/src/main/java/org/apache/cxf/jaxb/attachment/JAXBAttachmentMarshaller.java
=> swaref attachement cid association failed

parent/pom.xml
Update HttpClient5 to 5.4.3 and HttpCore5 to 5.3.4
=> Update HttpClient5 to 5.4.3 and HttpCore5 to 5.3.4

systests/transports/src/test/java/org/apache/cxf/systest/http/jaxws/JAXWSClientTest.java
Add a test case for SOAP based service to simulate a high load
=> Add a test case for SOAP based service to simulate a high load

rt/frontend/jaxrs/src/main/java/org/apache/cxf/jaxrs/provider/JAXBElementProvider.java, rt/rs/client/src/main/java/org/apache/cxf/jaxrs/client/spec/ClientResponseFilterInterceptor.java, systests/jaxrs/src/test/java/org/apache/cxf/systest/jaxrs/JAXRS31ClientServerBookTest.java
Fix ee.jakarta.tck.ws.rs.spec.provider.standardnotnull.JAXRSClientIT.serverJaxbProviderTest
=> CXF-9039: Run Jakarta RESTful Web Services 3.1 TCK. Fix ee.jakarta.tck.ws.rs.spec.provider.standardnotnull.JAXRSClientIT.serverJaxbProviderTest

rt/transports/http/src/main/java/org/apache/cxf/transport/http/HttpClientHTTPConduit.java, systests/transports/src/test/java/org/apache/cxf/systest/http/jaxws/JAXWSClientTest.java, systests/transports/src/test/java/org/apache/cxf/systest/https/conduit/HTTPSConduitTest.java, systests/transports/src/test/java/org/apache/cxf/systest/https/conduit/Server.java, systests/transports/src/test/resources/org/apache/cxf/systest/https/conduit/Bethal.cxf
HttpClientHTTPConduit releases the client while there are connection(s) still using it
=> CXF-9132: HttpClientHTTPConduit releases the client while there are connection(s) still using it

rt/frontend/jaxrs/src/main/java/org/apache/cxf/jaxrs/impl/EntityPartBuilderImpl.java, rt/frontend/jaxrs/src/test/java/org/apache/cxf/jaxrs/impl/EntityPartImplTest.java
EntityPart.Builder does not seem to work in a Java SE environment
=> CXF-9113: EntityPart.Builder does not seem to work in a Java SE environment

parent/pom.xml
=> Update Jackson to 2.19.0

.github/workflows/pull-request-build.yml, systests/transports/src/test/java/org/apache/cxf/systest/http/HTTPConduitIoExceptionsTest.java
=> Fix PMD violations

rt/features/logging/src/main/java/org/apache/cxf/ext/logging/AbstractLoggingInterceptor.java, rt/features/logging/src/main/java/org/apache/cxf/ext/logging/event/DefaultLogEventMapper.java, rt/features/logging/src/test/java/org/apache/cxf/ext/logging/LoggingInInterceptorTest.java
Inconcise handling of logging features logMulitpart and logBinary
=> CXF-9145: Inconcise handling of logging features logMulitpart and logBinary

core/src/main/java/org/apache/cxf/common/logging/JDKBugHacks.java
https://issues.apache.org/jira/browse/CXF-9165
=> [CXF-9165] Removing unnecessary JDK8 hacks
