apache/cxf

rt/rs/security/oauth-parent/oauth2/src/main/java/org/apache/cxf/rs/security/oauth2/grants/owner/ResourceOwnerGrantHandler.java
rt/rs/security/oauth-parent/oauth2/src/main/java/org/apache/cxf/rs/security/oauth2/grants/owner/ResourceOwnerLoginHandler.java

ResourceOwnerGrantHandler calls a customisable ResourceOwnerLoginHandler instance, however the `createSubject(String, String)` method declares no exceptions, and a null return value is not handled. This can possibly result in the issuing of an access token if the DataProvider doesn't check for the null subject.
ResourceOwnerGrantHandler.createAccessToken(...) appears to expect that the ResourceOwnerLoginHandler will throw an `Exception` (literally any Exception), however the method signature of the ResourceOwnerLoginHandler interface doesn't allow that.
Also, ResourceOwnerGrantHandler has a setter for loginHandler but not a getter. Minor, but perhaps we should add one for completeness?

[CXF-6561] [CXF-6562] ResourceOwnerGrantHandler improvements

---

rt/transports/http-jetty/src/main/java/org/apache/cxf/transport/http_jetty/JettyHTTPServerEngine.java

Jetty 9.3 contains a tiny (but fatal) change in SslConnectionFactory:
public SslConnectionFactory(@Name("sslContextFactory") SslContextFactory factory, @Name("next") String nextProtocol)
{
-        super("SSL-"+nextProtocol);
+        super("SSL");
See:
http://git.eclipse.org/c/jetty/org.eclipse.jetty.project.git/tree/jetty-server/src/main/java/org/eclipse/jetty/server/SslConnectionFactory.java
http://git.eclipse.org/c/jetty/org.eclipse.jetty.project.git/commit/jetty-server/src/main/java/org/eclipse/jetty/server/SslConnectionFactory.java?id=287e86b7aa787c9836fccbe2816dd08b4b6c599e
The protocol is now named "SSL" (was "SSL-HTTP" before).
If you still use "SSL-HTTP" as default protocol name, the "doStart" of the jetty connector will fail in 9.3+:
(from …

Compatibility to Jetty 9.3+

---

core/src/main/java/org/apache/cxf/endpoint/ClientImpl.java
core/src/main/java/org/apache/cxf/interceptor/ClientOutFaultObserver.java
core/src/main/java/org/apache/cxf/message/AbstractWrappedMessage.java
core/src/main/java/org/apache/cxf/message/ExchangeImpl.java
core/src/main/java/org/apache/cxf/message/StringMap.java
core/src/main/java/org/apache/cxf/message/StringMapImpl.java
rt/transports/http-hc/src/test/java/org/apache/cxf/transport/http/asyncclient/AsyncHTTPConduitTest.java
rt/transports/http/src/main/java/org/apache/cxf/transport/http/HTTPConduit.java

https://issues.apache.org/jira/browse/CXF-7109
https://issues.jboss.org/browse/ENTESB-6136
I think the best way to make a client callback invoked once and only once is to remove from the exchange immediately after its `handle***()` method is invoked once. It should prevent a client callback from being called more than once not only for the [CXF-7109](https://issues.apache.org/jira/browse/CXF-7109) case but also for any other potential cases where the callback may be invoked more than once accidentally.
I added `remove(Class<T>)` to `Exchange` (`StringMap`) for convenience and symmetry. It is necessary to remove the callback right before calling its `handle***()`, as otherwise some other thread may grab it concurrently before the current thread invokes `handle***()`.
I also added a test …

[CXF-7109] ClientCallback may be invoked twice when Async HTTP Transport is used

---

rt/transports/http-hc/src/main/java/org/apache/cxf/transport/http/asyncclient/AsyncHTTPConduit.java

https://issues.apache.org/jira/browse/CXF-7112
https://issues.apache.org/jira/browse/CXF-7109
If a client callback is not removed from exchange, there still remains a possibility for some other thread somewhere else to invoke the same callback again, according to [CXF-7109](https://issues.apache.org/jira/browse/CXF-7109).

[CXF-7112,CXF-7109] Make sure to remove ClientCallback from exchange when invoking handleException()

---

rt/rs/client/src/main/java/org/apache/cxf/jaxrs/client/AbstractClient.java

The logic goes as follows:
1) Base- & request-URI are the same, then only add base-URI.
2) If request-URI starts with base-URI, only add the parts from request-URI that are not already included in base-URI
3) Otherwise add both base-URI and request-URI

[CXF-7210] Fix StringIndexOutOfBoundsException

---

integration/cdi/src/main/java/org/apache/cxf/cdi/CdiBusBean.java
integration/cdi/src/main/java/org/apache/cxf/cdi/CdiClassUnwrapper.java
systests/cdi/base/src/main/java/org/apache/cxf/systests/cdi/base/AbstractCdiSingleAppTest.java
systests/cdi/base/src/main/java/org/apache/cxf/systests/cdi/base/BookStoreByIds.java
systests/cdi/cdi-owb/cdi-multiple-apps-owb/src/test/java/org/apache/cxf/systest/jaxrs/BookStoreCustomApplication.java

This is to avoid issues with proxies and class metadata.

[CXF-7493] Add a default ClassUnwrapper for CDI integration.

---

rt/frontend/jaxrs/src/main/java/org/apache/cxf/jaxrs/provider/ProviderFactory.java
rt/frontend/jaxrs/src/main/java/org/apache/cxf/jaxrs/provider/ServerProviderFactory.java
rt/frontend/jaxrs/src/test/java/org/apache/cxf/jaxrs/provider/ProviderFactoryTest.java

Like PR #321, we need to handle the `@Priority` annotation on exception mappers.

Handle @Priority on ExceptionMappers

---

integration/cdi/src/main/java/org/apache/cxf/cdi/CdiServerConfigurableFactory.java
integration/cdi/src/main/java/org/apache/cxf/cdi/JAXRSCdiResourceExtension.java
integration/cdi/src/main/java/org/apache/cxf/cdi/event/DisposableCreationalContext.java
rt/frontend/jaxrs/src/main/java/org/apache/cxf/jaxrs/impl/ConfigurableImpl.java
rt/frontend/jaxrs/src/main/java/org/apache/cxf/jaxrs/provider/ServerConfigurableFactory.java
rt/frontend/jaxrs/src/main/java/org/apache/cxf/jaxrs/provider/ServerProviderFactory.java
systests/cdi/base/src/main/java/org/apache/cxf/systests/cdi/base/BookStoreAuthenticator.java
systests/cdi/base/src/main/java/org/apache/cxf/systests/cdi/base/BookStoreRequestFilter.java
systests/cdi/cdi-weld/cdi-producers-weld/src/test/java/org/apache/cxf/systest/jaxrs/cdi/SampleFeature.java

Adding the new extension-based customization (`ServerConfigurableFactory`) in order to control the way how providers are created and registered using `FeatureContext::register` methods family. It allows to use proper mechanisms in case of managed runtimes (like CDIs f.e.).
@sberyozkin @johnament Submitting through PR to have some feedback guys you may have. The change is not really complex but touches a bit some internals. 
Thanks.

CXF-7501: Cannot inject field in ContainerRequestFilter (and generally, into any providers registered using FeatureContext)

---

rt/frontend/jaxrs/src/main/java/org/apache/cxf/jaxrs/impl/UriInfoImpl.java
rt/frontend/jaxrs/src/test/java/org/apache/cxf/jaxrs/impl/UriInfoImplTest.java
systests/jaxrs/src/test/java/org/apache/cxf/systest/jaxrs/JAXRSClientServerBookTest.java
systests/jaxrs/src/test/java/org/apache/cxf/systest/jaxrs/JAXRSUriInfoMatchTest.java

The UriInfo.getMatchedURIs method currently returns "duplicate" URI
entries when called from a method that is not annotated with an
@Path annotation. The "duplicate" URI is basically the same URI but
with a trailing slash. This was first discovered when using sub
resource locators, but could also occur in simpler scenarios (like
a resource method annotated with @GET but not @Path). 
When comparing against the javadoc and the RI, it looks like the
URIs we were returning started with a slash, where the RI and
javadoc examples do not. This commit removes the starting slash as
well.

[CXF-7527] getMatchedURIs to avoid duplicate URIs

---

rt/frontend/jaxrs/src/main/java/org/apache/cxf/jaxrs/impl/RequestImpl.java
rt/frontend/jaxrs/src/test/java/org/apache/cxf/jaxrs/impl/RequestImplTest.java

The Request.selectVariant method should return one of the passed-in Variants that is closest to the variant (combination of Accept, Accept-Language and Accept-Encoding headers with quality factors included).
This bug was first reported in CXF 3.1.11, so I'll plan to fix it in 3.1.x-fixes first - and after proper review, I'll make the same change in 3.2.X (master).
Please see the [JIRA](https://issues.apache.org/jira/browse/CXF-7553) for more details of the issue in question - I'm looking for confirmation that this is the appropriate spec-defined behavior (the spec and JAX-RS javadoc is a little ambiguous here) and that this is the best way to fix it.
Thanks, Andy

[CXF-7553] Consider the req headers' quality factors in selectVariant

---

integration/cdi/src/main/java/org/apache/cxf/cdi/CdiClassUnwrapper.java
rt/frontend/jaxrs/src/main/java/org/apache/cxf/jaxrs/model/FilterProviderInfo.java
rt/frontend/jaxrs/src/main/java/org/apache/cxf/jaxrs/model/ProviderInfo.java
rt/frontend/jaxrs/src/main/java/org/apache/cxf/jaxrs/provider/ServerProviderFactory.java
rt/rs/client/src/main/java/org/apache/cxf/jaxrs/client/spec/ClientImpl.java
systests/cdi/base/src/main/java/org/apache/cxf/systests/cdi/base/BookStorePreMatchingRequestFilter.java
systests/cdi/cdi-owb/cdi-producers-owb/pom.xml
systests/cdi/cdi-owb/cdi-producers-owb/src/test/java/org/apache/cxf/systest/jaxrs/cdi/SampleNestedFeature.java
systests/cdi/cdi-owb/cdi-producers-owb/src/test/java/org/apache/cxf/systest/jaxrs/cdi/unwrapper/ClassUnwrapperTest.java
systests/cdi/cdi-weld/cdi-producers-weld/pom.xml
systests/cdi/cdi-weld/cdi-producers-weld/src/test/java/org/apache/cxf/systest/jaxrs/cdi/SampleFeature.java
systests/cdi/cdi-weld/cdi-producers-weld/src/test/java/org/apache/cxf/systest/jaxrs/cdi/SampleNestedFeature.java
systests/cdi/cdi-weld/cdi-producers-weld/src/test/java/org/apache/cxf/systest/jaxrs/cdi/unwrapper/ClassUnwrapperTest.java

The issue pop up as part of #330 discussion. In case when provider / feature / resource is a proxied CDI bean, the contextual class members (annotated with @context) are not injected.
More broadly, in some circumstances (like using @ApplicationScoped annotation for example) the CDI runtime will create a proxy class for a particular bean. As the result, the CXF side is going to bind the particular provider metadata to this proxy instance. It looks logical and unambiguous.
However, the interesting things are happening when CXF will try to inject contextual proxies (@Context annotations) into the provider instance. The injections are successful but the target object for them will be the proxy instance (not the real instance behind it). Consequently, at runtime, when the proxy delegates the …

CXF-7544: Support @Context-based injection into proxied CDI beans

---

core/src/main/java/org/apache/cxf/interceptor/MessageSenderInterceptor.java
core/src/main/java/org/apache/cxf/interceptor/Messages.properties

Consider SocketTimeoutExceptions to be incoming message faults while all other
IOExceptions to be outgoing message faults. Each type will have its own error message.

When failing to close conduit, distinct read faults from write faults

---

rt/rs/security/oauth-parent/oauth2/src/main/java/org/apache/cxf/rs/security/oauth2/services/AuthorizationMetadataService.java

Default port should be removed from
issuer and endpoints in discovery
documents.
aka
"issuer":"https://authorization-server:443"
should be
"issuer":"https://authorization-server"

[CXF-7572] default port in OAuth discovery doc

---

rt/rs/microprofile-client/src/main/java/org/apache/cxf/microprofile/client/CxfTypeSafeClientBuilder.java
rt/rs/microprofile-client/src/test/java/org/apache/cxf/microprofile/client/CxfTypeSafeClientBuilderTest.java
rt/rs/microprofile-client/src/test/java/org/apache/cxf/microprofile/client/mock/HighPriorityClientReqFilter.java
rt/rs/microprofile-client/src/test/java/org/apache/cxf/microprofile/client/mock/HighPriorityMBW.java
rt/rs/microprofile-client/src/test/java/org/apache/cxf/microprofile/client/mock/LowPriorityClientReqFilter.java
rt/rs/microprofile-client/src/test/java/org/apache/cxf/microprofile/client/mock/MyClient.java
rt/rs/microprofile-client/src/test/java/org/apache/cxf/microprofile/client/mock/MyObject.java

@johnament Can you take a look at these changes?
This should help us handle the `Configurable` methods.  Notice that the overrides of the priority do not currently work (note the test that has the `@Ignore` annotation).  I ran a similar test using the JAX-RS client and that worked, so I'm probably just missing something simple...  if you see it, please let me know.  Thanks!

Config handling for MP rest client

---

core/src/main/java/org/apache/cxf/attachment/AttachmentSerializer.java

Here is a propsed fix for the bug that closes the `InputStream` after it has been encoded an written to the `OutputSteam`.

[CXF-7585] Close InputStream in AttachmentSerializer when base64 encoding is used

---

rt/ws/rm/src/main/java/org/apache/cxf/ws/rm/SourceSequence.java

This fixes https://issues.apache.org/jira/browse/CXF-7470 by making the setTarget method public.

[CXF-7470] Cannot set target for recovered source sequence

---

rt/rs/security/oauth-parent/oauth2/src/main/java/org/apache/cxf/rs/security/oauth2/grants/code/JPACMTCodeDataProvider.java
rt/rs/security/oauth-parent/oauth2/src/test/resources/org/apache/cxf/rs/security/oauth2/grants/code/JPACMTCodeDataProvider.xml
rt/rs/security/sso/oidc/src/test/resources/org/apache/cxf/rs/security/oidc/idp/JPAOidcUserSubjectCMTTest.xml

Remove PersistenceContext anotation
from JPACMTCodeDataProvider as it
impeds application startup on JBoss EAP 6.x
when the application declares multiple
persistence units in its persistence.xml.

CXF-7586: Remove @PersistenceContext

---

rt/transports/http-jetty/src/main/java/org/apache/cxf/transport/http_jetty/JettyHTTPServerEngine.java
systests/jaxrs/src/test/java/org/apache/cxf/systest/jaxrs/JAXRSClientServerUserResourceAsteriskTest.java

https://issues.apache.org/jira/browse/CXF-7587
Thanks!

[CXF-7587] use Jetty context path when setting HTTP handler name

---

core/src/main/java/org/apache/cxf/interceptor/AbstractFaultChainInitiatorObserver.java
core/src/main/java/org/apache/cxf/interceptor/Messages.properties

Use Messages.properties and change message to better indicate that an
error occurred during error handling, preventing further action.

CXF-7604 Refine error message during error handling

---

rt/rs/microprofile-client/src/main/java/org/apache/cxf/microprofile/client/MicroProfileClientProviderFactory.java
rt/rs/microprofile-client/src/test/java/org/apache/cxf/microprofile/client/CxfTypeSafeClientBuilderTest.java
rt/rs/microprofile-client/src/test/java/org/apache/cxf/microprofile/client/mock/ExceptionMappingClient.java
rt/rs/microprofile-client/src/test/java/org/apache/cxf/microprofile/client/mock/NoSuchEntityException.java
rt/rs/microprofile-client/src/test/java/org/apache/cxf/microprofile/client/mock/NotFoundClientReqFilter.java
rt/rs/microprofile-client/src/test/java/org/apache/cxf/microprofile/client/mock/NotFoundExceptionMapper.java

We should not need to call handleMapper for the ResponseExceptionMappers
- they already require the parameterized type to be a subclass of 
Throwable. And the handleMapper method checks whether the Throwable
class can be assigned to the type in the user's REM - which it never
will be (unless they define ResponseExceptionMapper<Throwable>).
This also adds unit tests ensuring that the REM is executed.
@johnament - can you review this to make sure I'm on the right track?

Handle ResponseExceptionMappers

---

rt/frontend/jaxrs/src/main/java/org/apache/cxf/jaxrs/impl/UriBuilderImpl.java
rt/frontend/jaxrs/src/test/java/org/apache/cxf/jaxrs/impl/UriBuilderImplTest.java

The JAX-RS 2.1 TCK checks that a URI that has a non-integer port - i.e.
a scheme specific part that looks like host:port. They expect that the
string returned from UriBuilder.fromUri(uri).build().toString() should
include the scheme and the scheme-specific part, but CXF currently drops
the scheme-specific part.  This change helps to ensure that we preserve
it, and adds a test similar to the TCK.

[CXF-7625] Handle schemeSpecificPart that looks like host:port

---

tools/wsdlto/frontend/jaxws/src/main/java/org/apache/cxf/tools/wsdlto/frontend/jaxws/template/fault.vm

reference qualified 'java.lang.Throwable' in order to avoid compile conflicts with 'Throwable' type in the same package

[CXF-6134] Apache CXF generating constructor with duplicate argument names causing compilation error

---

rt/transports/http-jetty/src/main/java/org/apache/cxf/transport/http_jetty/blueprint/JettyHTTPServerEngineFactoryHolder.java

Enable JMX connector and ThreadingParameters mbean for cxf webservice
created with custom threading parameters in blueprint.xml.

[CXF-7628] Enable JMX threading parameters for cxf endpoints in blueprint.

---

rt/frontend/jaxrs/src/main/java/org/apache/cxf/jaxrs/model/FilterProviderInfo.java
rt/frontend/jaxrs/src/main/java/org/apache/cxf/jaxrs/provider/ServerProviderFactory.java
systests/jaxrs/src/test/java/org/apache/cxf/systest/jaxrs/BookServer20.java

This makes `@NameBinding` work also when installing filters using a `Feature`

[CXF-7630] Do not preset namebindings when installing through a Feature

---

rt/rs/client/src/main/java/org/apache/cxf/jaxrs/client/AbstractClient.java
rt/rs/client/src/main/java/org/apache/cxf/jaxrs/client/spec/ClientRequestFilterInterceptor.java
rt/rs/client/src/main/java/org/apache/cxf/jaxrs/client/spec/InvocationBuilderImpl.java
rt/rs/client/src/test/java/org/apache/cxf/jaxrs/client/spec/ClientRequestFilterTest.java
rt/rs/client/src/test/java/org/apache/cxf/jaxrs/client/spec/InvocationBuilderImplTest.java
rt/rs/sse/src/main/java/org/apache/cxf/jaxrs/sse/client/SseEventSourceImpl.java
rt/rs/sse/src/test/java/org/apache/cxf/jaxrs/sse/client/SseEventSourceImplTest.java
rt/transports/http/src/main/java/org/apache/cxf/transport/http/Headers.java
rt/transports/http/src/test/java/org/apache/cxf/transport/http/HeadersTest.java

In testing the JAX-RS 2.1 TCK, we've found a few issues:
1) The `Headers.toHttpLanguage(...)` method will return things like "en-" in some cases - I believe this is because there is an empty (but non-null) country passed in as part of the Locale.  This seems like an error condition to me, but it seems to be tested by the TCK, so the fix is pretty simple - just checking whether the country is non-empty rather than just non-null.
2) The javadoc for `Invocation.Builder.headers(...)` method says that when called, all pre-existing headers must be removed.  Currently, we're just adding the new headers, but not removing the old ones.  
I provided test cases for these conditions, but I won't have confirmation that these fixes actually pass the TCK until tomorrow, but I wanted to get the PR out …

JAX-RS 2.1 TCK issues

---

parent/pom.xml

Updating the Import-Package of javax.servlet.* packages to include 4.0.  This is a small change, but is used in several modules.  I'm mainly looking for an automated build to confirm that this change doesn't break anything, but review/suggestions welcome.  Thanks!

[CXF-7639] Update dependency to servlet 4.0

---

integration/cdi/src/main/java/org/apache/cxf/cdi/CdiServerConfigurableFactory.java
rt/frontend/jaxrs/src/main/java/org/apache/cxf/jaxrs/impl/ConfigurableImpl.java
rt/frontend/jaxrs/src/main/java/org/apache/cxf/jaxrs/impl/ConfigurationImpl.java
rt/frontend/jaxrs/src/main/java/org/apache/cxf/jaxrs/provider/ServerConfigurableFactory.java
rt/frontend/jaxrs/src/main/java/org/apache/cxf/jaxrs/provider/ServerProviderFactory.java
rt/frontend/jaxrs/src/test/java/org/apache/cxf/jaxrs/impl/ConfigurationImplTest.java
rt/rs/client/src/main/java/org/apache/cxf/jaxrs/client/spec/ClientConfigurableImpl.java
rt/rs/client/src/test/java/org/apache/cxf/jaxrs/client/spec/ClientImplTest.java
rt/rs/microprofile-client/src/main/java/org/apache/cxf/microprofile/client/MicroProfileClientConfigurableImpl.java

Per JAX-RS javadoc, all registered components must implement the
contracts specified in the passed in array of Classes or the map of 
contracts to priorities.  CXF should also log a warning when an invalid
contract is passed in to alert the user that the call to register has
been ignored.
Since ServerProviderFactory and CdiServerConfigurableFactory also used
this same registration mechanism (passing in server side filters/
interceptors, these parts also needed changes.
Looking for a review because I'm not 100% certain what the supportedContracts flow was really doing or if there are any negative effects from removing it.

[CXF-7638] Only register provider if it implements specified contracts

---

core/src/main/java/org/apache/cxf/bus/managers/DestinationFactoryManagerImpl.java
core/src/main/java/org/apache/cxf/transport/AbstractTransportFactory.java
core/src/main/java/org/apache/cxf/transport/DestinationFactoryManager.java
rt/rs/sse/src/main/java/org/apache/cxf/jaxrs/sse/ext/SseTransportCustomizationExtension.java
rt/transports/http/src/main/java/org/apache/cxf/transport/servlet/CXFNonSpringServlet.java

Enhanced the default transport selection mechanism to consult bus property and already registered destination factories. It gives customization extensions (like SSE for example) to hint about preferred transport to use in case none of them is specified explicitly.

CXF-7659: Improve SSE automatic configuration. 

---

maven-plugins/codegen-plugin/pom.xml

Generate a help mojo for the cxf-codegen-plugin, so the user can get help regarding goals and parameters from the command line.
You can read more about how to use a help mojo here: https://maven.apache.org/plugin-tools/maven-plugin-plugin/help-mojo.html

Generate a help mojo for the cxf-codegen-plugin

---

core/src/main/java/org/apache/cxf/helpers/DOMUtils.java
rt/databinding/aegis/src/main/java/org/apache/cxf/aegis/type/XMLTypeCreator.java
rt/frontend/jaxrs/src/main/java/org/apache/cxf/jaxrs/utils/ResourceUtils.java
rt/frontend/jaxrs/src/test/java/org/apache/cxf/jaxrs/utils/ResourceUtilsTest.java
rt/transports/http-hc/src/main/java/org/apache/cxf/transport/http/asyncclient/AsyncHTTPConduit.java

In each resource class, an annotated method should be registered only once.

[CXF-7670] create a single ClassResourceInfo per class + annotated method

---

integration/cdi/src/main/java/org/apache/cxf/cdi/ContextProducerBean.java
integration/cdi/src/main/java/org/apache/cxf/cdi/JAXRSCdiResourceExtension.java
systests/cdi/base/src/main/java/org/apache/cxf/systests/cdi/base/AbstractCdiSingleAppTest.java
systests/cdi/base/src/main/java/org/apache/cxf/systests/cdi/base/BookStore.java
systests/cdi/base/src/main/java/org/apache/cxf/systests/cdi/base/Injections.java

This PR tries to make defaults of the CDI extension better, here are the changes:
1. if it detects OWB-web or weld-web it deactivate default context beans for HttpServletRequest and ServletContext
2. it observes beans to detect the types conflicting with "auto" context beans
3. it fires the extension and exposes the list of exclusion to let integration layers configure it properly if 1/2 defaults are not enough 
4. when it adds context beans it removes @Default from the ones which are found with 1/2/3 - but it keeps it with the cxf specific qualifier if needed (best practise being to use this classifier for internal/extensions needs)

CXF-7643 ensure CDI extension defaults are CDI compliant

---

tools/wsdlto/frontend/jaxws/src/main/java/org/apache/cxf/tools/wsdlto/frontend/jaxws/customization/JAXWSBindingSerializer.java
tools/wsdlto/frontend/jaxws/src/main/java/org/apache/cxf/tools/wsdlto/frontend/jaxws/wsdl11/JAXWSDefinitionBuilder.java

Revert some changes from commit bcb6385a095dcaaf8390ecfc33e9e22b9149daad that causes problem when generating ws client jar with jaxws bindings

CXF-7695 wsdl2java client jar generation fails if jaxws binding is used

---

rt/ws/addr/src/main/java/org/apache/cxf/ws/addressing/policy/AddressingAssertionBuilder.java

fix wrong log warning "Unable to recognize the addressing policy"

[CXF-7704] False positive warning log

---

rt/databinding/jaxb/src/main/java/org/apache/cxf/jaxb/JAXBDataBinding.java

JIRA: https://issues.apache.org/jira/browse/CXF-7707
See downstream for more info:
https://issues.jboss.org/browse/JBWS-4097
https://github.com/jboss/cxf/pull/18

[CXF-7707] JAXB doesn't (un)marshall property with @XmlElementRef

---

maven-plugins/codegen-plugin/pom.xml

Fixed and tested on JDK 8,9 and 10. @deki please review.

CXF-7708: fix groovy verification for jdk9 and jdk10

---

rt/features/clustering/src/main/java/org/apache/cxf/clustering/circuitbreaker/CircuitBreakerFailoverFeature.java

Adds a setTargetSelector method to CircuitBreakerFailoverFeature

[CXF-7726] allows targetSelector to be set in CircuitBreakerFailoverFeature

---

rt/frontend/jaxrs/src/main/java/org/apache/cxf/jaxrs/lifecycle/PerRequestResourceProvider.java
rt/frontend/jaxrs/src/main/java/org/apache/cxf/jaxrs/model/URITemplate.java
rt/frontend/jaxrs/src/main/java/org/apache/cxf/jaxrs/provider/ProviderFactory.java
rt/frontend/jaxrs/src/main/java/org/apache/cxf/jaxrs/utils/AccumulatingIntersector.java
rt/frontend/jaxrs/src/main/java/org/apache/cxf/jaxrs/utils/HttpUtils.java
rt/frontend/jaxrs/src/main/java/org/apache/cxf/jaxrs/utils/JAXRSUtils.java
rt/frontend/jaxrs/src/main/java/org/apache/cxf/jaxrs/utils/MimeTypesIntersector.java
rt/frontend/jaxrs/src/main/java/org/apache/cxf/jaxrs/utils/NonAccumulatingIntersector.java
rt/frontend/jaxrs/src/main/java/org/apache/cxf/jaxrs/utils/ResourceUtils.java

The IBM performance team has identified several areas of improvement to reduce garbage collection and CPU usage.
First, we reduced the amount of StringBuilders created in HTTPUtils.java and ResourceUtils.java.
Second, we created JAXRSUtils.doMimeTypesIntersect() - a method similar to JAXRSUtils.intersectMimeTypes - that doesn't create a HashSet but instead returns a boolean when we just need to know if they intersect.
Third, we found that getting the annotations for parameters to create constructor arguments in PerRequestResourceProvider.java is expensive, so we cache them in the constructor instead of getting them via reflection every request.
These changes combined result in a ~1.5-2% performance increase.

[CXF-7716] Reduce StringBuilders and other performance changes.

---

core/src/main/java/org/apache/cxf/attachment/AttachmentSerializer.java

JIRA: https://issues.apache.org/jira/browse/CXF-7317
downstream: https://issues.jboss.org/browse/JBWS-4064
According to https://tools.ietf.org/html/rfc2392, Content-ID header shouldn't be decoded
> For example, "cid:foo4%25foo1@bar.net" corresponds to Content-ID: \<foo4%25foo1@bar.net\>
See comments in JBWS-4064 for more info

[CXF-7317] Non-URL encoded Content-Id href does not seem be serialized by CXF's AttachmentSerializer

---

rt/rs/description-swagger-ui/src/main/java/org/apache/cxf/jaxrs/swagger/SwaggerUiResolver.java

Add support for JBoss 7.0 EAP class loader which is returning an url ending with ".jar/" instead of the expected ".jar" or ".jar!/"

CXF-7746 Swagger2Feature - SwaggerUiResolver & JBoss 7.0 EAP

---

rt/transports/http/src/main/java/org/apache/cxf/transport/servlet/AbstractHTTPServlet.java

When behind more than one reverse proxy, each can add a new entry in X-Forwarded-Host, resulting in:
> X-Forwarded-Host: host1, host2
Consider the outermost proxy/host ('host1') like done for 'originalRemoteAddr'.

Consider the outermost proxy in X-Forwarded-Host

---

rt/frontend/jaxrs/src/main/java/org/apache/cxf/jaxrs/provider/ProviderFactory.java

If newInstance fails because the called constructor of a custom Application implementation throws an exception, the root cause is not included which would reduce the search time for the actual cause.

createProviderFromConstructor should include exception cause

---

rt/rs/description-swagger-ui/src/main/java/org/apache/cxf/jaxrs/swagger/OsgiSwaggerUiResolver.java

When findSwaggerUiRootInternal(null, null) is called, the root is returned without the version number which is needed to locate the index.html and other resources within the bundle.
/META-INF/resources/webjars/swagger-ui//index.html
instead of 
/META-INF/resources/webjars/swagger-ui/3.17.6/index.html

UI not resolved correctly if version not specificed

---

rt/rs/description-swagger-ui/src/main/java/org/apache/cxf/jaxrs/swagger/OsgiSwaggerUiResolver.java

bundle.getBundleContext() will give an NPE (in Equinox) if the bundle can be found but is not active.
Would also be good to at least log the exception in debug mode to point to a possible problem.

NPE when annotations bundle found but not active

---

rt/databinding/jaxb/src/main/java/org/apache/cxf/jaxb/JAXBEncoderDecoder.java
systests/databinding/src/test/java/org/apache/cxf/systest/jaxb/TestServiceTest.java
systests/databinding/src/test/java/org/apache/cxf/systest/jaxb/service/ErrorData.java
systests/databinding/src/test/java/org/apache/cxf/systest/jaxb/service/PropertyOrderException.java
systests/databinding/src/test/java/org/apache/cxf/systest/jaxb/service/TestService.java
systests/databinding/src/test/java/org/apache/cxf/systest/jaxb/service/TestServiceImpl.java

Backport of 354ab5e7eb63aef3f7b213cb9637acf8f9274305

[CXF-7823]:JAXBEncoderDecoder doesn't respect @XmlType's propOrder in Exception class

---

rt/frontend/jaxrs/src/main/java/org/apache/cxf/jaxrs/provider/XSLTJaxbProvider.java

to allow override, e.g. for pdf generation using apache fop

introduce getStreamResult

---

core/src/main/java/org/apache/cxf/helpers/JavaUtils.java
maven-plugins/java2ws-plugin/src/main/java/org/apache/cxf/maven_plugin/Java2WSMojo.java

When using the `cxf-java2ws-plugin` from a Maven project using JDK 9+ (10 and 11 release candidate) on Windows 10, it fails to run because the generated command line is too long.
As an example, in one project I'm working on, the generated classpath was more than 75000 characters long – Yes, it is a big project. It works on JDK 8.
`[ERROR] Failed to execute goal org.apache.cxf:cxf-java2ws-plugin:3.2.6:java2ws (EXECUTIONNAME) on project PROJECTNAME: Error while executing process.: Cannot run program "cmd.exe" (in directory "C:\opt\dev\..._PROJECTNAME_\target"): CreateProcess error=206, The filename or extension is too long -> [Help 1]`
The current code base (3.3.0-SNAPSHOT) does not work at all with JDK 10 or 11.
The problem is that the classpath is part of the command line and on Windows …

[CXF-7830] Support for running java2ws-plugin using JDK9+ on Windows.

---

core/src/main/java/org/apache/cxf/attachment/AttachmentSerializer.java

Reverts apache/cxf#408
See https://www.rfc-editor.org/errata/rfc2392

Revert "[CXF-7317] Non-URL encoded Content-Id href does not seem be serialized by CXF's AttachmentSerializer"

---

services/sts/sts-core/src/main/java/org/apache/cxf/sts/token/provider/DefaultConditionsProvider.java
services/sts/sts-core/src/test/java/org/apache/cxf/sts/token/provider/SAMLProviderLifetimeTest.java

WS-trust define that a `/wst:RequestSecurityToken/wst:Lifetime` can be specified with only having `wsu:Expires`. In that case the creationTime shall be set to the current time. CXF simply ignore the lifetime if either expires or created is not present.
I have fixed the behavior and provide a unit test for it. I have to also modify test `testSaml2NoExpires` because it fails after my changes, because the creationTime was too fare in the future. The "old" implementation just ignore the creationTime, which was wrong.
If my change is acceptable, could you please also merge the fix to 3.2-branch. Thank you.

CXF-7864: Fix issue if lifetime only specify expired without created

---

rt/transports/http/src/main/java/org/apache/cxf/transport/http/policy/impl/ClientPolicyCalculator.java
rt/transports/http/src/test/java/org/apache/cxf/transport/http/policy/ClientPolicyCalculatorTest.java

https://issues.apache.org/jira/browse/CXF-7878
Timeout values set to random numbers in the test to avoid accidentally setting them to the same value as a default and not noticing.

CXF-7878: ClientPolicyCalculator ignores ConnectionRequestTimeout property

---

rt/frontend/jaxws/src/main/java/org/apache/cxf/jaxws/context/WrappedMessageContext.java
rt/frontend/jaxws/src/test/java/org/apache/cxf/jaxws/context/WrappedMessageContextTest.java

Upstream issue: https://issues.apache.org/jira/browse/CXF-7832
Upstream commit https://github.com/apache/cxf/commit/01ec97bfcfd6ba59687da128b31d3995194c3bfc
EAP 7.1.x jira: https://issues.jboss.org/browse/JBEAP-15389

[CXF-7832]WrappedMessageContext containsKey not consistent with get/put

---

rt/transports/http/src/main/java/org/apache/cxf/transport/http/HTTPConduit.java
rt/transports/http/src/test/java/org/apache/cxf/transport/http/HTTPConduitTest.java
rt/transports/http/src/test/java/org/apache/cxf/transport/http/MockHTTPConduit.java

In the case where the current Executor throws a RejectedExecutionException:
This should ensure that if allowCurrentThread is false OR the client policy has setAsyncExecuteTimeoutRejection, then the the caller should receive a RejectedExecutionException.
If allowCurrentThread is true, then current thread will handle the async response.
This should resolve JIRA [CXF-7881](
https://issues.apache.org/jira/browse/CXF-7881)

CXF-7881: Ensure proper allowCurrentThread behavior

---

rt/rs/client/src/main/java/org/apache/cxf/jaxrs/client/ClientProxyImpl.java
rt/rs/microprofile-client/src/test/java/org/apache/cxf/microprofile/client/CxfTypeSafeClientBuilderTest.java
rt/rs/microprofile-client/src/test/java/org/apache/cxf/microprofile/client/mock/MyClient.java

Runtime code changes based on patterns described here:
https://rmannibucau.wordpress.com/2014/03/27/java-8-default-interface-methods-and-jdk-dynamic-proxies/
This enables default interface methods to be invoked when they are not overridden or annotated with `@GET`-type annotations.
I would like to push this back to the 3.2.X stream once approved.

[CXF-7922] Invoke default interface methods on client interfaces

---

core/src/main/java/org/apache/cxf/helpers/HttpHeaderHelper.java
core/src/test/java/org/apache/cxf/common/util/Base64UtilityTest.java
core/src/test/java/org/apache/cxf/helpers/HttpHeaderHelperTest.java
rt/transports/jms/src/main/java/org/apache/cxf/transport/jms/JMSMessageUtils.java
rt/transports/jms/src/test/java/org/apache/cxf/transport/jms/JMSMessageUtilTest.java

benchmark [1] results:
- old: 40 MB 47 ms
- new: 9 MB 0 ms
1.
```
public class HttpHeaderHelperMapCharsetTest {
private static final int CNT = 131072;
static final String charset = java.nio.charset.StandardCharsets.UTF_8.name();
private static final String[] STR = new String[CNT];
static {
for (int i = 0; i < CNT; ++i) {
if (i % 3 == 0) {
STR[i] = "\"" + charset + "\"";
} else if (i % 3 == 1) {
STR[i] = "'" + charset + "'";
} else {
STR[i] = charset;
}
}
}
@org.junit.Test
public void mapCharset() {
metrics("HttpHeaderHelper::mapCharset", HttpHeaderHelper::mapCharset);
}
@org.junit.Test
public void mapCharset2() {
metrics("HttpHeaderHelper::mapCharset2", HttpHeaderHelper::mapCharset2);
}
private static void metrics(String label, java.util.function.Function<String, String> f) { …
```

HttpHeaderHelper: String.replace instead of Pattern.matcher().replaceAll

---

rt/rs/client/src/main/java/org/apache/cxf/jaxrs/client/ClientProperties.java
rt/rs/client/src/main/java/org/apache/cxf/jaxrs/client/spec/ClientBuilderImpl.java
rt/rs/client/src/main/java/org/apache/cxf/jaxrs/client/spec/ClientImpl.java
rt/rs/microprofile-client/pom.xml
rt/rs/microprofile-client/src/main/java/org/apache/cxf/microprofile/client/CxfTypeSafeClientBuilder.java
rt/rs/microprofile-client/src/main/java/org/apache/cxf/microprofile/client/Messages.properties
rt/rs/microprofile-client/src/main/java/org/apache/cxf/microprofile/client/MicroProfileClientConfigurableImpl.java
rt/rs/microprofile-client/src/main/java/org/apache/cxf/microprofile/client/MicroProfileClientFactoryBean.java
rt/rs/microprofile-client/src/main/java/org/apache/cxf/microprofile/client/cdi/CDIInterceptorWrapper.java
rt/rs/microprofile-client/src/main/java/org/apache/cxf/microprofile/client/cdi/CDIInterceptorWrapperImpl.java
rt/rs/microprofile-client/src/main/java/org/apache/cxf/microprofile/client/cdi/InterceptorInvoker.java
rt/rs/microprofile-client/src/main/java/org/apache/cxf/microprofile/client/cdi/MPRestClientInvocationContextImpl.java
rt/rs/microprofile-client/src/main/java/org/apache/cxf/microprofile/client/cdi/RestClientBean.java
rt/rs/microprofile-client/src/main/java/org/apache/cxf/microprofile/client/config/ConfigFacade.java
rt/rs/microprofile-client/src/main/java/org/apache/cxf/microprofile/client/proxy/MPAsyncInvocationInterceptorImpl.java
rt/rs/microprofile-client/src/main/java/org/apache/cxf/microprofile/client/proxy/MPAsyncInvocationInterceptorRemoveContextImpl.java
rt/rs/microprofile-client/src/main/java/org/apache/cxf/microprofile/client/proxy/MicroProfileClientProxyImpl.java
systests/microprofile/client/async/pom.xml
systests/microprofile/client/async/src/test/java/org/apache/cxf/systest/microprofile/rest/client/mock/AsyncInvocationInterceptorFactoryTestImpl.java
systests/microprofile/client/async/src/test/java/org/apache/cxf/systest/microprofile/rest/client/mock/AsyncInvocationInterceptorFactoryTestImpl2.java
systests/microprofile/client/weld/testng.xml
systests/microprofile/pom.xml

This implements MP Rest Client 1.2 Milestone 2 which includes:
* specifying the baseURI in the `@RegisterRestClient` annotation.
* `removeContext` method in `AsyncInvocationInterceptor` interface.
* new `RestClientListener` interface for intercepting client instances.
* portable connect and read timeout properties.
* invoking CDI interceptors.
This commit includes the runtime changes, some unit test changes, updates to the systests to include the latest TCK test cases, etc.

[CXF-7926] Initial MP Rest Client 1.2 impl

---

core/src/main/java/org/apache/cxf/service/model/EndpointInfo.java
core/src/main/java/org/apache/cxf/transport/AbstractDestination.java
core/src/main/java/org/apache/cxf/ws/addressing/ContextJAXBUtils.java
core/src/main/java/org/apache/cxf/ws/addressing/ContextUtils.java
core/src/main/java/org/apache/cxf/ws/addressing/EndpointReferenceUtils.java
core/src/main/java/org/apache/cxf/ws/addressing/VersionTransformer.java
rt/frontend/jaxrs/src/main/java/org/apache/cxf/jaxrs/provider/AbstractJAXBProvider.java
rt/frontend/jaxrs/src/main/java/org/apache/cxf/jaxrs/provider/ProviderFactory.java
rt/frontend/jaxrs/src/main/java/org/apache/cxf/jaxrs/utils/AnnotationUtils.java
rt/frontend/jaxrs/src/main/java/org/apache/cxf/jaxrs/utils/JAXBUtils.java
rt/frontend/jaxrs/src/main/java/org/apache/cxf/jaxrs/utils/ResourceUtils.java
rt/rs/description/src/main/java/org/apache/cxf/jaxrs/model/wadl/WadlGenerator.java
rt/ws/addr/src/test/java/org/apache/cxf/ws/addressing/soap/MAPCodecTest.java

Goal is to ensure default java11 experience is still good when not needing JAXB/activation (which is pretty much often these days with JAX-RS)

Ensure JAXB and javax.activation are not required for JAX-RS

---

rt/rs/microprofile-client/pom.xml
rt/rs/microprofile-client/src/main/java/org/apache/cxf/microprofile/client/CxfTypeSafeClientBuilder.java
rt/rs/microprofile-client/src/main/java/org/apache/cxf/microprofile/client/Messages.properties
rt/rs/microprofile-client/src/main/java/org/apache/cxf/microprofile/client/MicroProfileClientFactoryBean.java
rt/rs/microprofile-client/src/main/java/org/apache/cxf/microprofile/client/Validator.java
rt/rs/microprofile-client/src/main/java/org/apache/cxf/microprofile/client/cdi/RestClientBean.java
rt/rs/microprofile-client/src/main/java/org/apache/cxf/microprofile/client/proxy/MicroProfileClientProxyImpl.java
rt/rs/microprofile-client/src/test/java/org/apache/cxf/microprofile/client/ClientHeadersTest.java
rt/rs/microprofile-client/src/test/java/org/apache/cxf/microprofile/client/ValidatorTest.java
rt/rs/microprofile-client/src/test/java/org/apache/cxf/microprofile/client/mock/HeaderCaptureClientRequestFilter.java
rt/rs/microprofile-client/src/test/java/org/apache/cxf/microprofile/client/mock/HeaderGenerator.java
rt/rs/microprofile-client/src/test/java/org/apache/cxf/microprofile/client/mock/HeadersFactoryClient.java
rt/rs/microprofile-client/src/test/java/org/apache/cxf/microprofile/client/mock/HeadersOnInterfaceClient.java
rt/rs/microprofile-client/src/test/java/org/apache/cxf/microprofile/client/mock/HeadersOnMethodClient.java
rt/rs/microprofile-client/src/test/java/org/apache/cxf/microprofile/client/mock/MyClientHeadersFactory.java
systests/microprofile/client/async/pom.xml
systests/microprofile/client/jaxrs/pom.xml
systests/microprofile/client/jaxrs/src/test/java/org/apache/cxf/systest/microprofile/rest/client/JaxrsHeaderPropagationTest.java
systests/microprofile/client/jaxrs/src/test/java/org/apache/cxf/systest/microprofile/rest/client/JaxrsResource.java
systests/microprofile/client/jaxrs/src/test/java/org/apache/cxf/systest/microprofile/rest/client/MockConfigProviderResolver.java
systests/microprofile/client/jaxrs/src/test/java/org/apache/cxf/systest/microprofile/rest/client/RestClient.java
systests/microprofile/client/jaxrs/src/test/java/org/apache/cxf/systest/microprofile/rest/client/ReturnAllOutboundHeadersFilter.java
systests/microprofile/client/weld/testng.xml
systests/microprofile/pom.xml

* This includes generation and propagation of HTTPHeaders via @ClientHeaderParam annotations and ClientHeadersFactory.
* Ensuring that timeout props only have effect when using CDI.
* Related unit and system tests.
* Updates from the milestone 2 release to release candidate 1 of the API and TCK (1.2 final release is expected late next week).

[CXF-7926] Initial MP Rest Client 1.2 impl - part 2

---

core/src/main/java/org/apache/cxf/helpers/JavaUtils.java

If an environment defines the java.version with 1.8.0 this code will die with an ArrayIndexOutOfBoundsEx. 
To evade this either the length of the version should be checked for being >6 or, as proposed in the pr, the 1.8.0 version format should be checked for an additional underscore - if its not there then the environment uses something different than the expected value like 1.8.0_161. But it should never die with an AIOB-Ex. Thank you.

Get rid of IndexArrayOutOfBounds

---

parent/pom.xml

Commit 424591420b052a2b557d3f1dd48609c9858d9809 bumped Spring to version 5 however the OSGi version constraints still only allowed max version 4 of Spring.

Fix Spring 5 OSGi version constraints

---

core/src/main/java/org/apache/cxf/staxutils/StaxUtils.java

Rational is that people don't understand why JAXB does not work when woodstox is excluded, goal is to ensure the error is explicit about that.

More details when woodstox is not present and a XMLInputFactory can't be created

---

osgi/karaf/features/src/main/resources/features.xml

Issue: https://issues.apache.org/jira/browse/CXF-7974
Removal of <library ....jaxws-api.. > from cxf-jaxws. Library is already defined in cxf-specs, so it could be removed -> solves problems on jdk11.

CXF-7974 <library> defined in cxf-jaxws causes trouble (jdk11)

---

rt/features/logging/src/main/java/org/apache/cxf/ext/logging/AbstractLoggingInterceptor.java
rt/features/logging/src/main/java/org/apache/cxf/ext/logging/LoggingFeature.java
rt/features/logging/src/main/java/org/apache/cxf/ext/logging/LoggingInInterceptor.java
rt/features/logging/src/main/java/org/apache/cxf/ext/logging/LoggingOutInterceptor.java
rt/features/logging/src/main/java/org/apache/cxf/ext/logging/event/DefaultLogEventMapper.java

Need for 
https://issues.apache.org/jira/browse/CXF-7920

Configure media types in bean for logging intercepters

---

testutils/src/main/java/org/apache/cxf/testutil/common/ServerLauncher.java
testutils/src/main/java/org/apache/cxf/testutil/common/TestUtil.java

avoid 'java.io.IOException: CreateProcess error=206, The filename or extension is too long' on Windows

[cxf-testutils] ServerLauncher: expose only running server ports

---

rt/rs/microprofile-client/src/main/java/org/apache/cxf/microprofile/client/cdi/RestClientExtension.java

This PR fixes the error below. Basically it will avoid beans to leak and cause issues when there are multiple apps using the same classes.
Error
Caused by: org.apache.webbeans.exception.WebBeansException: org.apache.webbeans.exception.DuplicateDefinitionException: PassivationCapable bean id is not unique: br.com.gbrsistemas.crvirtual.classificacao.SiemClassificacaoServiceClient bean:SiemClassificacaoServiceClient, WebBeansType:THIRDPARTY, Name:br.com.gbrsistemas.crvirtual.classificacao.SiemClassificacaoServiceClient, API Types:[br.com.gbrsistemas.crvirtual.classificacao.SiemClassificacaoServiceClient], Qualifiers:[javax.enterprise.inject.Default,org.eclipse.microprofile.rest.client.inject.RestClient,javax.enterprise.inject.Any], existing: SiemClassificacaoServiceClient, …

CXF-7980 Fixing bean leak

---

rt/frontend/jaxrs/src/main/java/org/apache/cxf/jaxrs/JAXRSInvoker.java
systests/jaxrs/src/test/java/org/apache/cxf/systest/jaxrs/reactive/CompletableFutureServer.java
systests/jaxrs/src/test/java/org/apache/cxf/systest/jaxrs/reactive/CompletableFutureService.java
systests/jaxrs/src/test/java/org/apache/cxf/systest/jaxrs/reactive/JAXRSCompletionStageTest.java
systests/jaxrs/src/test/java/org/apache/cxf/systest/jaxrs/reactive/MappedException.java
systests/jaxrs/src/test/java/org/apache/cxf/systest/jaxrs/reactive/MappedExceptionMapper.java

The Problem
===
In case when CXF is used along with `CompletionStage` / `CompletableFuture`, in most cases the error handling is propagated back through `CompletionException` instance (http://cs.oswego.edu/pipermail/concurrency-interest/2014-August/012911.html). It works but it forces users to introduce own implementations of `ExceptionMapper`s and manually unwrap the `CompletionException` into something more meaningful.
Use cases
===
There are 3 leading use cases which cover most typical usage of the `CompletionStage` / `CompletableFuture`.
1. `@Suspended AsyncResponse`
```
public void get(@PathParam("isbn") String isbn, @Suspended final AsyncResponse resp) {
client.target("http://localhost:19092/services/catalog/" + isbn)
.request()
.rx()
.get(Book.class)
.whenComplete((r, ex) -> {
if …
```

CXF-7989: org.apache.cxf.jaxrs.JAXRSInvoker should handle CompletionException

---

rt/ws/security/src/main/java/org/apache/cxf/ws/security/policy/interceptors/KerberosTokenInterceptorProvider.java
rt/ws/security/src/main/java/org/apache/cxf/ws/security/policy/interceptors/STSInvoker.java
rt/ws/security/src/main/java/org/apache/cxf/ws/security/policy/interceptors/SecureConversationInInterceptor.java
rt/ws/security/src/main/java/org/apache/cxf/ws/security/policy/interceptors/SpnegoContextTokenOutInterceptor.java
rt/ws/security/src/main/java/org/apache/cxf/ws/security/tokenstore/MemoryTokenStore.java
rt/ws/security/src/main/java/org/apache/cxf/ws/security/trust/STSLoginModule.java
rt/ws/security/src/main/java/org/apache/cxf/ws/security/trust/STSTokenRetriever.java
rt/ws/security/src/main/java/org/apache/cxf/ws/security/wss4j/CryptoCoverageUtil.java
rt/ws/security/src/main/java/org/apache/cxf/ws/security/wss4j/PolicyBasedWSS4JInInterceptor.java
rt/ws/security/src/main/java/org/apache/cxf/ws/security/wss4j/SamlTokenInterceptor.java
rt/ws/security/src/main/java/org/apache/cxf/ws/security/wss4j/UsernameTokenInterceptor.java
rt/ws/security/src/main/java/org/apache/cxf/ws/security/wss4j/policyhandlers/AbstractBindingBuilder.java
rt/ws/security/src/main/java/org/apache/cxf/ws/security/wss4j/policyhandlers/AsymmetricBindingHandler.java
rt/ws/security/src/main/java/org/apache/cxf/ws/security/wss4j/policyhandlers/StaxAsymmetricBindingHandler.java
rt/ws/security/src/main/java/org/apache/cxf/ws/security/wss4j/policyhandlers/StaxSymmetricBindingHandler.java
rt/ws/security/src/main/java/org/apache/cxf/ws/security/wss4j/policyhandlers/TransportBindingHandler.java
rt/ws/security/src/main/java/org/apache/cxf/ws/security/wss4j/policyvalidators/AbstractSupportingTokenPolicyValidator.java
rt/ws/security/src/main/java/org/apache/cxf/ws/security/wss4j/policyvalidators/AlgorithmSuitePolicyValidator.java
rt/ws/security/src/main/java/org/apache/cxf/ws/security/wss4j/policyvalidators/AsymmetricBindingPolicyValidator.java
rt/ws/security/src/test/java/org/apache/cxf/ws/security/wss4j/StaxToDOMRoundTripTest.java
rt/ws/security/src/test/java/org/apache/cxf/ws/security/wss4j/saml/StaxToDOMSamlTest.java

https://www.viva64.com/en/m/0044/
The rest of report:
```
Low: V6008 [CWE-690] Potential null dereference of 'ai'. [cxf\rt\ws\security\src\main\java\org\apache\cxf\ws\security\wss4j\policyhandlers\AbstractBindingBuilder.java:374]
Low: V6008 [CWE-690] Potential null dereference of 'tok'. [cxf\rt\ws\security\src\main\java\org\apache\cxf\ws\security\policy\interceptors\SecureConversationInInterceptor.java:536]
Low: V6008 [CWE-690] Potential null dereference of 'origBinding'. [cxf\rt\ws\security\src\main\java\org\apache\cxf\ws\security\policy\interceptors\SecureConversationInInterceptor.java:196]
Medium: V6008 [CWE-690] Potential null dereference of 'secToken'. [cxf\rt\ws\security\src\main\java\org\apache\cxf\ws\security\wss4j\policyhandlers\AbstractStaxBindingHandler.java:219, …
```

cxf-rt-ws-security: fix PVS-Studio errors/warnings

---

core/src/main/java/org/apache/cxf/common/util/ClassHelper.java
core/src/main/java/org/apache/cxf/common/util/ClassUnwrapper.java
core/src/main/java/org/apache/cxf/common/util/SpringClassUnwrapper.java
core/src/test/java/org/apache/cxf/common/util/ClassHelperTest.java
integration/cdi/src/main/java/org/apache/cxf/cdi/CdiClassUnwrapper.java

This is a tricky one. So the `ClassUtils.isCglibProxyClass`, which is used by `SpringAopClassHelper`, does check if the class name has `$$` to disambiguate CGLIB proxies from regular classes. The typical examples of CGLIB proxy class names are:
```
SpringProxy$$EnhancerBySpringCGLIB$$d8e73a30
Function$$EnhancerByCGLIB$$53576dae
```
However, the classes generated for lambda expressions do contain `$$` as well, tricking `SpringAopClassHelper` to believe it is a CGLIB proxy, here is an example:
```
org.apache.cxf.common.util.ClassHelperTest$$Lambda$10/846254484@32b260fa
```
It turned out to be difficult to come up with efficient and bullet-proof check (based on class name only) to determine if it is CGLIB generated proxy or not. The cheapest but not 100% reliable way seems to be to check the …

CXF-8009: CXF should not rely on ClassUtils for CGLIB proxy checks

---

rt/rs/security/http-signature/src/main/java/org/apache/cxf/rs/security/httpsignature/filters/ClientDigestInterceptor.java
rt/rs/security/http-signature/src/main/java/org/apache/cxf/rs/security/httpsignature/filters/CreateDigestInterceptor.java
systests/rs-security/src/test/java/org/apache/cxf/systest/jaxrs/security/httpsignature/JAXRSHTTPSignatureTest.java

add client digest interceptor

---

rt/rs/security/http-signature/src/main/java/org/apache/cxf/rs/security/httpsignature/TomitribeSignatureValidator.java
rt/rs/security/http-signature/src/main/java/org/apache/cxf/rs/security/httpsignature/provider/KeyProvider.java
rt/rs/security/http-signature/src/main/java/org/apache/cxf/rs/security/httpsignature/provider/PrivateKeyProvider.java
rt/rs/security/http-signature/src/main/java/org/apache/cxf/rs/security/httpsignature/provider/PublicKeyProvider.java

We're looking into a scheme where the keys involved can be HMAC keys which are not asymmetrical - hence use simply an interface which resolves and uses Key instead of PublicKey.
@coheigea

add more generic interface which allows to use a sharedKey/Key

---

rt/rs/extensions/reactivestreams/src/main/java/org/apache/cxf/jaxrs/reactivestreams/server/StreamingAsyncSubscriber.java
rt/rs/extensions/reactor/src/main/java/org/apache/cxf/jaxrs/reactor/client/ReactorInvokerImpl.java
systests/jaxrs/pom.xml
systests/jaxrs/src/test/java/org/apache/cxf/systest/jaxrs/reactor/FluxReactorTest.java
systests/jaxrs/src/test/java/org/apache/cxf/systest/jaxrs/reactor/FluxService.java
systests/jaxrs/src/test/java/org/apache/cxf/systest/jaxrs/reactor/IllegalArgumentExceptionMapper.java
systests/jaxrs/src/test/java/org/apache/cxf/systest/jaxrs/reactor/ReactorServer.java

Indeed, there is an issue in case of error, opening the PR to get some feedback while working on the test cases. According to Reactive Streams spec (https://github.com/reactive-streams/reactive-streams-jvm), the `onError` is the terminal state:
> For a Publisher: When onComplete or onError has been signalled. For a Subscriber: When an onComplete   or onError has been received.
However, `StreamingAsyncSubscriber` does not treat it as that.
@coheigea @rmannibucau @davidkarlsen if you guys can validate my assumptions here, thanks.

CXF-8022: Thread hangs using Reactor Flux when Exception is Thrown

---

rt/frontend/jaxrs/src/main/java/org/apache/cxf/jaxrs/impl/ReaderInterceptorMBR.java
rt/frontend/jaxrs/src/main/java/org/apache/cxf/jaxrs/provider/ProviderFactory.java
rt/frontend/jaxrs/src/test/java/org/apache/cxf/jaxrs/impl/ReaderInterceptorMBRTest.java
rt/frontend/jaxrs/src/test/java/org/apache/cxf/jaxrs/provider/ProviderFactoryTest.java
systests/jaxrs/src/test/java/org/apache/cxf/systest/jaxrs/JAXRSClientServerBookTest.java

I observed that when reading an entity from a response of a failed rest call the CXF throws a NullPointer exception.
I tracked this down to specific case where a JAXRS ReaderInterceptor is present on the chain and the response fails. When parsing the response this condition triggers a different path in JAXRSUtils.readFromMessageBodyReader which eventually results in a call to ProviderFactory.createMessageBodyReaderInterceptor which will throw a NullPointerException when there is no inMessage.
This fix tries to load  an inFaultMessage if there is no inMessage available which prevents the NPE and allows the code to execute successfully.
To reproduce create a JAX-RS Proxy client with a ReaderInterceptor. Then trigger a request that returns a 403 status code and try to 'readEntity' on the …

If there is no inMessage use the inFaultMessage

---

rt/rs/security/oauth-parent/oauth2/src/main/java/org/apache/cxf/rs/security/oauth2/filters/JwtAccessTokenValidator.java

The token lifetime is incorrectly calculated to a negative value because claims expiry time is in second interval and code is setting issued at value in millisecond interval. Consequently causing token to expire.

JWT Token lifetime incorrectly calculated causing token to expire.

---

maven-plugins/java2wadl-plugin/pom.xml
maven-plugins/java2wadl-plugin/src/main/java/org/apache/cxf/maven_plugin/javatowadl/DumpJavaDoc.java
maven-plugins/java2wadl-plugin/src/main/java/org/apache/cxf/maven_plugin/javatowadl/Java2WADLMojo.java
maven-plugins/java2wadl-plugin/src/main/java13/org/apache/cxf/maven_plugin/javatowadl/DumpJavaDoc.java

The problem
===
Our `java2wadl` plugin uses some part of Javadoc API to extract the documentation pieces from the
Java classes / methods / parameters. Since OpenJDK13, this API has been removed completely [2], [3]. To support JDK13 and above, we essentially have to rewrite the implementation completely. However, we would face another blocker here: how to support JDK8-11 and JDK13+ at the same time?
The solution
===
Use multi-release JAR. This is exactly the use case this feature has been designed for. So what it means 
is that `java2wadl` has additional source folder `src/main/java13` with JDK13 implementation. It would be it however there is another subtle complication. 
The complication 
===
For multi-release JAR, the java2wadl has to be build with 2 JDKs (ideally), pre-JDK13 and JDK13, …

CXF-8066: Support Doclet API (JDK13+)

---

rt/rs/client/src/main/java/org/apache/cxf/jaxrs/client/ClientProxyImpl.java
rt/rs/microprofile-client/pom.xml
rt/rs/microprofile-client/src/main/java/org/apache/cxf/microprofile/client/MPRestClientCallback.java
rt/rs/microprofile-client/src/main/java/org/apache/cxf/microprofile/client/proxy/MicroProfileClientProxyImpl.java
rt/rs/microprofile-client/src/test/java/org/apache/cxf/microprofile/client/AsyncTest.java
rt/rs/microprofile-client/src/test/java/org/apache/cxf/microprofile/client/mock/AsyncClient.java

This fix ensures that we use the specified executor service to complete the CompletionStage from the MP Rest Client async methods. It also adds a test case based off of Manish Kumar's [reproducer example](https://gist.github.com/manish2aug/b4133b9fbedc2175e15b303a0682b552).
We may a similar change in OpenLiberty to handle this case, but I neglected to contribute that change back to CXF until now (apologies).

[CXF-8080] Ensure stages from async methods are completed

---

.gitignore
rt/frontend/jaxrs/src/main/java/org/apache/cxf/jaxrs/impl/UriBuilderImpl.java
rt/frontend/jaxrs/src/test/java/org/apache/cxf/jaxrs/impl/UriBuilderImplTest.java
rt/rs/client/src/main/java/org/apache/cxf/jaxrs/client/ClientProxyImpl.java
rt/rs/client/src/main/java/org/apache/cxf/jaxrs/client/ClientState.java
rt/rs/client/src/main/java/org/apache/cxf/jaxrs/client/JAXRSClientFactory.java
rt/rs/client/src/main/java/org/apache/cxf/jaxrs/client/JAXRSClientFactoryBean.java
rt/rs/client/src/main/java/org/apache/cxf/jaxrs/client/LocalClientState.java
rt/rs/client/src/main/java/org/apache/cxf/jaxrs/client/ThreadLocalClientState.java
rt/rs/client/src/main/java/org/apache/cxf/jaxrs/client/WebClient.java
rt/rs/client/src/main/java/org/apache/cxf/jaxrs/client/spec/ClientImpl.java
rt/rs/client/src/test/java/org/apache/cxf/jaxrs/client/spring/JAXRSClientFactoryBeanTest.java
rt/rs/client/src/test/java/org/apache/cxf/jaxrs/client/spring/clients.xml
rt/rs/microprofile-client/src/main/java/org/apache/cxf/microprofile/client/proxy/MicroProfileClientProxyImpl.java
systests/jaxrs/src/test/java/org/apache/cxf/systest/jaxrs/BookStore.java
systests/jaxrs/src/test/java/org/apache/cxf/systest/jaxrs/JAXRSClientServerQueryParamBookTest.java
systests/jaxrs/src/test/java/org/apache/cxf/systest/jaxrs/JAXRSClientServerQueryParamCollectionBookTest.java

The typical style the collection-like query parameters are encoded assumes the repetition of the parameter in question multiple times, for example:
http://localhost/books?ids=1&ids=2&ids=3&ids=4
However, as part of https://issues.apache.org/jira/browse/CXF-6941, the CXF server-side includes support for collection query parameters encoded as comma-separated strings, for example:
http://localhost/books?ids=1,2,3,4
This is quite useful in many cases however the CXF's client side does not anyhow support this encoding and always uses the repetition (`ids=1&ids=2&ids=3&ids=4`). This PRs complements the client-side feature set.
@coheigea @deki @andymc12 if you guys could take a look please, would appreciate the opinion, there are a few corner cases to cover but the idea in general seems to be …

CXF-8089: Build Comma Separated Values in url from Array/List Query Param

---

rt/features/logging/src/main/java/org/apache/cxf/ext/logging/event/DefaultLogEventMapper.java
rt/frontend/jaxws/src/test/java/org/apache/cxf/jaxws/logging/SOAPLoggingTest.java

Fill address in case of responses to be able to find out which URI does belong to the logged response.

CXF-8128: Fill address field in case of responses

---

systests/jaxrs/pom.xml
systests/jaxrs/src/test/java/org/apache/cxf/systest/jaxrs/metrics/Book.java
systests/jaxrs/src/test/java/org/apache/cxf/systest/jaxrs/metrics/JAXRSClientMetricsTest.java
systests/jaxrs/src/test/java/org/apache/cxf/systest/jaxrs/metrics/JAXRSServerMetricsTest.java
systests/jaxrs/src/test/java/org/apache/cxf/systest/jaxrs/metrics/Library.java
systests/jaxws/pom.xml
systests/jaxws/src/test/java/org/apache/cxf/systest/jaxws/metrics/BookWebService.java
systests/jaxws/src/test/java/org/apache/cxf/systest/jaxws/metrics/IBookWebService.java
systests/jaxws/src/test/java/org/apache/cxf/systest/jaxws/metrics/JAXWSClientMetricsTest.java
systests/jaxws/src/test/resources/org/apache/cxf/systest/jaxws/metrics/context.xml

For some reason the MetricsMessageInPostInvokeInterceptor interceptor is called twice, once for inbound message, and once for outbound message.

CXF-8124: CXF metrics - MetricsContext#stop called twice or without Fault in certain error cases

---

osgi/itests/pom.xml
osgi/karaf/features/src/main/resources/features.xml
parent/pom.xml

The following changes seems to fix the issues with Jackson 2.10.x update:
1. Removing `wrap` for Jackson JAX-RS modules. The `wrap` caused the issue with `bndlib` since Jackson 2.10.x introduces `module-info.class` / built with JDK9+. The exception in the logs:
```
java.lang.ArrayIndexOutOfBoundsException: 19
at aQute.bnd.osgi.Clazz.parseClassFile(Clazz.java:576)
at aQute.bnd.osgi.Clazz.parseClassFile(Clazz.java:494)
at aQute.bnd.osgi.Clazz.parseClassFileWithCollector(Clazz.java:483)
at aQute.bnd.osgi.Clazz.parseClassFile(Clazz.java:473)
at aQute.bnd.osgi.Analyzer.analyzeJar(Analyzer.java:2177)
at aQute.bnd.osgi.Analyzer.analyzeBundleClasspath(Analyzer.java:2083)
at aQute.bnd.osgi.Analyzer.analyze(Analyzer.java:138)
at aQute.bnd.osgi.Analyzer.calcManifest(Analyzer.java:616)
at …
```

CXF-8155: Update to Jackson 2.10.1

---

rt/frontend/jaxrs/src/main/java/org/apache/cxf/jaxrs/impl/NewCookieHeaderProvider.java
rt/frontend/jaxrs/src/test/java/org/apache/cxf/jaxrs/impl/NewCookieHeaderProviderTest.java
rt/frontend/jaxrs/src/test/java/org/apache/cxf/jaxrs/impl/ResponseImplTest.java

The RFC-6265 has the clarifications regarding empty cookie values, both in grammar  [1] and interpretation [2]. The approach adopted by other Java libraries (RESTEasy, Jersey, JDK11's HttpClient, ...) is to return an empty string as the value of the cookie.
[1] https://tools.ietf.org/html/rfc6265#section-4.1.1
[2] https://tools.ietf.org/html/rfc6265#section-5.2
@rmannibucau

CXF-8163: javax.ws.rs.core.Response#getCookies() fails when cookie has no value

---

rt/frontend/jaxrs/src/main/java/org/apache/cxf/jaxrs/impl/ResponseImpl.java
rt/frontend/jaxrs/src/test/java/org/apache/cxf/jaxrs/impl/ResponseImplTest.java

- if multiple, comma separated links are present in a single header, split up by comma and parse each.
- static final Pattern from open-liberty, see https://github.com/OpenLiberty/open-liberty/pull/8956/commits/e159898d1c9a230f5d71b82414874204a1a66715
Co-authored-by: Adam Anderson <atanderson9383@gmail.com>
Signed-off-by: Benjamin Marwell <bmarwell@gmail.com>

[CXF-8170] Parse HTTP link headers

---

rt/transports/jms/src/main/java/org/apache/cxf/transport/jms/JMSDestination.java
rt/transports/jms/src/main/java/org/apache/cxf/transport/jms/util/PollingMessageListenerContainer.java
rt/transports/jms/src/test/java/org/apache/cxf/transport/jms/JMSDestinationTest.java
rt/transports/jms/src/test/java/org/apache/cxf/transport/jms/util/MessageListenerTest.java

Solves problems of https://issues.apache.org/jira/browse/CXF-8161:
- JMSDestination#restartConnection() is synchronized: when multiple poller-threads run into exception handling, the restart will only run sequential. (otherwise there will be race conditions in restartConnection)
- JMSDestination#restartConnection() now checks if the PollingMessageListenerContainer is running before restart. When multiple poller-threads trigger the restart, it will only starts one new PollingMessageListenerContainer.
- PollingMessageListenerContainer stops the Executor after exception handling, resources will be released

[CXF-8161] fix memory leak and thread leak in JMSDestination

---

rt/frontend/jaxrs/src/main/java/org/apache/cxf/jaxrs/utils/JAXRSUtils.java
rt/frontend/jaxrs/src/test/java/org/apache/cxf/jaxrs/BaseApi.java
rt/frontend/jaxrs/src/test/java/org/apache/cxf/jaxrs/BaseRequest.java
rt/frontend/jaxrs/src/test/java/org/apache/cxf/jaxrs/BaseResponse.java
rt/frontend/jaxrs/src/test/java/org/apache/cxf/jaxrs/CustomerService.java
rt/frontend/jaxrs/src/test/java/org/apache/cxf/jaxrs/CustomerServiceRequest.java
rt/frontend/jaxrs/src/test/java/org/apache/cxf/jaxrs/CustomerServiceResource.java
rt/frontend/jaxrs/src/test/java/org/apache/cxf/jaxrs/CustomerServiceResponse.java
rt/frontend/jaxrs/src/test/java/org/apache/cxf/jaxrs/CustomizedApi.java
rt/frontend/jaxrs/src/test/java/org/apache/cxf/jaxrs/GenericService.java
rt/frontend/jaxrs/src/test/java/org/apache/cxf/jaxrs/SelectMethodCandidatesTest.java
rt/rs/description-openapi-v3/src/main/java/org/apache/cxf/jaxrs/openapi/OpenApiCustomizedResource.java
rt/rs/description-openapi-v3/src/main/java/org/apache/cxf/jaxrs/openapi/OpenApiFeature.java

Indeed, there was a side effect introduced by https://issues.apache.org/jira/browse/CXF-7946 where the argument classes are compared. The minor enhancements over this logic is to try to detect relations between parameter types (if any) and descend from subtypes to parent types.
@ffang could you please take a look? thanks!

CXF-8174: Incorrect service method resolution

---

rt/rs/microprofile-client/src/main/java/org/apache/cxf/microprofile/client/proxy/MicroProfileClientProxyImpl.java

if a service throws "ServerExecption" but ends up throwing a sub-class
of ServerException e.g. ValidationException, the ResponseExceptionMapper
resulting Exception is lost.
Additional information, Resteasy also does it this way:
https://github.com/resteasy/Resteasy/blob/cc424c27f0e9b5ccbc712fd114b7c9abb43e6ba5/resteasy-client-microprofile/src/main/java/org/jboss/resteasy/microprofile/client/ExceptionMapping.java

subclasses of declared exception should be thrown

---

.gitignore
rt/rs/microprofile-client/src/main/java/org/apache/cxf/microprofile/client/cdi/CDIFacade.java
rt/rs/microprofile-client/src/main/java/org/apache/cxf/microprofile/client/cdi/CDIInterceptorWrapper.java
rt/rs/microprofile-client/src/main/java/org/apache/cxf/microprofile/client/cdi/CDIUtils.java
rt/rs/microprofile-client/src/main/java/org/apache/cxf/microprofile/client/cdi/Instance.java
rt/rs/microprofile-client/src/main/java/org/apache/cxf/microprofile/client/proxy/MicroProfileClientProxyImpl.java
rt/rs/microprofile-client/src/test/java/org/apache/cxf/microprofile/client/cdi/RestClientCdiTest.java
systests/microprofile/client/jaxrs/src/test/java/org/apache/cxf/systest/microprofile/rest/client/InjectClientHeadersFactory.java
systests/microprofile/client/jaxrs/src/test/java/org/apache/cxf/systest/microprofile/rest/client/InjectRestClient.java
systests/microprofile/client/jaxrs/src/test/java/org/apache/cxf/systest/microprofile/rest/client/JaxrsHeaderPropagationTest.java
systests/microprofile/client/jaxrs/src/test/java/org/apache/cxf/systest/microprofile/rest/client/JaxrsResource.java
systests/microprofile/client/jaxrs/src/test/java/org/apache/cxf/systest/microprofile/rest/client/MockConfigProviderResolver.java

Implements [CXF-8188](https://issues.apache.org/jira/browse/CXF-8188) - injecting `@Context` and `@Inject` into custom `ClientHeadersFactory` implementations.  
This tests JAX-RS injection.  The MP Rest Client 2.0 TCK will test CDI injection.

CXF-8188: Inject into ClientHeadersFactory

---

core/src/main/java/org/apache/cxf/common/util/CollectionUtils.java
core/src/test/java/org/apache/cxf/common/util/CollectionUtilsTest.java
rt/frontend/jaxrs/src/main/java/org/apache/cxf/jaxrs/impl/UriBuilderImpl.java
rt/frontend/jaxrs/src/test/java/org/apache/cxf/jaxrs/impl/UriBuilderImplTest.java

This additional check enables path appends for file URIs to work as it has done in previous versions of CXF, for example, with this patch:
UriBuilder.fromUri("file:///~/calendar").path("extra").build() will return file:///~calendar/extra as opposed to file:///~/calendar.
This has been discussed on the mailing list here: https://mail-archives.apache.org/mod_mbox/cxf-dev/202001.mbox/%3cCAGRgoZhuKXoYW_JtxyDH=u7Qqqcbeo6-9BXa0dxB8L+iGB4J4g@mail.gmail.com%3e

CXF-8201 add additional check for file scheme in setUriParts

---

distribution/src/main/release/samples/jax_rs/tracing_brave/pom.xml
integration/tracing/tracing-brave/src/main/java/org/apache/cxf/tracing/brave/AbstractBraveClientProvider.java
parent/pom.xml

I believe there is an incompatibility between `cxf-integration-tracing-brave` and recent versions of `brave-instrumentation-http`.
CXF master currently depends on Brave version 5.6.9 while the newest version is 5.9.4.
As of version 5.7, `brave-instrumentation-http` throws a `NullPointerException` when invoking `brave.http.HttpClientHandler.create(HttpTracing, HttpClientAdapter)` with a `null` value for the `HttpClientAdapter` parameter.
Which is exactly what `cxf-integration-tracing-brave` does in case of an exception/SOAP fault.
This results in the following stack trace and hides the original SOAP fault from the user:
```
java.lang.NullPointerException: adapter == null
at brave.http.HttpClientHandler.create(HttpClientHandler.java:64)
at …
```

Incompatibility with recent Brave versions causes NullPointerException and hides root cause

---

rt/rs/description-swagger-ui/pom.xml
rt/rs/description-swagger-ui/src/main/java/org/apache/cxf/jaxrs/swagger/ui/SwaggerUiResourceLocator.java
rt/rs/description-swagger-ui/src/test/java/org/apache/cxf/jaxrs/swagger/ui/SwaggerUIResourceLocatorTest.java

CXF-8208 add exception handler so that failed swagger ui resource lookups don't fail the request completely with invalid uri errors.

Cxf 8208 - Handle exceptions when looking up swagger ui resources

---

rt/rs/sse/src/main/java/org/apache/cxf/jaxrs/sse/SseEventSinkContextProvider.java
rt/rs/sse/src/main/java/org/apache/cxf/jaxrs/sse/SseFeature.java
rt/rs/sse/src/main/java/org/apache/cxf/jaxrs/sse/interceptor/SseInterceptor.java
rt/rs/sse/src/main/java/org/apache/cxf/transport/sse/SseProvidersExtension.java
systests/rs-sse/rs-sse-base/src/main/java/org/apache/cxf/systest/jaxrs/sse/AbstractSseTest.java
systests/rs-sse/rs-sse-base/src/main/java/org/apache/cxf/systest/jaxrs/sse/BookStore.java
systests/rs-sse/rs-sse-base/src/main/java/org/apache/cxf/systest/jaxrs/sse/BookStore2.java
systests/rs-sse/rs-sse-base/src/main/java/org/apache/cxf/systest/jaxrs/sse/BookStoreResponseFilter.java
systests/rs-sse/rs-sse-base/src/main/java/org/apache/cxf/systest/jaxrs/sse/SseApplication.java
systests/rs-sse/rs-sse-jetty/src/test/java/org/apache/cxf/systest/jaxrs/sse/jetty/AbstractJettyServer.java
systests/rs-sse/rs-sse-tomcat/src/test/java/org/apache/cxf/systest/jaxrs/sse/tomcat/AbstractTomcatServer.java
systests/rs-sse/rs-sse-undertow/src/test/java/org/apache/cxf/systest/jaxrs/sse/undertow/AbstractUndertowServer.java

The JAX-RS Specification 2.1 contains the chapter 9 for "Server-Sent Events", specifically section 9.5 "Pipeline Processing" states:
> For compatibility purposes, implementations MUST initiate processing of an SSE response when either the first message is sent or when the resource method returns, whichever happens first. The initial SSE response, which may only include the HTTP headers, is processed using the standard JAX-RS pipeline as described in Appendix C. Each subsequent SSE event may include a different payload and thus require the use of a specific message body writer. Note that since this use case differs slightly from the normal JAX-RS pipeline, implementations SHOULD NOT call entity interceptors on each individual event (1).
In case of CXF SSE processing, the …

CXF-8215: SSE breaks Pipeline Processing

---

rt/features/logging/src/main/java/org/apache/cxf/ext/logging/slf4j/Slf4jEventSender.java

By extracting code into subroutines it is easier to override parts e.g. to make used Logger dependent of called method

[CXF-8225] Structure send method of Slf4jEventSender

---

rt/frontend/jaxrs/src/main/java/org/apache/cxf/jaxrs/impl/AsyncResponseImpl.java
rt/frontend/jaxrs/src/test/java/org/apache/cxf/jaxrs/impl/AsyncResponseImplTest.java

instead of throwing a NullPointerException

CXF-8235 Handle null continuation in AsyncResponseImpl

---

core/src/main/java/org/apache/cxf/interceptor/security/AbstractAuthorizingInInterceptor.java
core/src/main/java/org/apache/cxf/message/MessageUtils.java
core/src/main/java/org/apache/cxf/validation/AbstractValidationInterceptor.java
core/src/test/java/org/apache/cxf/message/MessageUtilsTest.java
rt/frontend/jaxrs/src/main/java/org/apache/cxf/jaxrs/provider/JAXRSDataBinding.java
rt/security/src/main/java/org/apache/cxf/rt/security/claims/interceptor/ClaimsAuthorizingInterceptor.java

I was looking at getting the target method in a new interceptor and realized that there are a few different places in the code that is essentially doing the same thing.  So I thought it would be better for maintenance to consolidate that function in one place.
Feedback appreciated.  If nobody objects, I'd like to back port this to 3.3.x too.
Thanks!

Consolidate getTargetMethod calls

---

core/src/main/java/org/apache/cxf/endpoint/ClientCallback.java
core/src/test/java/org/apache/cxf/endpoint/ClientCallbackTest.java
rt/frontend/jaxws/src/main/java/org/apache/cxf/jaxws/JaxwsClientCallback.java
rt/frontend/jaxws/src/test/java/org/apache/cxf/jaxws/JaxwsClientCallbackTest.java
rt/rs/client/src/main/java/org/apache/cxf/jaxrs/client/JaxrsClientCallback.java
rt/rs/client/src/test/java/org/apache/cxf/jaxrs/client/JaxrsClientCallbackTest.java
rt/rs/microprofile-client/src/main/java/org/apache/cxf/microprofile/client/MPRestClientCallback.java
rt/rs/microprofile-client/src/test/java/org/apache/cxf/microprofile/client/MPRestClientCallbackTest.java

Replacing CXF's future implementation with Java 8 `CompletableFuture` delegate.

CXF-8242: Stop blocking executor thread on microprofile rest asynchronous call

---

rt/rs/security/oauth-parent/oauth2/src/main/java/org/apache/cxf/rs/security/oauth2/services/ClientRegistrationResponse.java

Here is a small fix for the issue I've come across. A wrong constant/field name was used in the `ClientRegistrationResponse` class.

Client registration response field 'client_secret_expires_at' is always null

---

rt/rs/client/src/main/java/org/apache/cxf/jaxrs/client/AbstractClient.java
rt/rs/client/src/main/java/org/apache/cxf/jaxrs/client/spec/ClientResponseFilterInterceptor.java
rt/rs/client/src/test/java/org/apache/cxf/jaxrs/client/spec/ClientResponseFilterTest.java

Section 4.5.2 of the JAX-RS 2.1 specification:
> When a provider method throws an exception, the JAX-RS client runtime will map it to an instance of ProcessingException if thrown while processing a request, and to a ResponseProcessingException if thrown while processing a response.

CXF-8261: Exceptions being thrown in a ClientResponseFilter are ignored

---

rt/transports/http-hc/src/main/java/org/apache/cxf/transport/http/asyncclient/AsyncHTTPConduit.java

Fixing https://issues.apache.org/jira/browse/CXF-8270 to support SSL persistent connections for more than one endpoints at the same server.

CXF-8270 - fix SSL persistent connection

---

rt/rs/client/src/main/java/org/apache/cxf/jaxrs/client/AbstractClient.java
rt/rs/client/src/test/java/org/apache/cxf/jaxrs/client/spec/ClientResponseFilterTest.java
systests/jaxrs/src/test/java/org/apache/cxf/systest/jaxrs/BookServer20.java
systests/jaxrs/src/test/java/org/apache/cxf/systest/jaxrs/JAXRS20ClientServerBookTest.java
systests/jaxrs/src/test/java/org/apache/cxf/systest/jaxrs/JAXRSAsyncClientTest.java

The CXF's async JAX-RS client never completes the response in case of an exception during the interceptor chain processing.

CXF-8271: The async JAX-RS client never completes the response in case of an exception during the interceptor chain processing.

---

rt/rs/security/oauth-parent/oauth2/src/main/java/org/apache/cxf/rs/security/oauth2/utils/OAuthUtils.java

In case of using some of overloaded `org.apache.cxf.rs.security.oauth2.utils.OAuthUtils#setSessionToken` methods with a custom `maxInactiveInterval` the actual value will be ignored.

Specify proper inactive interval for a session token

---

parent/pom.xml

Upgrade guava to avoid being marked for CVE-2018-10237 - although CXF might not directly be affected by the issue.
Signed-off-by: David Karlsen <david@davidkarlsen.com>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/apache/cxf/638)

upgrade guava, CVE-2018-10237

---

rt/transports/http-netty/netty-client/src/main/java/org/apache/cxf/transport/http/netty/client/CxfResponseCallBack.java
rt/transports/http-netty/netty-client/src/main/java/org/apache/cxf/transport/http/netty/client/NettyHttpClientHandler.java
rt/transports/http-netty/netty-client/src/main/java/org/apache/cxf/transport/http/netty/client/NettyHttpClientPipelineFactory.java
rt/transports/http-netty/netty-client/src/main/java/org/apache/cxf/transport/http/netty/client/NettyHttpConduit.java
rt/transports/http-netty/netty-client/src/test/java/org/apache/cxf/transport/http/netty/client/NettyHttpConduitTest.java

In case of asynchronous invocation, the receive / read timeout (implemented using `Object.wait()` / `Object.notifyAll()`) does not trigger. One of the solutions is to fallback to Netty's `ReadTimeoutHandler`.

CXF-8282: Set read timeout using netty client

---

rt/features/clustering/src/main/java/org/apache/cxf/clustering/AbstractStaticFailoverStrategy.java
systests/jaxrs/src/test/java/org/apache/cxf/systest/jaxrs/failover/FailoverWebClientTest.java

AbstractStaticFailoverStrategy.getEndpoints() never returns anything for JAX-RS clients (with RetryStrategy)

CXF-8286: AbstractStaticFailoverStrategy.getEndpoints() never returns anything for JAX-RS clients (with RetryStrategy)

---

parent/pom.xml
rt/rs/microprofile-client/src/main/java/org/apache/cxf/microprofile/client/CxfTypeSafeClientBuilder.java
rt/rs/microprofile-client/src/main/java/org/apache/cxf/microprofile/client/MicroProfileClientFactoryBean.java
rt/rs/microprofile-client/src/main/java/org/apache/cxf/microprofile/client/cdi/RestClientBean.java
rt/rs/microprofile-client/src/test/java/org/apache/cxf/microprofile/client/CxfTypeSafeClientBuilderTest.java
rt/transports/http/src/main/java/org/apache/cxf/transport/http/HTTPConduit.java

This PR covers two JIRAs [CXF-8294](https://issues.apache.org/jira/browse/CXF-8294) and [CXF-8295](https://issues.apache.org/jira/browse/CXF-8295) - proxy server support and auto follow redirect support.  Both of these features already exist in the CXF client, but now are made part of the MicroProfile Rest Client API.  This PR maps the MP API to the existing CXF properties.
On a related note, I have added a separate commit that will auto-redirect on 308 responses too.   Per [MDN](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/308), 308s are a permanent redirect - and the Jakarta JAX-RS community is planning to include official support for it in a future spec release (3.1, I think...).  This is not strictly required in order to implement the MP spec, but I thought it would make a …

[CXF-8294][CXF-8295] Proxy and followRedirect APIs for MicroProfile Rest Client 2.0

---

rt/frontend/jaxrs/src/main/java/org/apache/cxf/jaxrs/utils/InjectionUtils.java
rt/frontend/jaxrs/src/test/java/org/apache/cxf/jaxrs/Customer.java
rt/frontend/jaxrs/src/test/java/org/apache/cxf/jaxrs/utils/JAXRSUtilsTest.java

The general issue is with the way CXF handles `null` parameter values injection, it does not actually distinguish if the converter was applied and returned `null`, or the result is just `null` for any reason (no converter found fe).

CXF-8296: Custom Boolean ParamConverter wrong behaviour

---

parent/pom.xml
rt/frontend/jaxrs/src/main/java/org/apache/cxf/jaxrs/impl/UriBuilderImpl.java
rt/frontend/jaxrs/src/test/java/org/apache/cxf/jaxrs/impl/UriBuilderImplTest.java
rt/rs/microprofile-client/src/main/java/org/apache/cxf/microprofile/client/CxfTypeSafeClientBuilder.java
rt/rs/microprofile-client/src/main/java/org/apache/cxf/microprofile/client/MicroProfileClientConfigurableImpl.java
rt/rs/microprofile-client/src/main/java/org/apache/cxf/microprofile/client/MicroProfileClientFactoryBean.java
rt/rs/microprofile-client/src/main/java/org/apache/cxf/microprofile/client/cdi/CDIFacade.java
rt/rs/microprofile-client/src/main/java/org/apache/cxf/microprofile/client/cdi/CDIInstantiator.java
rt/rs/microprofile-client/src/main/java/org/apache/cxf/microprofile/client/cdi/RestClientBean.java
rt/rs/microprofile-client/src/main/java/org/apache/cxf/microprofile/client/proxy/MicroProfileClientProxyImpl.java

This PR fixes [CXF-8299](https://issues.apache.org/jira/browse/CXF-8299) (QueryParamStyles) and [CXF-8304](https://issues.apache.org/jira/browse/CXF-8304) (CDI-managed providers), and supersedes PR #678. 
For 8299, this allows the client to specify how collections should be handle when using query parameters - i.e. expanded, expanded with array syntax (required for PHP servers), or with a single key but comma-separated values.
For 8304, this changes the way providers are instantiated. If CDI is managing an instance of the provider class, then the client implementation should use that instance rather than creating a new instance.  This should only apply in cases where the interface registers the provider _class_, and not cases where it registers an _instance_ of the provider.

[CXF-8299][CXF-8304] QueryParamStyles and CDI-managed providers for MP Rest Client 2.0

---

rt/rs/microprofile-client/src/main/java/org/apache/cxf/microprofile/client/MPRestClientCallback.java
rt/rs/microprofile-client/src/main/java/org/apache/cxf/microprofile/client/MicroProfileClientFactoryBean.java
rt/rs/microprofile-client/src/main/java/org/apache/cxf/microprofile/client/Utils.java
rt/rs/microprofile-client/src/main/java/org/apache/cxf/microprofile/client/proxy/MicroProfileClientProxyImpl.java
systests/microprofile/client/async/pom.xml
systests/microprofile/client/async/src/test/java/org/apache/cxf/systest/microprofile/rest/client/AsyncThreadingTest.java

1. Aligning MP Client implementation to use only one executor service, configured through `MicroProfileClientFactoryBean` and propagated via contextual property `EXECUTOR_SERVICE_PROPERTY`
2. Always initialize executor service in the `MicroProfileClientFactoryBean`, using `ForkJoin` pool as default if not specified
3. Removed async delegation from `MPRestClientCallback::createFuture` since it is always executed in the context of executor service (configured through `MicroProfileClientFactoryBean`)

CXF-8303: MP: Context propagation impossible using AsyncInvocationInterceptorFactory

---

core/src/main/java/org/apache/cxf/attachment/AttachmentDeserializer.java
core/src/main/java/org/apache/cxf/attachment/AttachmentUtil.java
core/src/test/java/org/apache/cxf/attachment/AttachmentUtilTest.java

Provide better error if the given value is not allowed
Document allowed values for properties
I also had to do some special handling if someone provides a BigInteger which has a larger value than `Long.MAX_VALUE`.

CXF-8324: Allow wider range of values for attachment properties

---

rt/rs/security/jose-parent/jose/src/main/java/org/apache/cxf/rs/security/jose/jwe/JweJsonConsumer.java

I'm using cxf-rt-rs-security-jose's JweJsonConsumer to parse a Json JWE (that I just created and encrypted using JweJsonProducer).
I'm doing this because I need to pass its components (headers, kid, iv, aad, ciphertext, auth tag, ...) to another API individually (the API does not accept the full JsonJWE).
Currently however, only getAad(), getAadText() and some getters for the headers are available. There's no getIv(), getCipherText(), etc
This pull request add the missing getters

[CXF-8338] Add missing getters to JweJsonConsumer

---

core/src/main/java/org/apache/cxf/interceptor/ServiceInvokerInterceptor.java
core/src/main/java/org/apache/cxf/message/MessageImpl.java
core/src/main/java/org/apache/cxf/message/StringMapImpl.java

Hi All,
While trying to consume the new 3.4.0 release into Open Liberty, we noticed that we had made a number of changes that has effectively forked Open Liberty's implementation of CXF.  We'd like to contribute those back to Apache as much as possible.
This PR includes some of the changes that are easy to "disentangle" and include some fixes we needed to make in order to pass some JAX-RS TCK tests, improve performance (the change to MessageImpl in particular made a large difference by avoiding resizing the underlying data store), etc.
Unfortunately, many of our forked classes contains references to Open Liberty-specific code, so we'll need to sort those out before we can contribute them back.  One thing we did in this PR to was to add an extension point (the new `RunnableWrapperFactory` …

[CXF-8345] Improve performance by avoiding resize of MessageImpl

---

rt/frontend/jaxrs/src/main/java/org/apache/cxf/jaxrs/impl/ContainerRequestContextImpl.java
rt/frontend/jaxrs/src/main/java/org/apache/cxf/jaxrs/impl/ResponseImpl.java
rt/frontend/jaxrs/src/test/java/org/apache/cxf/jaxrs/impl/ResponseImplTest.java

Fixes various "hasEntity" TCK tests where the entityStream is non-null, but empty.  Also fixes an issue with `ContainerRequestContext.setRequestUri(...)` methods.
Resolves [CXF-8346](https://issues.apache.org/jira/browse/CXF-8346).

[CXF-8346] TCK Changes for URI and hasEntity checks

---

rt/frontend/jaxrs/src/main/java/org/apache/cxf/jaxrs/impl/ContainerRequestContextImpl.java
systests/cdi/base/src/main/java/org/apache/cxf/systests/cdi/base/AbstractCdiMultiAppTest.java
systests/jaxrs/src/test/java/org/apache/cxf/systest/jaxrs/BookServer20.java
systests/jaxrs/src/test/java/org/apache/cxf/systest/jaxrs/JAXRSClientServerBookTest.java
systests/rs-security/src/test/java/org/apache/cxf/systest/jaxrs/security/oidc/OIDCNegativeTest.java

This should resolve 4 errors/failures in systests that resulted from runtime changes in CXF-8346 / PR #697.  
The first change is to remove query parameters.  These should need to be "replaced" as the query parameter was specified on the original request.  By replacing them, it actually appended them, making the request URI look something like: `http://localhost:8080/bookstore/books/check2?a=b?a=b` which is not allowed (the extra question mark).
The other changes were to re-acquire the Response object rather than just re-using them.  This was a clear test bug, since it was previously checking the response from the first request twice rather than checking the response from both requests.
This should resolve 8 failures in the master builds since these 4 tests are run twice (once for Java 8 …

Fix systests to account for fix in CXF-8346

---

tools/wsdlto/frontend/jaxws/src/main/java/org/apache/cxf/tools/wsdlto/frontend/jaxws/template/fault.vm
tools/wsdlto/test/src/test/java/org/apache/cxf/tools/wsdlto/jaxws/CodeGenBugTest.java

wsdl2java generates wrapper exception class for fault bean. The generated exception has method getFaultInfo(). This method name is correct according to JAX-WS specification. However this method returns fault bean stored in a field called "name of fault bean". The name of the field and getter do not follow the naming convention. 
In general, it does not cause issue unless such fault beans becomes serialization / deserialization targets (the absence of the setter method `setFaultInfo`  makes the matter difficult).
@coheigea @dkulp may I ask you please to take a look? thanks!

CXF-8337: wsdl2java generates exceptions fields which do not follow naming convention

---

core/src/main/java/org/apache/cxf/common/logging/LogUtils.java

I'm not sure how I could test this fix, because it would require alternating between different SLF4J bindings to make sure we always get the correct logger implementation. This means we would need a different classpath for each test, and SLF4J would need to be reinitialized from scratch.

CXF-8354: removed remaining references to old Log4jLogger

---

rt/rs/extensions/reactivestreams/src/main/java/org/apache/cxf/jaxrs/reactivestreams/server/ResponseStatusOnlyException.java
rt/rs/extensions/reactivestreams/src/main/java/org/apache/cxf/jaxrs/reactivestreams/server/ResponseStatusOnlyExceptionMapper.java
rt/rs/extensions/reactivestreams/src/main/java/org/apache/cxf/jaxrs/reactivestreams/server/StreamingAsyncSubscriber.java
rt/rs/extensions/reactor/src/main/java/org/apache/cxf/jaxrs/reactor/server/ReactorCustomizer.java
rt/rs/extensions/reactor/src/main/java/org/apache/cxf/jaxrs/reactor/server/ReactorInvoker.java
systests/jaxrs/src/test/java/org/apache/cxf/systest/jaxrs/reactor/FluxReactorTest.java
systests/jaxrs/src/test/java/org/apache/cxf/systest/jaxrs/reactor/FluxService.java
systests/jaxrs/src/test/java/org/apache/cxf/systest/jaxrs/reactor/IllegalStateExceptionMapper.java
systests/jaxrs/src/test/java/org/apache/cxf/systest/jaxrs/reactor/MonoReactorTest.java
systests/jaxrs/src/test/java/org/apache/cxf/systest/jaxrs/reactor/MonoService.java
systests/jaxrs/src/test/java/org/apache/cxf/systest/jaxrs/reactor/ReactorServer.java

Fixing the following cases:
- handling `Mono.empty()`
- handling `Flux.empty()` in case of no streaming
- fixing mixed response issue by  `ResponseStatusOnlyException`
- more test cases

CXF-8349: Flux Returns Mixed Response on Errors and Mono Hangs when Empty

---

rt/frontend/jaxrs/src/main/java/org/apache/cxf/jaxrs/impl/MediaTypeHeaderProvider.java
rt/frontend/jaxrs/src/test/java/org/apache/cxf/jaxrs/impl/MediaTypeHeaderProviderTest.java

Performs validation on the type and subtype of the MediaType string passed-in according to https://tools.ietf.org/html/rfc2045#section-5.1

[CXF-8353] MediaType validation

---

rt/rs/extensions/rx3/src/main/java/org/apache/cxf/jaxrs/rx3/server/ReactiveIOCustomizer.java
rt/rs/extensions/rx3/src/main/java/org/apache/cxf/jaxrs/rx3/server/ReactiveIOInvoker.java
systests/jaxrs/src/test/java/org/apache/cxf/systest/jaxrs/reactive/IllegalArgumentExceptionMapper.java
systests/jaxrs/src/test/java/org/apache/cxf/systest/jaxrs/reactive/IllegalStateExceptionMapper.java
systests/jaxrs/src/test/java/org/apache/cxf/systest/jaxrs/reactive/JAXRSRxJava3FlowableTest.java
systests/jaxrs/src/test/java/org/apache/cxf/systest/jaxrs/reactive/JAXRSRxJava3ObservableTest.java
systests/jaxrs/src/test/java/org/apache/cxf/systest/jaxrs/reactive/JAXRSRxJava3SingleTest.java
systests/jaxrs/src/test/java/org/apache/cxf/systest/jaxrs/reactive/RxJava3FlowableService.java
systests/jaxrs/src/test/java/org/apache/cxf/systest/jaxrs/reactive/RxJava3ObservableServer.java
systests/jaxrs/src/test/java/org/apache/cxf/systest/jaxrs/reactive/RxJava3ObservableService.java
systests/jaxrs/src/test/java/org/apache/cxf/systest/jaxrs/reactive/RxJava3SingleServer.java
systests/jaxrs/src/test/java/org/apache/cxf/systest/jaxrs/reactive/RxJava3SingleService.java

Fixing the following cases:
- handling `Observable.empty()`
- handling `Flowable.empty()`
- handling `Flowable.empty()` in case of no streaming
- fixing mixed response issue by `ResponseStatusOnlyException`
- more test cases (including `Single`)

CXF-8355: RxJava3: Observable / Flowable Returns Mixed Response on Errors and Hangs when Empty

---

rt/rs/extensions/rx2/src/main/java/org/apache/cxf/jaxrs/rx2/server/ReactiveIOCustomizer.java
rt/rs/extensions/rx2/src/main/java/org/apache/cxf/jaxrs/rx2/server/ReactiveIOInvoker.java
systests/jaxrs/src/test/java/org/apache/cxf/systest/jaxrs/reactive/JAXRSRxJava2FlowableTest.java
systests/jaxrs/src/test/java/org/apache/cxf/systest/jaxrs/reactive/JAXRSRxJava2ObservableTest.java
systests/jaxrs/src/test/java/org/apache/cxf/systest/jaxrs/reactive/JAXRSRxJava2SingleTest.java
systests/jaxrs/src/test/java/org/apache/cxf/systest/jaxrs/reactive/RxJava2FlowableServer.java
systests/jaxrs/src/test/java/org/apache/cxf/systest/jaxrs/reactive/RxJava2FlowableService.java
systests/jaxrs/src/test/java/org/apache/cxf/systest/jaxrs/reactive/RxJava2ObservableService.java
systests/jaxrs/src/test/java/org/apache/cxf/systest/jaxrs/reactive/RxJava2SingleServer.java
systests/jaxrs/src/test/java/org/apache/cxf/systest/jaxrs/reactive/RxJava2SingleService.java

Fixing the following cases:
- handling `Observable.empty()`
- handling `Flowable.empty()`
- handling `Flowable.empty()` in case of no streaming
- fixing mixed response issue by `ResponseStatusOnlyException`
- more test cases (including `Single`)

CXF-8358: RxJava2: Observable / Flowable Returns Mixed Response on Errors and Hangs when Empty

---

rt/rs/microprofile-client/src/main/java/org/apache/cxf/microprofile/client/MicroProfileClientProviderFactory.java

Moves classloading of MP Rest Client 1.1 APIs to static block to avoid class loads from within loop.

Reduce classloading on Rest Client init

---

distribution/src/main/release/samples/jax_rs/spring_boot/README
distribution/src/main/release/samples/jax_rs/spring_boot/pom.xml
distribution/src/main/release/samples/jax_rs/spring_boot/src/main/java/sample/rs/service/SampleRestApplication.java
distribution/src/main/release/samples/jax_rs/spring_boot/src/main/resources/application.properties
integration/spring-boot/autoconfigure/pom.xml
integration/spring-boot/autoconfigure/src/main/java/org/apache/cxf/spring/boot/autoconfigure/CxfProperties.java
integration/spring-boot/autoconfigure/src/main/java/org/apache/cxf/spring/boot/autoconfigure/micrometer/MicrometerMetricsAutoConfiguration.java
integration/spring-boot/autoconfigure/src/main/java/org/apache/cxf/spring/boot/autoconfigure/micrometer/provider/SpringBasedTimedAnnotationProvider.java
integration/spring-boot/autoconfigure/src/test/java/org/apache/cxf/spring/boot/autoconfigure/micrometer/MicrometerMetricsAutoConfigurationTest.java
rt/features/metrics/src/main/java/org/apache/cxf/metrics/micrometer/MicrometerMetricsProperties.java
rt/features/metrics/src/main/java/org/apache/cxf/metrics/micrometer/MicrometerMetricsProvider.java
rt/features/metrics/src/main/java/org/apache/cxf/metrics/micrometer/provider/DefaultTimedAnnotationProvider.java
rt/features/metrics/src/main/java/org/apache/cxf/metrics/micrometer/provider/StandardTags.java
rt/features/metrics/src/main/java/org/apache/cxf/metrics/micrometer/provider/jaxrs/JaxrsOperationTagsCustomizer.java
rt/features/metrics/src/main/java/org/apache/cxf/metrics/micrometer/provider/jaxrs/JaxrsTags.java
rt/features/metrics/src/test/java/org/apache/cxf/metrics/micrometer/MicrometerMetricsProviderTest.java
rt/features/metrics/src/test/java/org/apache/cxf/metrics/micrometer/provider/DefaultExceptionClassProviderTest.java
rt/features/metrics/src/test/java/org/apache/cxf/metrics/micrometer/provider/DefaultTimedAnnotationProviderTest.java
rt/features/metrics/src/test/java/org/apache/cxf/metrics/micrometer/provider/StandardTagsProviderTest.java
rt/features/metrics/src/test/java/org/apache/cxf/metrics/micrometer/provider/StandardTagsTest.java
rt/features/metrics/src/test/java/org/apache/cxf/metrics/micrometer/provider/jaxrs/JaxrsOperationTagsCustomizerTest.java
rt/features/metrics/src/test/java/org/apache/cxf/metrics/micrometer/provider/jaxrs/JaxrsTagsTest.java
systests/spring-boot/src/test/java/org/apache/cxf/systest/jaxrs/resources/Library.java
systests/spring-boot/src/test/java/org/apache/cxf/systest/jaxrs/spring/boot/SpringJaxrsTest.java
systests/spring-boot/src/test/resources/application-jaxrs.yml
systests/spring-boot/src/test/resources/application-jaxws.yml

@shark300 fyi, there are a few changes but they should not impact the JAX-WS integration anyhow (expect `uri` tag which is using the `REQUEST_URI` instead of `BASE_PATH`)

CXF-8252: Add Micrometer metric support for JAX-RS (Spring Boot)

---

rt/transports/udp/src/main/java/org/apache/cxf/transport/udp/UDPDestination.java
rt/transports/udp/src/test/java/org/apache/cxf/transport/udp/UDPTransportTest.java
services/ws-discovery/ws-discovery-api/src/test/java/org/apache/cxf/ws/discovery/WSDiscoveryClientTest.java

Guard against null return value from `java.net.NetworkInterface.getNetworkInterfaces()`.

Guard against null NetworkInterface.getNetworkInterfaces()

---

core/src/main/java/org/apache/cxf/message/MessageUtils.java
rt/features/metrics/src/main/java/org/apache/cxf/metrics/micrometer/provider/StandardTags.java
rt/features/metrics/src/main/java/org/apache/cxf/metrics/micrometer/provider/jaxws/JaxwsFaultCodeProvider.java
rt/features/metrics/src/test/java/org/apache/cxf/metrics/micrometer/provider/StandardTagsTest.java
rt/features/metrics/src/test/java/org/apache/cxf/metrics/micrometer/provider/jaxws/JaxwsFaultCodeProviderTest.java
rt/transports/http/src/main/java/org/apache/cxf/transport/http/AbstractHTTPDestination.java

Reusing the logic from `AbstractHTTPDestination` to come up with the response status code if it is not set.

CXF-8367: Micrometer always reports outcome=UNKNOWN on success cases

---

rt/frontend/jaxws/src/main/java/org/apache/cxf/jaxws/handler/AnnotationHandlerChainBuilder.java
rt/frontend/jaxws/src/main/java/org/apache/cxf/jaxws/handler/Messages.properties
rt/frontend/jaxws/src/test/java/org/apache/cxf/jaxws/handler/JakartaAnnotationHandlerChainBuilderTest.java
rt/frontend/jaxws/src/test/java/org/apache/cxf/jaxws/handler/JavaxAnnotationHandlerChainBuilderTest.java
rt/frontend/jaxws/src/test/java/org/apache/cxf/jaxws/handler/jakarta-handlers.xml
rt/frontend/jaxws/src/test/java/org/apache/cxf/jaxws/handler/javax-handlers.xml

Fixes https://issues.apache.org/jira/browse/CXF-8361

[CXF-8361] Added support for jakarta NS in AnnotationHandlerChainBuilder

---

parent/pom.xml
systests/jaxrs/src/test/java/org/apache/cxf/systest/jaxrs/security/BookLoginModule.java
systests/jaxrs/src/test/java/org/apache/cxf/systest/jaxrs/security/BookLoginService.java
systests/jaxrs/src/test/resources/jaxrs_jaas_security/WEB-INF/beans.xml

The change in PropertyFileLoginModule  caused tests to fail (dependency on thread-local static `JAASLoginService.INSTANCE` has been introduced), see please https://github.com/eclipse/jetty.project/issues/5486

Update to Jetty 9.4.35.v20201120

---

core/src/main/java/org/apache/cxf/interceptor/FIStaxInInterceptor.java
core/src/main/java/org/apache/cxf/interceptor/FIStaxOutInterceptor.java

Applies the changes discussed in [CXF-8411](https://issues.apache.org/jira/browse/CXF-8411).

CXF-8411: Improve FastInfoset interceptors' compatibility with GraalVM native compilation

---

core/src/main/java/org/apache/cxf/catalog/OASISCatalogManager.java
core/src/main/java/org/apache/cxf/resource/URIResolver.java
core/src/main/java/org/apache/cxf/service/factory/AbstractServiceFactoryBean.java
distribution/src/main/release/samples/jax_rs/basic/src/main/java/demo/jaxrs/client/Client.java
rt/databinding/jaxb/src/main/java/org/apache/cxf/jaxb/JAXBDataBinding.java
rt/frontend/simple/src/main/java/org/apache/cxf/endpoint/dynamic/DynamicClientFactory.java
tools/validator/src/main/java/org/apache/cxf/tools/validator/internal/SchemaValidator.java
tools/wadlto/jaxrs/src/main/java/org/apache/cxf/tools/wadlto/jaxb/CustomizationParser.java
tools/wsdlto/databinding/jaxb/src/main/java/org/apache/cxf/tools/wsdlto/databinding/jaxb/JAXBDataBinding.java
tools/wsdlto/frontend/jaxws/src/main/java/org/apache/cxf/tools/wsdlto/frontend/jaxws/JAXWSContainer.java
tools/wsdlto/frontend/jaxws/src/main/java/org/apache/cxf/tools/wsdlto/frontend/jaxws/customization/CustomizationParser.java

Multiple input stream leaks where `URIResolver` is used. Marked `URIResolver`  as `AutoCloseable` and refactored its usage to `try-with-resources` in most places.

CXF-8422: Unclosed input streams after using org.apache.cxf.tools.wsdlto.WSDLToJava

---

core/src/main/java/org/apache/cxf/staxutils/AutoCloseableXMLStreamReader.java
core/src/main/java/org/apache/cxf/staxutils/StaxUtils.java
rt/ws/security/src/main/java/org/apache/cxf/ws/security/wss4j/StaxSerializer.java

```
/**
*<p>
* Note: as per StAX 1.0 specs, this method does NOT close the underlying
* input reader. That is, unless the new StAX2 property
* {@link org.codehaus.stax2.XMLInputFactory2#P_AUTO_CLOSE_INPUT} is
* set to true.
*/
@Override
public void close() throws XMLStreamException 
```
Introduced new system property:
- `org.apache.cxf.staxutils.autoCloseInputSource`, by default is `false` (preserving the current behavior)
- when set, the stream behind `InputSource` is going to be closed along with `XMLStreamReader`

CXF-8422: Unclosed input streams after using org.apache.cxf.tools.wsdlto.WSDLToJava (targeting StAX's XMLStreamReader)

---

rt/frontend/jaxws/src/main/java/org/apache/cxf/jaxws/handler/AnnotationHandlerChainBuilder.java
rt/frontend/jaxws/src/main/java/org/apache/cxf/jaxws/handler/BaseHandlerChainBuilder.java
rt/frontend/jaxws/src/main/java/org/apache/cxf/jaxws/handler/JakartaeeHandlerChainBuilder.java
rt/frontend/jaxws/src/main/java/org/apache/cxf/jaxws/handler/JakartaeeToJavaeeAdaptor.java
rt/frontend/jaxws/src/main/java/org/apache/cxf/jaxws/handler/JavaeeHandlerChainBuilder.java
rt/frontend/jaxws/src/main/java/org/apache/cxf/jaxws/handler/jakartaee/CString.java
rt/frontend/jaxws/src/main/java/org/apache/cxf/jaxws/handler/jakartaee/DescriptionType.java
rt/frontend/jaxws/src/main/java/org/apache/cxf/jaxws/handler/jakartaee/DisplayNameType.java
rt/frontend/jaxws/src/main/java/org/apache/cxf/jaxws/handler/jakartaee/FullyQualifiedClassType.java
rt/frontend/jaxws/src/main/java/org/apache/cxf/jaxws/handler/jakartaee/IconType.java
rt/frontend/jaxws/src/main/java/org/apache/cxf/jaxws/handler/jakartaee/ParamValueType.java
rt/frontend/jaxws/src/main/java/org/apache/cxf/jaxws/handler/jakartaee/PathType.java
rt/frontend/jaxws/src/main/java/org/apache/cxf/jaxws/handler/jakartaee/PortComponentHandlerType.java
rt/frontend/jaxws/src/main/java/org/apache/cxf/jaxws/handler/jakartaee/XsdQNameType.java
rt/frontend/jaxws/src/main/java/org/apache/cxf/jaxws/handler/jakartaee/XsdStringType.java
rt/frontend/jaxws/src/main/java/org/apache/cxf/jaxws/handler/jakartaee/package-info.java
rt/frontend/jaxws/src/test/java/org/apache/cxf/jaxws/handler/JakartaAnnotationHandlerChainBuilderTest.java
rt/frontend/jaxws/src/test/java/org/apache/cxf/jaxws/handler/JavaxAnnotationHandlerChainBuilderTest.java
rt/frontend/jaxws/src/test/java/org/apache/cxf/jaxws/handler/jakarta-handlers.xml
rt/frontend/jaxws/src/test/java/org/apache/cxf/jaxws/handler/javax-handlers.xml

https://issues.apache.org/jira/browse/CXF-8361
* introduced new org.apache.cxf.jaxws.handler.jakarta_types package for JAXB de/serialization
* added new methods in HandlerChainBuilder
* enhanced handlers de/serialization tests

[CXF-8361] Finalized support for Jakarta NS

---

rt/wsdl/pom.xml
services/sts/sts-core/pom.xml
tools/validator/src/main/java/org/apache/cxf/tools/validator/internal/SchemaValidator.java

Using `Xerces` as the substitution of the JDK's implementation (sealed even more in JDK16). Sadly, not all features are supported by `Xerces`, fe `http://javax.xml.XMLConstants/property/accessExternalSchema` is not recognizable. 
@ffang could you please take a look? thank you!

CXF-8429: Illegal reflective access in XercesSchemaValidationUtils

---

rt/rs/sse/pom.xml
rt/rs/sse/src/test/java/org/apache/cxf/jaxrs/sse/client/SseEventSourceImplTest.java

Error Message
Expected: <2> but: was <1>
Stacktrace
java.lang.AssertionError: Expected: <2> but: was <1> at org.apache.cxf.jaxrs.sse.client.SseEventSourceImplTest.testReconnectAndTwoEventsReceived(SseEventSourceImplTest.java:297)

CXF-8428: Fix org.apache.cxf.jaxrs.sse.client.SseEventSourceImplTest.testReconnectAndTwoEventsReceived

---

parent/pom.xml
systests/microprofile/client/async/pom.xml
systests/microprofile/client/weld/src/test/java/org/apache/cxf/microprofile/AnnotationTransformer.java
systests/microprofile/client/weld/src/test/java/org/apache/cxf/microprofile/RetryAnalyzer.java
systests/microprofile/client/weld/testng.xml

The long term option would be to stabilize CXF or/and MP RestClient TCKs (may need some time), suggesting to use the retrier as the interim solution to the problem, at least to minimize the number of failing builds.
@andymc12 mind please taking a look? thanks!

CXF-8393: Umbrella issue to address fixing flaky tests

---

core/src/main/java/org/apache/cxf/io/CacheAndWriteOutputStream.java
core/src/main/java/org/apache/cxf/io/CachedOutputStream.java
core/src/test/java/org/apache/cxf/io/CacheAndWriteOutputStreamTest.java

see https://issues.apache.org/jira/browse/CXF-8442

CXF-8442 Java 16 & CachedOutputStream Fix IOException closed after multiple close() & postClose() calls 

---

rt/frontend/jaxrs/src/main/java/org/apache/cxf/jaxrs/JAXRSServerFactoryBean.java
rt/frontend/jaxrs/src/main/java/org/apache/cxf/jaxrs/model/ClassResourceInfo.java
rt/frontend/jaxrs/src/main/java/org/apache/cxf/jaxrs/provider/ProviderFactory.java
rt/frontend/jaxrs/src/main/java/org/apache/cxf/jaxrs/utils/AnnotationUtils.java
systests/cdi/base/src/main/java/org/apache/cxf/systests/cdi/base/AbstractCdiMultiAppTest.java
systests/cdi/base/src/main/java/org/apache/cxf/systests/cdi/base/CustomScopedBookStore.java
systests/cdi/base/src/main/java/org/apache/cxf/systests/cdi/base/PerRequestBookStore.java
systests/cdi/base/src/main/java/org/apache/cxf/systests/cdi/base/RequestScopedBookStore.java
systests/cdi/base/src/main/java/org/apache/cxf/systests/cdi/base/bindings/Logged.java
systests/cdi/base/src/main/java/org/apache/cxf/systests/cdi/base/bindings/LoggingFilter.java
systests/cdi/base/src/main/java/org/apache/cxf/systests/cdi/base/scope/CustomContext.java
systests/cdi/base/src/main/java/org/apache/cxf/systests/cdi/base/scope/CustomScopeExtension.java
systests/cdi/base/src/main/java/org/apache/cxf/systests/cdi/base/scope/CustomScoped.java
systests/cdi/base/src/main/resources/META-INF/services/javax.enterprise.inject.spi.Extension
systests/cdi/cdi-owb/cdi-multiple-apps-owb/src/test/java/org/apache/cxf/systest/jaxrs/BookStoreCustomApplication.java
systests/cdi/cdi-weld/cdi-multiple-apps-weld/src/test/java/org/apache/cxf/systest/jaxrs/BookStoreCustomApplication.java

I also added a couple of tests for `@NameBinding` and custom CDI scopes (which would be using `PerRequestResourceProvider` invocation), it turned out we had none.
@rmannibucau mind taking a look please?  thanks a lot!

CXF-8344: org.apache.cxf.jaxrs.utils.AnnotationUtils#getNameBindings does not use ClassUnwrapper

---

rt/frontend/jaxrs/src/main/java/org/apache/cxf/jaxrs/utils/JAXRSUtils.java
rt/frontend/jaxrs/src/test/java/org/apache/cxf/jaxrs/Customer.java
rt/frontend/jaxrs/src/test/java/org/apache/cxf/jaxrs/utils/JAXRSUtilsTest.java

This should fix the following Jakarta RESTful WS TCK failures:
> com/sun/ts/tests/jaxrs/ee/rs/beanparam/form/plain/JAXRSClient.java#formFieldParamEntityWithEncodedTest_from_standalone: JAXRSClient_formFieldParamEntityWithEncodedTest_from_standalone
> com/sun/ts/tests/jaxrs/ee/rs/beanparam/form/plain/JAXRSClient.java#formParamEntityWithEncodedTest_from_standalone: JAXRSClient_formParamEntityWithEncodedTest_from_standalone
The issue is that (prior to this fix) form parameters are read into a map as either decoded or encoded based on whether the first parameter has the `@Encoded` annotation or not.  This can result in the `@Encoded` annotation on second or subsequent parameters getting ignored.
The fix is to read the parameters into the map without performing any decoding until it is …

[CXF-7996] Fix `@Encode` TCK test

---

parent/pom.xml
rt/rs/client/src/main/java/org/apache/cxf/jaxrs/client/WebClient.java

Fixing this warning in the build:
```
[WARNING] Old version of checkstyle detected. Consider updating to >= v8.30
[WARNING] For more information see: https://maven.apache.org/plugins/maven-checkstyle-plugin/examples/upgrading-checkstyle.html
```
@amarkevich it seems like you have commented out the previous dependency change, any concerns / issues with it? Thank you!

Update Checkstyle to 8.41.1

---

rt/frontend/jaxrs/src/main/java/org/apache/cxf/jaxrs/provider/ProviderFactory.java
rt/frontend/jaxrs/src/test/java/org/apache/cxf/jaxrs/provider/CustomJaxbProvider.java
rt/frontend/jaxrs/src/test/java/org/apache/cxf/jaxrs/provider/ProviderFactoryTest.java
systests/jaxrs/src/test/java/org/apache/cxf/systest/jaxrs/JAXRSAsyncClientTest.java
systests/jaxrs/src/test/java/org/apache/cxf/systest/jaxrs/provider/CXFJaxbElementProvider.java
systests/jaxrs/src/test/java/org/apache/cxf/systest/jaxrs/provider/JAXBContextResolverTest.java

While troubleshooting the TCK test case in question discovered that sorting of message body readers and writers ~~is not symmetrical~~ does not handle all subclasses combinations correctly. 
- ~~readers are sorted first by media type~~ 
- ~~writers are sorted first by classes comparison which **does not look right**~~
~~Fixed the message body writers sorting by starting with media types, the same as for message body readers.~~

CXF-8516: Fixing jaxrs.spec.provider.jaxbcontext readWriteProviderTest

---

core/src/main/java/org/apache/cxf/helpers/IOUtils.java
rt/frontend/jaxrs/src/main/java/org/apache/cxf/jaxrs/provider/JAXBElementProvider.java
systests/jaxrs/src/test/java/org/apache/cxf/systest/jaxrs/provider/CXFResource.java
systests/jaxrs/src/test/java/org/apache/cxf/systest/jaxrs/provider/JAXBProviderTest.java

Per specification:
```
for a zero-length response entities returns a corresponding
Java object that represents zero-length data. In case no zero-length representation
is defined for the Java type, a {@link ProcessingException} wrapping the
underlying {@link NoContentException} is thrown.
```
For JAXB serialization / desearialization, the empty input stream (empty response) leads to `javax.xml.bind.UnmarshalException`, for example:
```
[com.ctc.wstx.exc.WstxEOFException: Unexpected EOF in prolog
at [row,col {unknown-source}]: [1,0]]
at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallerImpl.handleStreamException(UnmarshallerImpl.java:470)
at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal0(UnmarshallerImpl.java:402)
at …
```

CXF-8518: Fixing jaxrs.spec.provider.standardnotnull clientJaxbProviderTest

---

core/src/main/java/org/apache/cxf/common/spi/NamespaceClassGenerator.java

Only logs the message "Could not create a NamespaceMapper ..." if it really is the case

CXF-8536 Conditional log for NamespaceMapper not found

---

rt/frontend/jaxrs/src/main/java/org/apache/cxf/jaxrs/utils/JAXRSUtils.java

It's much better to use substring to remove the last '/' character than replaceAll from a performance perspective. Certain applications can see up to 2% throughput gains with this change.

Remove String.replaceAll JAXRSUtils performance fix

---

rt/frontend/jaxrs/src/main/java/org/apache/cxf/jaxrs/impl/RetryAfterHeaderProvider.java
rt/frontend/jaxrs/src/test/java/org/apache/cxf/jaxrs/impl/RetryAfterHeaderProviderTest.java
rt/rs/sse/src/main/java/org/apache/cxf/jaxrs/sse/client/SseEventSourceImpl.java
rt/rs/sse/src/test/java/org/apache/cxf/jaxrs/sse/client/SseEventSourceImplTest.java

CXF-7996 Jakarta EE TCKs and compatibility. Address SSE failures, missed 503 & Retry-After handling:
- jaxrs.jaxrs21.ee.sse.sseeventsource wait2Seconds 
- jaxrs.jaxrs21.ee.sse.sseeventsource defaultWaiting2s

CXF-7996 Jakarta EE TCKs and compatibility. Address SSE failures, missed 503 & Retry-After handling

---

parent/pom.xml
rt/rs/security/http-signature/pom.xml
rt/rs/security/http-signature/src/main/java/org/apache/cxf/rs/security/httpsignature/filters/CreateSignatureInterceptor.java
rt/rs/security/http-signature/src/main/java/org/apache/cxf/rs/security/httpsignature/filters/VerifySignatureFilter.java
rt/rs/security/http-signature/src/main/java/org/apache/cxf/rs/security/httpsignature/utils/SignatureHeaderUtils.java
rt/rs/security/http-signature/src/test/java/org/apache/cxf/rs/security/httpsignature/SpecExamplesTest.java

Changed Interceptor and Filter to include query component in request-target.
Added test methods to include interceptor/filter in testing the cases from the spec. These tests previously only tested the objects used within the interceptor/filter (MessageSigner/Verifier) which led to this issue not being discovered by tests.
I also had to include PowerMock to mock the static PhaseInterceptorChain class used by the VerifySignatureFilter.

[CXF-8535] Query missing from signature request-target

---

rt/frontend/jaxrs/src/main/java/org/apache/cxf/jaxrs/provider/ProviderFactory.java
rt/frontend/jaxrs/src/test/java/org/apache/cxf/jaxrs/PriorityCustomerParameterHandler.java
rt/frontend/jaxrs/src/test/java/org/apache/cxf/jaxrs/provider/ProviderFactoryTest.java
rt/rs/client/src/test/java/org/apache/cxf/jaxrs/client/ClientProviderFactoryTest.java
rt/rs/client/src/test/java/org/apache/cxf/jaxrs/client/Customer.java
rt/rs/client/src/test/java/org/apache/cxf/jaxrs/client/CustomerParameterHandler.java
rt/rs/client/src/test/java/org/apache/cxf/jaxrs/client/PriorityCustomerParameterHandler.java

`@Priority` support for `ParamConverterProvider` providers

CXF-8532: @Priority support for ParamConverterProvider

---

systests/microprofile/client/nocdi/pom.xml
systests/microprofile/client/nocdi/src/test/java/org/apache/cxf/systest/microprofile/rest/client/AsyncMethodTest.java
systests/microprofile/client/nocdi/src/test/java/org/apache/cxf/systest/microprofile/rest/client/AsyncThreadingTest.java
systests/microprofile/client/nocdi/src/test/java/org/apache/cxf/systest/microprofile/rest/client/mock/AsyncClientWithCompletionStage.java
systests/microprofile/client/nocdi/src/test/java/org/apache/cxf/systest/microprofile/rest/client/mock/AsyncInvocationInterceptorFactoryTestImpl.java
systests/microprofile/client/nocdi/src/test/java/org/apache/cxf/systest/microprofile/rest/client/mock/AsyncInvocationInterceptorFactoryTestImpl2.java
systests/microprofile/client/nocdi/src/test/java/org/apache/cxf/systest/microprofile/rest/client/mock/ThreadLocalClientFilter.java

This PR re-runs the MP Rest Client async tests but without using CDI or MP Config.  This is intended to verify that all of the dependencies on CDI and MP Config truly are optional, and it should address some of the concern raised in PR #805.

Run Async systests with no CDI or MP Config

---

rt/frontend/jaxrs/src/main/java/org/apache/cxf/jaxrs/utils/JAXRSUtils.java
rt/frontend/jaxrs/src/test/java/org/apache/cxf/jaxrs/impl/UriBuilderImplTest.java
systests/jaxrs/src/test/java/org/apache/cxf/systest/jaxrs/BookStore.java
systests/jaxrs/src/test/java/org/apache/cxf/systest/jaxrs/JAXRS20ClientServerBookTest.java

Allow special characters to be used for a queryParam name.

CXF-8387: Allow special characters to be used for a queryParam name.

---

rt/rs/client/src/test/java/org/apache/cxf/jaxrs/client/logging/RESTLoggingTest.java

The `org.apache.cxf.jaxrs.client.logging.RESTLoggingTest.testBinary` occasionally fails on Jenkins with:
```
org.junit.ComparisonFailure: expected:<[--- Content suppressed ---]> but was:<&amp#1;&amp#2;&amp#3;&amp#4;&amp#5;&amp#6;&amp#8;> at org.apache.cxf.jaxrs.client.logging.RESTLoggingTest.assertContentNotLogged(RESTLoggingTest.java:121) at org.apache.cxf.jaxrs.client.logging.RESTLoggingTest.testBinary(RESTLoggingTest.java:83)
```
It seems like the root cause is in-place `loggingFeature.setLogBinary(true)` modification: the feature's interceptors are called in the scope of different threads (execution thread + CXF's async working queue) but the feature was not supposed to be used from multiple threads. As such, the hypothesis is that `logBinary` flag change may not be visible by all …

CXF-8534: Fix org.apache.cxf.jaxrs.client.logging.RESTLoggingTest.testBinary

---

rt/rs/client/src/main/java/org/apache/cxf/jaxrs/client/JAXRSClientFactoryBean.java
rt/rs/client/src/test/java/org/apache/cxf/jaxrs/client/spring/JAXRSClientFactoryBeanTest.java
rt/rs/client/src/test/java/org/apache/cxf/jaxrs/client/spring/clients.xml
systests/jaxrs/src/test/java/org/apache/cxf/systest/jaxrs/BookServer.java
systests/jaxrs/src/test/java/org/apache/cxf/systest/jaxrs/BookStoreRegex.java
systests/jaxrs/src/test/java/org/apache/cxf/systest/jaxrs/JAXRSClientServerBookTest.java

CXF-8556: Null AbstractEndpointFactory Properties Interferes with Class-Level PathParam When Creating Proxies with Defined ClientState

CXF-8556: Null AbstractEndpointFactory Properties Interferes with Class-Level PathParam When Creating Proxies with Defined ClientState

---

rt/rs/extensions/json-basic/src/main/java/org/apache/cxf/jaxrs/json/basic/JsonMapObjectReaderWriter.java
rt/rs/extensions/json-basic/src/test/java/org/apache/cxf/jaxrs/json/basic/JsonMapObjectReaderWriterTest.java

The logic is changed so that it now only escapes " and \ if they are not already escaped. I did not choose to escape /, because this broke a ton of tests in different modules.
In addition, I followed the existing logic for /, so that after parsing it strips out the backslashes that were previously escaped.

CXF-8555 - JsonMapObjectReaderWriter escapes now any back slash

---

rt/rs/sse/src/main/java/org/apache/cxf/jaxrs/sse/interceptor/SseInterceptor.java
systests/rs-sse/rs-sse-base/src/main/java/org/apache/cxf/systest/jaxrs/sse/AbstractSseTest.java
systests/rs-sse/rs-sse-base/src/main/java/org/apache/cxf/systest/jaxrs/sse/BookStore.java
systests/rs-sse/rs-sse-base/src/main/java/org/apache/cxf/systest/jaxrs/sse/BookStoreResponseFilter.java

`SseInterceptor` uses PROTOCOL_HEADERS from request (in) message, not from response (out) one, as such the request headers are leaking into the response.

CXF-8559: SseInterceptor uses PROTOCOL_HEADERS from request (in) message, not from response (out) one

---

rt/frontend/jaxrs/src/main/java/org/apache/cxf/jaxrs/utils/JAXRSUtils.java
rt/frontend/jaxrs/src/test/java/org/apache/cxf/jaxrs/impl/UriBuilderImplTest.java

A service in question needs to be reachable via multiple paths. The @Path parameter allows for regex matching on a class-level like the following: @Path("/{a: regex}"). A class-level `@PathParam` is created by the name of a. On the server side, the following annotations both correctly receive requests at `/foo/bar`:
```
@Path("/{a : foo/bar}")
@Path("/{a : foo\\/bar}")
```
However, on the client side, the following URI(s)
```
final URI uri = UriBuilder
.fromUri("/")
.path("{a : foo/bar}")
.buildFromEncoded("foo/bar");
```
are not properly constructed due to the fact that `/` is used as path segment separator without taking into account the URI template expression.

CXF-8557: Incorrect Proxy Path Segmenting when @Path Annotation RegexExpression Contains '/'

---

rt/rs/microprofile-client/pom.xml

* Using OSGi's [Service Loader Mediator](https://blog.osgi.org/2013/02/javautilserviceloader-in-osgi.html) (i.e. Apache Aries [SPI Fly](https://aries.apache.org/documentation/modules/spi-fly.html))
* Made all requirements optional (minimally invasive change)
* ~~Removing `Bundle-ActivationPolicy` header _locally_ as it prevents the OSGi ServiceLoader Mediator (SPI Fly) to work when set to [`Lazy`](https://github.com/apache/cxf/blob/master/parent/pom.xml#L653) (in the parent POM). I committed this separately should there be a better solution.~~
Based on the following discussion: https://github.com/eclipse/microprofile-rest-client/issues/308#issuecomment-813638983
Cheers

MicroProfile REST client: enable SPI/ServiceLoader under OSGi 

---

rt/rs/microprofile-client/pom.xml

* The Rest Client for MicroProfile specification defines CDI and MP Config as optional
* Analogous upstream change: https://github.com/eclipse/microprofile-rest-client/pull/309
Cheers

Make CDI and MP Config dependencies optional for MicroProfile REST client

---

rt/features/logging/src/main/java/org/apache/cxf/ext/logging/event/DefaultLogEventMapper.java
rt/features/logging/src/test/java/org/apache/cxf/ext/logging/DefaultLogEventMapperTest.java

[CXF-8568] Added overloaded map method, added null check for sensitiveProtocolHeaders in DefaultLogEventMapper

[CXF-8568] DefaultLogEventMapper Method Overload

---

rt/frontend/jaxrs/src/main/java/org/apache/cxf/jaxrs/impl/EntityTagHeaderProvider.java
rt/frontend/jaxrs/src/test/java/org/apache/cxf/jaxrs/impl/EntityTagHeaderProviderTest.java

With  following ETag being generated `wyoBLW/ye71RgN/0LNyj4eA5rfE1ovtlM03aakuGr2Y=`,  the `EntityTag.valueOf(etag)` throws following error:
```
java.lang.IllegalArgumentException: Misformatted ETag : "wyoBLW/ye71RgN/0LNyj4eA5rfE1ovtlM03aakuGr2Y="
at org.apache.cxf.jaxrs.impl.EntityTagHeaderProvider.fromString(EntityTagHeaderProvider.java:57)
```
As per specification, the ETag should start from `W/` to indicate weak validator.

CXF-8572: Incorrectly parsed ETag when contains 'W/' as part of the content

---

rt/rs/microprofile-client/src/main/java/org/apache/cxf/microprofile/client/proxy/MicroProfileClientProxyImpl.java
systests/microprofile/client/jaxrs/src/test/java/org/apache/cxf/systest/microprofile/rest/client/regex/BookStore.java
systests/microprofile/client/jaxrs/src/test/java/org/apache/cxf/systest/microprofile/rest/client/regex/BookStoreClientRoot.java
systests/microprofile/client/jaxrs/src/test/java/org/apache/cxf/systest/microprofile/rest/client/regex/JaxrsPathRegexTest.java

The usage of varargs made unwanted parameters treated as variables

CXF-8574: MP Rest call on jax-rs interface with long @Path and 3 path params causes error since

---

parent/pom.xml

The 3.0.x patch line won't be developed further.

Update RxJava3 to 3.1.0

---

integration/spring-boot/autoconfigure/src/main/java/org/apache/cxf/spring/boot/autoconfigure/CxfAutoConfiguration.java
integration/spring-boot/autoconfigure/src/main/java/org/apache/cxf/spring/boot/autoconfigure/CxfProperties.java
integration/spring-boot/autoconfigure/src/test/java/org/apache/cxf/spring/boot/autoconfigure/CxfAutoConfigurationTest.java
systests/spring-boot/src/test/java/org/apache/cxf/systest/jaxrs/spring/boot/SpringClientOnlyJaxrsTest.java
systests/spring-boot/src/test/resources/application-client.yml

Provide the possibility to control CXF servlet registration over the property `cxf.servlet.enabled`

CXF-8539: Allow client-only Spring Boot autoconfiguration

---

rt/frontend/jaxrs/src/main/java/org/apache/cxf/jaxrs/utils/ResourceUtils.java
rt/frontend/jaxrs/src/test/java/org/apache/cxf/jaxrs/utils/ResourceUtilsTest.java
rt/rs/client/src/test/java/org/apache/cxf/jaxrs/client/JAXRSClientFactoryBeanTest.java
rt/rs/client/src/test/java/org/apache/cxf/jaxrs/resources/SuperBook.java
rt/rs/client/src/test/java/org/apache/cxf/jaxrs/resources/SuperBookStore.java

Bridge methods for covariant return types cannot be invoked on client proxies

CXF-8578: Bridge methods for covariant return types cannot be invoked on client proxies

---

rt/transports/jms/src/main/java/org/apache/cxf/transport/jms/JMSConduit.java
rt/transports/jms/src/main/java/org/apache/cxf/transport/jms/JMSConfiguration.java

Temporary queues are never deleted when the are used.
This patch provides fixes for this behavior.

Delete temporary queue when it is used

---

rt/frontend/jaxws/src/main/java/org/apache/cxf/jaxws/EndpointReferenceBuilder.java
rt/frontend/jaxws/src/main/java/org/apache/cxf/jaxws/support/JaxWsEndpointImpl.java
rt/ws/policy/src/main/java/org/apache/cxf/ws/policy/PolicyAnnotationListener.java
rt/ws/policy/src/main/java/org/apache/cxf/ws/policy/attachment/reference/LocalServiceModelReferenceResolver.java
rt/ws/policy/src/main/java/org/apache/cxf/ws/policy/attachment/wsdl11/Wsdl11AttachmentPolicyProvider.java
rt/ws/policy/src/test/java/org/apache/cxf/ws/policy/attachment/reference/ReferenceResolverTest.java
rt/wsdl/src/main/java/org/apache/cxf/wsdl11/SchemaUtil.java
rt/wsdl/src/main/java/org/apache/cxf/wsdl11/ServiceWSDLBuilder.java

Add synchronization to UnknownExtensibilityElement.getElement() call sites.
The Element returned from getElement may not be thread safe, so we have to take precautions when accessing the Element.
Also synchronize on the DescriptionInfo parameter in Wsdl11AttachmentPolicyProvider.getElementPolicy to avoid a race condition when registeredPolicy is not yet set.

[CXF-8590]

---

rt/features/metrics/src/main/java/org/apache/cxf/metrics/micrometer/provider/jaxrs/JaxrsTags.java
systests/spring-boot/src/test/java/org/apache/cxf/systest/jaxrs/spring/boot/SpringJaxrsApplicationTest.java
systests/spring-boot/src/test/java/org/apache/cxf/systest/jaxrs/spring/boot/SpringJaxrsTest.java

The method for the client proxy is stored in exchange and could be picked from there.

CXF-8588: Micrometer operation UNKNOWN for clients

---

osgi/karaf/features/src/main/resources/features.xml

`cxf-specs` feature installs stax2-api bundle without dependency flag set to true. It causes issues with camel features.

CXF-8585: cxf-specs feature should use stax2-api 4.2 bundle with dependency=true

---

osgi/bundle/pom.xml
osgi/bundle/servlet-compatible/pom.xml
osgi/karaf/features/pom.xml
osgi/karaf/features/src/main/resources/org.apache.karaf.features.xml

Thanks to @ffang for identifying the root cause: the root cause of this error is that in the container two `javax.servlet` versions are required.

CXF-8593: Error when installing CXF OpenAPI v3 under Karaf 4.2.11

---

rt/rs/client/src/main/java/org/apache/cxf/jaxrs/client/JAXRSClientFactoryBean.java
rt/rs/client/src/main/java/org/apache/cxf/jaxrs/client/spring/JAXRSClientFactoryBeanDefinitionParser.java
rt/rs/client/src/test/java/org/apache/cxf/jaxrs/client/cache/ClientCacheTest.java
rt/rs/client/src/test/java/org/apache/cxf/jaxrs/client/spring/JAXRSClientFactoryBeanTest.java
rt/rs/client/src/test/java/org/apache/cxf/jaxrs/client/spring/SpringParameterHandler.java
rt/rs/client/src/test/java/org/apache/cxf/jaxrs/client/spring/clients.xml
rt/rs/microprofile-client/src/main/java/org/apache/cxf/microprofile/client/MicroProfileClientFactoryBean.java
rt/rs/microprofile-client/src/test/java/org/apache/cxf/microprofile/client/CxfTypeSafeClientBuilderTest.java
rt/rs/microprofile-client/src/test/java/org/apache/cxf/microprofile/client/MicroProfileClientFactoryBeanTest.java

The `JAXRSClientFactoryBean` does not support JAX-RS features, as such if the feature registers additional providers, then those providers are never considered for use on the proxy or `WebClient` instance created.

CXF-7543: JAX-RS Features not used in proxies or WebClients

---

rt/frontend/jaxrs/src/main/java/org/apache/cxf/jaxrs/impl/ResponseImpl.java
systests/jaxrs/src/test/java/org/apache/cxf/systest/jaxrs/ClientHttpConnectionOutInterceptor.java
systests/jaxrs/src/test/java/org/apache/cxf/systest/jaxrs/JAXRSMultithreadedClientTest.java
systests/jaxrs/src/test/java/org/apache/cxf/systest/jaxrs/JAXRSRequestDispatcherTest.java

Relates to https://github.com/apache/cxf/pull/697, the entity input stream is indeed not closed after consumption. But according to the specification for `public abstract <T> T readEntity(Class<T> entityType, Annotation[] annotations)`:
> A message instance returned from this method will be cached for subsequent retrievals via getEntity(). Unless the supplied entitytype is an input stream, this method automatically closes the an unconsumed original response entity data stream if open.

CXF-8597: CXF JAXRS client not closing HTTP connections

---

rt/frontend/jaxrs/src/main/java/org/apache/cxf/jaxrs/impl/ResponseImpl.java
rt/frontend/jaxrs/src/main/java/org/apache/cxf/jaxrs/utils/JAXRSUtils.java
rt/frontend/jaxrs/src/test/java/org/apache/cxf/jaxrs/impl/ResponseImplTest.java
rt/rs/client/src/main/java/org/apache/cxf/jaxrs/client/AbstractClient.java

By default, the response entity is never closed automatically which is not compliant with JAX-RS specification and TCK. The auto-close behavior is controlled by `ResponseImpl#RESPONSE_STREAM_AUTO_CLOSE` property which is set to "false" by default.
One of the possible solutions which tries to minimize the impact of the change as much as possible is to introduce the `autoCloseHint`. It alters the default value of this property to be "true" for all non-streaming and non-streaming like responses  in order to follow the specification. The additional set of streaming-like responses, including `MultipartBody`, `Attachment`, ... and all supported reactive types have been introduced.
Fixing following tests:
- com/sun/ts/tests/jaxrs/ee/rs/core/response/JAXRSClient.java#getEntityThrowsIllegalStateExc …

CXF-8601: [Regression] jaxrs.ee.rs.core.response tests

---

core/src/main/java/org/apache/cxf/message/Message.java
rt/rs/client/src/main/java/org/apache/cxf/jaxrs/client/AbstractClient.java
rt/transports/http/src/main/java/org/apache/cxf/transport/http/HTTPConduit.java
systests/jaxrs/src/test/java/org/apache/cxf/systest/jaxrs/BookStore.java
systests/jaxrs/src/test/java/org/apache/cxf/systest/jaxrs/JAXRSAsyncClientTest.java
systests/jaxrs/src/test/java/org/apache/cxf/systest/jaxrs/JAXRSClientServerBookTest.java

It turns out that when async client is used with oneway methods (in CXF context, oneway is the method that returns 202), the response hangs indefinitely due to the fact that the client callback is never called / propagated. Additionally, it turned out, for sync / async flows, the response filters are also not called for oneway methods.
- Introduced new contextual property `PROPAGATE_202_RESPONSE_ONEWAY_OR_PARTIAL`
- It is set to `false` by default but JAX-RS clients override it with `true`

CXF-8616: Calling oneway methods using async client hangs response indefinitely

---

bom/pom.xml
parent/pom.xml
rt/transports/http-hc5/pom.xml
rt/transports/http-hc5/src/main/java/org/apache/cxf/transport/http/asyncclient/hc5/AnyAuthScope.java
rt/transports/http-hc5/src/main/java/org/apache/cxf/transport/http/asyncclient/hc5/AsyncHTTPConduit.java
rt/transports/http-hc5/src/main/java/org/apache/cxf/transport/http/asyncclient/hc5/AsyncHTTPConduitFactory.java
rt/transports/http-hc5/src/main/java/org/apache/cxf/transport/http/asyncclient/hc5/AsyncHttpTransportFactory.java
rt/transports/http-hc5/src/main/java/org/apache/cxf/transport/http/asyncclient/hc5/CXFHttpAsyncRequestProducer.java
rt/transports/http-hc5/src/main/java/org/apache/cxf/transport/http/asyncclient/hc5/CXFHttpAsyncResponseConsumer.java
rt/transports/http-hc5/src/main/java/org/apache/cxf/transport/http/asyncclient/hc5/CXFHttpRequest.java
rt/transports/http-hc5/src/main/java/org/apache/cxf/transport/http/asyncclient/hc5/CXFResponseCallback.java
rt/transports/http-hc5/src/main/java/org/apache/cxf/transport/http/asyncclient/hc5/MutableHttpEntity.java
rt/transports/http-hc5/src/main/java/org/apache/cxf/transport/http/asyncclient/hc5/SharedInputBuffer.java
rt/transports/http-hc5/src/main/java/org/apache/cxf/transport/http/asyncclient/hc5/SharedOutputBuffer.java
rt/transports/http-hc5/src/main/resources/META-INF/cxf/bus-extensions.txt
rt/transports/http-hc5/src/test/java/org/apache/cxf/transport/http/asyncclient/hc5/AsyncHTTPConduitTest.java
rt/transports/pom.xml
systests/pom.xml
systests/transport-hc5/pom.xml
systests/transport-hc5/src/test/java/org/apache/cxf/systest/hc5/jaxrs/Book.java
systests/transport-hc5/src/test/java/org/apache/cxf/systest/hc5/jaxrs/BookServerAsyncClient.java
systests/transport-hc5/src/test/java/org/apache/cxf/systest/hc5/jaxrs/BookStore.java
systests/transport-hc5/src/test/java/org/apache/cxf/systest/hc5/jaxrs/Chapter.java
systests/transport-hc5/src/test/java/org/apache/cxf/systest/hc5/jaxrs/JAXRSAsyncClientTest.java
systests/transport-hc5/src/test/java/org/apache/cxf/systest/hc5/jaxrs/RETRIEVE.java
systests/transport-hc5/src/test/java/org/apache/cxf/systest/hc5/jaxws/JAXWSAsyncClientTest.java

Upgrade Http Components Core and Client to 5.0 by introducing new module `transports/http-hc5`. Functionally, it is interchangeable with the Http Components Core and Client to 4.x (existing `transports/http-hc` module, except the OSGi part) and could be used as in-place replacement.  The implementation is largely ported from the `transports/http-hc` and adapted to the new APIs.

CXF-8221: Upgrade Http Components Core and Client to 5.0

---

rt/transports/http-hc5/src/main/java/org/apache/cxf/transport/http/asyncclient/hc5/SharedOutputBuffer.java
rt/transports/http-hc5/src/test/java/org/apache/cxf/transport/http/asyncclient/hc5/AsyncHTTPConduitTest.java

Caused by the exception in `SharedOutputBuffer` which signaled the end of the stream prematurely.

CXF-8617: The org.apache.cxf.transport.http.asyncclient.hc5.AsyncHTTPConduitTest hangs intermittently

---

distribution/src/main/release/samples/pom.xml
parent/pom.xml

Update to Spring Boot 2.6.0:
- Update to Spring Boot 2.6.0 (https://spring.io/blog/2021/11/19/spring-boot-2-6-is-now-available)
- Update to Spring Security 5.6.0 (https://spring.io/blog/2021/11/16/spring-security-5-6-0-released)
- Update to Micrometer 1.8.0 (https://github.com/micrometer-metrics/micrometer/releases/tag/v1.8.0)

CXF-8618: Update to Spring Boot 2.6.0

---

rt/transports/http/src/main/java/org/apache/cxf/transport/servlet/servicelist/ServiceListGeneratorServlet.java
rt/transports/http/src/test/java/org/apache/cxf/transport/servlet/ServletControllerTest.java

lightweight healthcheck endpoint using HTTP HEAD method

cxf-rt-transports-http: allow to use service list endpoint as lightweight healthcheck endpoint using HTTP HEAD method

---

rt/frontend/jaxrs/src/main/java/org/apache/cxf/jaxrs/ext/TRACE.java
rt/transports/http/src/main/java/org/apache/cxf/transport/servlet/AbstractHTTPServlet.java
systests/spring-boot/src/test/java/org/apache/cxf/systest/jaxrs/resources/Library.java
systests/spring-boot/src/test/java/org/apache/cxf/systest/jaxrs/resources/LibraryApi.java
systests/spring-boot/src/test/java/org/apache/cxf/systest/jaxrs/spring/boot/SpringJaxrsTest.java
systests/transport-netty/src/test/java/org/apache/cxf/systest/http2/netty/AbstractNettyClientServerHttp2Test.java
systests/transport-netty/src/test/java/org/apache/cxf/systest/http2/netty/BookStore.java
systests/transport-netty/src/test/java/org/apache/cxf/systest/http2/netty/Http2TestClient.java

A number of JAX-RS TCK of tests use HTTP TRACE to verify the client / server behavior, but TRACE HTTP method dispatching is not supported by AbstractHTTPServlet, causing tests do not fail.

CXF-8620: AbstractHTTPServlet should support HTTP TRACE method dispatching if it is allowed by underlying container

---

rt/frontend/jaxrs/src/main/java/org/apache/cxf/jaxrs/utils/JAXRSUtils.java
rt/frontend/jaxrs/src/test/java/org/apache/cxf/jaxrs/impl/ResponseImplTest.java

Fixing jaxrs.spec.provider.standardnotnull clientDataSourceProviderTest
Before:
```
Tests that passed: 2630
Tests that failed: 33 
Total: 2663
```
| keyword                                                                                                       | passed | failed | Total |
|---|---|---|---|
| all clientDataSourceProviderTest forward javaee jaxrs standalone_vehicle |  |  1  | 1  |
After:
```
Tests that passed: 2631
Tests that failed: 32 
Total: 2663
```
| keyword                                                                                                       | passed | failed | Total |
|---|---|---|---|
| all clientDataSourceProviderTest forward javaee jaxrs standalone_vehicle | 1 |   | 1 |

Fixing jaxrs.spec.provider.standardnotnull clientDataSourceProviderTest

---

parent/pom.xml
rt/rs/microprofile-client/pom.xml
rt/rs/microprofile-client/src/test/java/org/apache/cxf/microprofile/client/AsyncTest.java

Right now there is one module which uses `mockwebserver` for test scaffolding, this is not really necessary since we already have `wiremock` dependency in place. One or another should be used, although `wiremock`  is used in most places.

CXF-8630: Remove mockwebserver dependency, use wiremock instead

---

rt/rs/client/src/main/java/org/apache/cxf/jaxrs/client/AbstractClient.java
systests/transports/src/test/java/org/apache/cxf/systest/http/HTTPConduitTest.java

The regression introduced by [CXF-8633](https://issues.apache.org/jira/browse/CXF-8633) causes intermittent tests failures wirh `ConcurrentModificationException`: 
```
Caused by: java.util.ConcurrentModificationException
at java.base/java.util.HashMap$HashIterator.nextNode(HashMap.java:1511)
at java.base/java.util.HashMap$EntryIterator.next(HashMap.java:1544)
at java.base/java.util.HashMap$EntryIterator.next(HashMap.java:1542)
at java.base/java.util.HashMap.putMapEntries(HashMap.java:508)
at java.base/java.util.HashMap.putAll(HashMap.java:781)
at org.apache.cxf.message.MessageImpl.calcContextCache(MessageImpl.java:216)
at org.apache.cxf.message.MessageImpl.getContextualProperty(MessageImpl.java:179)
at org.apache.cxf.message.MessageUtils.getContextualProperty(MessageUtils.java:176)
at …
```

CXF-8635: Fix org.apache.cxf.jaxrs.client.logging.RESTLoggingTest.testSlf4

---

rt/frontend/jaxrs/src/main/java/org/apache/cxf/jaxrs/impl/ResponseImpl.java
rt/frontend/jaxrs/src/test/java/org/apache/cxf/jaxrs/impl/ResponseImplTest.java

`ResponseImpl#hasEntity` returns 'false' when entity is buffered but entity stream is fully consumed with processing exception. 
No new TCK test cases are failing:
```
Test results: passed: 2,631; failed: 32
```

CXF-8642: ResponseImpl#hasEntity return 'false' when entity is buffered but entity stream is fully consumed with processing exception

---

systests/jaxrs/src/test/java/org/apache/cxf/systest/jaxrs/AsyncResource2.java
systests/jaxrs/src/test/java/org/apache/cxf/systest/jaxrs/JAXRSContinuationsServlet3Test.java

Fix org.apache.cxf.systest.jaxrs.JAXRSContinuationsServlet3Test.testSuspendSetTimeout

CXF-8650: Fix org.apache.cxf.systest.jaxrs.JAXRSContinuationsServlet3Test.testSuspendSetTimeout

---

rt/frontend/jaxrs/src/main/java/org/apache/cxf/jaxrs/provider/ProviderFactory.java
rt/frontend/jaxrs/src/main/java/org/apache/cxf/jaxrs/provider/ServerProviderFactory.java
rt/frontend/jaxrs/src/test/java/org/apache/cxf/jaxrs/provider/ProviderFactoryTest.java
rt/rs/client/src/main/java/org/apache/cxf/jaxrs/client/ClientProviderFactory.java
rt/rs/client/src/test/java/org/apache/cxf/jaxrs/client/ClientProviderFactoryTest.java
rt/rs/microprofile-client/src/main/java/org/apache/cxf/microprofile/client/MicroProfileClientProviderFactory.java

As per JSR 370:
```
@ConstrainedTo: 
Can be used to restrict the applicability of a provider to just the Client API or just the Server API. If omitted, a
provider can be used in either context.
```
Fixing 1 TCK test (clientSideReaderIsNotUsedOnServerTest):
```
Test results: passed: 2,638; failed: 25
```

CXF-8652: Implement @ConstrainedTo annotation support

---

rt/frontend/jaxrs/src/main/java/org/apache/cxf/jaxrs/utils/JAXRSUtils.java

Ensure InputStreamDataSource is optional in JAXRSUtils to be able to run without activation dependency

CXF-8654: Ensure InputStreamDataSource is optional in JAXRSUtils to be able to run without activation dependency

---

distribution/src/main/release/samples/pom.xml
parent/pom.xml
rt/rs/description-swagger-ui/src/main/java/org/apache/cxf/jaxrs/swagger/ui/SwaggerUiConfig.java
rt/rs/description-swagger-ui/src/main/java/org/apache/cxf/jaxrs/swagger/ui/SwaggerUiService.java
systests/jaxrs/src/test/java/org/apache/cxf/systest/jaxrs/description/SwaggerUiConfigurationQueryConfigTest.java

Since [Swagger UI 4.1.3](https://github.com/swagger-api/swagger-ui/releases/tag/v4.1.3) passing the default URL as query parameter, e.g. `?url=swagger.json` is disabled by default due to security concerns. Instead the default swagger PetStore definition is loaded.
It's possible to restore the old behaviour by setting `queryConfigEnabled` inside the config file but in this case, custom SwaggerUI distribution should be used. 
One of the options to make it work is to replace the URL on the fly while returning `index.html`, fetching the URL not from the query string but using server-side configuration (no security concerns with respect to picking arbitrary URLs). This behavior is controlled by `SwaggerUiConfig::queryConfigEnabled` (default: `false`) and triggers only when `queryConfigEnabled` …

CXF-8636: Swagger2Feature: Can't set url in UI through SwaggerUiConfig

---

rt/frontend/simple/src/main/java/org/apache/cxf/frontend/WSDLGetUtils.java
systests/jaxws/src/test/java/org/apache/cxf/systest/jaxws/OASISCatalogTest.java
testutils/src/main/resources/wsdl/others/common.xsd
testutils/src/main/resources/wsdl/others/d/common.xsd
testutils/src/main/resources/wsdl/others/d/shared.xsd
testutils/src/main/resources/wsdl/others/hello_world_messages_catalog.wsdl

Issue: https://issues.apache.org/jira/browse/CXF-8655
As commented in the Jira the three lines added in [CXF-6717](https://issues.apache.org/jira/browse/CXF-6717) for "urn" are removed. If you prefer other solution just let me know. Test added for the issue.
If you agree with the solution I'll submit more PR for the different branches (3.5.x, 3.4.x and 3.3.x).
Thanks a lot in advance!

[CXF-8655] Incorrect XSD resolution when the file name is the same in different folders

---

rt/frontend/jaxrs/src/main/java/org/apache/cxf/jaxrs/utils/JAXRSUtils.java
systests/jaxrs/src/test/java/org/apache/cxf/systest/jaxrs/BookResourceLocator.java
systests/jaxrs/src/test/java/org/apache/cxf/systest/jaxrs/BookServerSub.java
systests/jaxrs/src/test/java/org/apache/cxf/systest/jaxrs/JAXRSClientServerSubBookTest.java

Before:
| Tests that passed  |  2637| 
|  -- |  -- | 
|  Tests that failed | 12   |  
| Total  | 2663  | 
After:
| Tests that passed  |  2638 | 
|  -- |  -- | 
|  Tests that failed | 25   |  
| Total  | 2663  | 
Only 12 test cases left:
```
JT Harness : Tests that failed
Tests are grouped by their final status message.
Test case throws exception: No exception has been thrown for link <http://:@>
[com/sun/ts/tests/jaxrs/api/rs/core/linkbuilder/JAXRSClient.java#buildNoArgsThrowsUriBuilderExceptionTest_from_standalone](file:///tmp/JTwork/com/sun/ts/tests/jaxrs/api/rs/core/linkbuilder/JAXRSClient_buildNoArgsThrowsUriBuilderExceptionTest_from_standalone.jtr): JAXRSClient_buildNoArgsThrowsUriBuilderExceptionTest_from_standalone
[com/sun/ts/tests/jaxrs/api/rs/core/linkbuilder/JAXRSClient.java#bui …
```

CXF-8522: Fixing jaxrs.spec.resource.requestmatching consumesOnResourceLocatorTest & other subresource test cases

---

rt/frontend/jaxrs/src/main/java/org/apache/cxf/jaxrs/utils/HttpUtils.java
rt/frontend/jaxrs/src/test/java/org/apache/cxf/jaxrs/utils/HttpUtilsTest.java

CXF-8682: x-forwarded-proto header causes cxf to not match request to java method

CXF-8682: x-forwarded-proto header causes cxf to not match request to java method

---

rt/rs/security/jose-parent/jose-jaxrs/src/main/java/org/apache/cxf/rs/security/jose/jaxrs/JwtTokenSecurityContext.java
systests/rs-security/src/test/java/org/apache/cxf/systest/jaxrs/security/jose/jwt/JWTAuthnAuthzTest.java

BTW, I noticed that the assertion statements were not correct.

[CXF-8686] JWT role claim incorrectly parsed if not tokenized as string

---

maven-plugins/java2ws-plugin/src/main/java/org/apache/cxf/maven_plugin/Java2WSMojo.java

cxf-java2ws-plugin plugin running on non-modular JDK fails with NullPointerException

CXF-8689: cxf-java2ws-plugin plugin running on non-modular JDK fails with NullPointerException

---

rt/frontend/jaxrs/src/main/java/org/apache/cxf/jaxrs/impl/Rfc3986UriValidator.java
rt/frontend/jaxrs/src/main/java/org/apache/cxf/jaxrs/impl/UriBuilderImpl.java
rt/frontend/jaxrs/src/main/java/org/apache/cxf/jaxrs/utils/HttpUtils.java
rt/frontend/jaxrs/src/test/java/org/apache/cxf/jaxrs/impl/LinkBuilderImplTest.java
rt/frontend/jaxrs/src/test/java/org/apache/cxf/jaxrs/impl/UriBuilderImplTest.java

The Java's URI is not compliant with RFC 3986 and as such, some invalid URIs sneak in, failing the TCK test cases:
```
Test case throws exception: No exception has been thrown for link <http://:@>
[com/sun/ts/tests/jaxrs/api/rs/core/linkbuilder/JAXRSClient.java#buildNoArgsThrowsUriBuilderExceptionTest_from_standalone](https://ci-builds.apache.org/tmp/JTwork/com/sun/ts/tests/jaxrs/api/rs/core/linkbuilder/JAXRSClient_buildNoArgsThrowsUriBuilderExceptionTest_from_standalone.jtr): JAXRSClient_buildNoArgsThrowsUriBuilderExceptionTest_from_standalone
[com/sun/ts/tests/jaxrs/api/rs/core/linkbuilder/JAXRSClient.java#buildObjectsThrowsUriBuilderExceptionTest_from_standalone](https://ci-builds.apache.org/tmp/JTwork/com/sun/ts/tests/jaxrs/api/rs/core/linkbuilder/JAXRSClient_buildObjectsThrowsUriBuild …
```

CXF-8688: Accomodate some RFC 3986 checks to filter out invalid URIs

---

core/src/test/java/org/apache/cxf/io/CachedStreamTestBase.java

**Issue**
[Jira Issue](https://issues.apache.org/jira/browse/CXF-8697?jql=project%20%3D%20CXF%20AND%20resolution%20%3D%20Unresolved%20AND%20text%20~%20%22CachedOutputStream%22%20ORDER%20BY%20priority%20DESC%2C%20updated%20DESC)
The tests `org.apache.cxf.io.CacheAndWriteOutputStreamTest.testDeleteTmpFile` and `org.apache.cxf.io.CachedOutputStreamTest.testDeleteTmpFile` fail when run by themselves with the command `mvn test` because the temporary file is null. The reason is because the method `createFileOutPutStream` is never called in the method `enforceLimits` in `CachedOutputStream` since the threshold instance variable is not greater than the totalLength variable. The threshold variable depends on the static variable defaultThreshold. The defaultThreshold also depends on the system …

[CXF-8697] Fix order-dependent flaky tests

---

rt/ws/security/src/main/java/org/apache/cxf/ws/security/trust/AbstractSTSClient.java

In AbstractSTSClient NPE is thrown when instance claims is null, and claimsCallbackHandler returns claims as ClaimCollection.
In the original code the wrong variable was cast on the claimCollection local variable, was claims and should be claimsToSerialize.

NPE fix in addClaims() method

---

services/sts/systests/sts-itests/src/test/java/org/apache/cxf/systest/sts/itests/BasicSTSIntegrationTest.java

PAX Maven URL does not take local Maven repository into account, see please [1]. It seems like the system property is not taken into account.
[1] https://github.com/apache/cxf/pull/946/files

CXF-8703: PAX Maven URL does not take local Maven repository into account

---

rt/frontend/jaxrs/src/main/java/org/apache/cxf/jaxrs/impl/ContainerRequestContextImpl.java
rt/frontend/jaxrs/src/main/java/org/apache/cxf/jaxrs/impl/UriInfoImpl.java
rt/frontend/jaxrs/src/main/java/org/apache/cxf/jaxrs/utils/HttpUtils.java
systests/jaxrs/src/test/java/org/apache/cxf/systest/jaxrs/BookServer20.java
systests/jaxrs/src/test/java/org/apache/cxf/systest/jaxrs/JAXRS20ClientServerBookTest.java

Fixing `jaxrs.ee.rs.container.requestcontext setRequestUriTwoUrisTest`. It turns out CXF does not distinguish between base URI and request URI but it should. Finally, we have a clean TCK run:
```
[javatest.batch] ********************************************************************************
[javatest.batch] Completed running 2663 tests.
[javatest.batch] Number of Tests Passed      = 2663
[javatest.batch] Number of Tests Failed      = 0
[javatest.batch] Number of Tests with Errors = 0
[javatest.batch] ********************************************************************************
```

CXF-8478: fixing jaxrs.ee.rs.container.requestcontext setRequestUriTwoUrisTest

---

core/src/main/java/org/apache/cxf/attachment/AttachmentSerializer.java
core/src/main/java/org/apache/cxf/attachment/AttachmentUtil.java
core/src/test/java/org/apache/cxf/attachment/AttachmentSerializerTest.java

RFC-2392 (https://datatracker.ietf.org/doc/html/rfc2392) says:
```
content-id = url-addr-spec
url-addr-spec = addr-spec ; URL encoding of RFC 822 addr-spec
```
RFC-822 addr-spec (https://datatracker.ietf.org/doc/html/rfc822#appendix-D) says:
```
addr-spec = local-part "@" domain ; global address
```
In the same vein, as RFC-2392 (https://datatracker.ietf.org/doc/html/rfc2392) says:
```
A "cid" URL is converted to the corresponding Content-ID message
header [MIME] by removing the "cid:" prefix, converting the % encoded
character to their equivalent US-ASCII characters, and enclosing the
remaining parts with an angle bracket pair, "<" and ">".  
```

CXF-8698: Content-ID of attachments for outgoing requests are URL-decoded instead of URL-encoded

---

osgi/itests/src/test/java/org/apache/cxf/osgi/itests/BundlesAndNamespacesTest.java
osgi/itests/src/test/java/org/apache/cxf/osgi/itests/CXFOSGiTestSupport.java
osgi/itests/src/test/java/org/apache/cxf/osgi/itests/jaxrs/JaxRsServiceTest.java
osgi/itests/src/test/java/org/apache/cxf/osgi/itests/soap/HttpServiceTest.java
osgi/itests/src/test/java/org/apache/cxf/osgi/itests/soap/JmsServiceTest.java

When running pipeline, it is very likely that more than 1 build is run on the same runner, since OSGi tests use hardcoded port, the tests often conflict and fail the whole pipeline.

CXF-8730: Fix org.apache.cxf.osgi.itests.jaxrs.JaxRsServiceTest

---

core/src/main/java/org/apache/cxf/attachment/AttachmentUtil.java
core/src/test/java/org/apache/cxf/attachment/AttachmentSerializerDeserializerTest.java

After https://github.com/apache/cxf/pull/950, `Content-ID` of attachments for outgoing requests is not URL-decoded

CXF-8733: [regression] Content-ID of attachments for outgoing requests is not URL-decoded

---

rt/frontend/jaxrs/src/main/java/org/apache/cxf/jaxrs/utils/JAXRSUtils.java

The change in JAXRSUTils makes javax.activation.DataSource loaded whereas we did the work to make activation+jaxb optional in previous releases.

CXF-8732: [regression] activation DataSource requires to run JAXRS

---

core/src/main/java/org/apache/cxf/attachment/AttachmentSerializer.java
core/src/test/java/org/apache/cxf/attachment/AttachmentSerializerTest.java

Limiting decoding only to % encoded characters (as per  RFC-2392).
// A "cid" URL is converted to the corresponding Content-ID message
// header [MIME] by removing the "cid:" prefix, converting the % encoded
// character to their equivalent US-ASCII characters

CXF-8698: Content-ID of attachments for outgoing requests are URL-decoded instead of URL-encoded (limiting decoding only to % encoded characters)

---

rt/transports/http/src/main/java/org/apache/cxf/transport/http/auth/DigestAuthSupplier.java
rt/transports/http/src/test/java/org/apache/cxf/transport/http/auth/DigestAuthSupplierTest.java

DigestAuthSupplier currently decodes URL encoded URI parts. This breaks digest auth because servers do digest auth based of the still encoded URI.

[CXF-8761] DigestAuthSupplier: Must not decode URL encoded URI parts

---

core/src/main/java/org/apache/cxf/common/util/SortedArraySet.java
core/src/test/java/org/apache/cxf/common/util/SortedArraySetTest.java

Remove would fail when removing the not-lowest entry.
The implementation of `containsAll` was "containsAny".
Also tweaks `add` to use binary search + insert instead
of a full sort every time.

Fix SortedArraySet remove, containsAll

---

maven-plugins/pom.xml
maven-plugins/wadl2java-plugin/pom.xml
tools/pom.xml
tools/wadlto/jaxrs/pom.xml
tools/wadlto/jaxrs/src/test/java/org/apache/cxf/tools/wadlto/jaxrs/WADLToJavaTest.java
tools/wadlto/jaxrs/src/test/resources/wadl/test.xml

Migrating `cxf-wadl2java-plugin` & `cxf-tools-wadlto-jaxrs` modules. Temporary excluding ` jaxb2-basics` extensions till the equivalent Jakarta replacement becomes available.

Migrating cxf-wadl2java-plugin & cxf-tools-wadlto-jaxrs modules

---

parent/pom.xml
systests/microprofile/client/weld/pom.xml
systests/microprofile/client/weld/src/test/java/org/apache/cxf/microprofile/AnnotationTransformer.java
systests/microprofile/client/weld/src/test/java/org/apache/cxf/microprofile/RetryAnalyzer.java

Bringing back RetryAnalyzer to mitigate flaky Microprofile Rest Client TCK tests, mostly every build is failing:
- https://ci-builds.apache.org/job/CXF/job/CXF-JDK20/157/ 
- https://ci-builds.apache.org/job/CXF/job/CXF-JDK19/362/
- https://ci-builds.apache.org/job/CXF/job/CXF-JDK17/856/
- https://ci-builds.apache.org/job/CXF/job/CXF-JDK17-PR/129/
- ...

Bringing back RetryAnalyzer to mitigate flaky Microprofile Rest Client TCK tests

---

rt/transports/jms/src/test/java/org/apache/cxf/transport/jms/util/MessageListenerTest.java

The `org.apache.cxf.transport.jms.util.MessageListenerTest.testWithJTA` fails intermittently [1] with:
```
jakarta.jms.InvalidDestinationException: AMQ229017: Queue test does not exist
at org.apache.activemq.artemis.core.protocol.core.impl.ChannelImpl.sendBlocking(ChannelImpl.java:554)
at org.apache.activemq.artemis.core.protocol.core.impl.ChannelImpl.sendBlocking(ChannelImpl.java:446)
``` 
[1] https://ci-builds.apache.org/job/CXF/job/pipeline/job/main/141/testReport/junit/org.apache.cxf.transport.jms.util/MessageListenerTest/Build___Matrix___JAVA_VERSION____jdk_17_latest____JDK_specific_build___Build___Test___testWithJTA/

CXF-8795: Fix org.apache.cxf.transport.jms.util.MessageListenerTest.testWithJTA

---

parent/pom.xml
systests/wsdl_maven/codegen/src/it/settings.xml

This upgrade is important in order to be able to build CXF with maven 4.x.

Allow building with maven 4

---

parent/pom.xml

Reverting the update due to https://issues.apache.org/jira/browse/MRRESOURCES-121, the build is flooded with:
```
[WARNING] Failed to build parent project for io.netty:netty-buffer:jar:4.1.85.Final
[WARNING] Invalid project model for artifact [netty-buffer:io.netty:4.1.85.Final]. It will be ignored by the remote resources Mojo.
[WARNING] Failed to build parent project for io.netty:netty-transport:jar:4.1.85.Final
[WARNING] Invalid project model for artifact [netty-transport:io.netty:4.1.85.Final]. It will be ignored by the remote resources Mojo.
[WARNING] Failed to build parent project for io.netty:netty-resolver:jar:4.1.85.Final
[WARNING] Invalid project model for artifact [netty-resolver:io.netty:4.1.85.Final]. It will be ignored by the remote resources Mojo.
[WARNING] Failed to build …
```

Revert maven-remote-resources-plugin due to issues with the build

---

rt/transports/jms/src/test/java/org/apache/cxf/transport/jms/AbstractJMSTester.java

Fix `org.apache.cxf.transport.jms.RequestResponseTest` test cases which fail with `Can't receive the Conduit Message in 10 seconds`

Fix org.apache.cxf.transport.jms.RequestResponseTest test cases which fail with 'Can't receive the Conduit Message in 10 seconds'

---

parent/pom.xml
systests/ldap/pom.xml
systests/ldap/src/test/java/org/apache/cxf/systest/ldap/jaxrs/JAXRSLDAPUserTest.java
systests/ldap/src/test/java/org/apache/cxf/systest/ldap/sts/LDAPClaimsTest.java
systests/ldap/src/test/java/org/apache/cxf/systest/ldap/xkms/LDAPCertificateRepoTest.java
systests/ldap/src/test/resources/ldap.xml

The ApacheDS project is effectively dead (no releases since 2020), moreover it is not compatible with latest JDK-20+:
```
java.lang.NoSuchMethodError: 'void sun.security.x509.X509CertInfo.set(java.lang.String, java.lang.Object)'
at org.apache.directory.server.core.security.CertificateUtil.setInfo(CertificateUtil.java:96)
at org.apache.directory.server.core.security.CertificateUtil.generateSelfSignedCertificate(CertificateUtil.java:194)
at org.apache.directory.server.core.security.CertificateUtil.createTempKeyStore(CertificateUtil.java:337)
at org.apache.directory.server.factory.ServerAnnotationProcessor.instantiateLdapServer(ServerAnnotationProcessor.java:158)
at org.apache.directory.server.factory.ServerAnnotationProcessor.createLdapServer(ServerAnnotationProcessor.java:318)
at …
```

CXF-8809: Migrate LDAP systest cases from ApacheDS to UnboundID LDAP

---

distribution/src/main/release/samples/pom.xml
pom.xml

The last blocker (Spring Cloud release train) is now resolved

CXF-8788: Remove the 'jakarta' profile (which enables the Spring milestone repositories)

---

parent/pom.xml
rt/rs/microprofile-client/pom.xml
systests/microprofile/client/async/pom.xml
systests/microprofile/client/nocdi/pom.xml
systests/microprofile/client/weld/pom.xml

Migration path for Wiremock (Jetty 11/JakartaEE)

CXF-8758: Migration path for Wiremock (Jetty 11/JakartaEE)

---

core/src/main/java/org/apache/cxf/common/util/CompressionUtils.java
rt/security/src/main/java/org/apache/cxf/rt/security/crypto/CryptoUtils.java
rt/security/src/test/java/org/apache/cxf/rt/security/crypto/CryptoUtilsTest.java

As for now Deflater and Inflater initialized with different 'nowrap' value. As result we are getting the folowing Exeption:
```
java.lang.SecurityException: java.util.zip.DataFormatException: invalid stored block lengths
at org.apache.cxf.rt.security.crypto.CryptoUtils.processBytes(CryptoUtils.java:587)
at org.apache.cxf.rt.security.crypto.CryptoUtils.decryptBytes(CryptoUtils.java:483)
at org.apache.cxf.rs.security.jose.jwe.AbstractJweDecryption.doDecrypt(AbstractJweDecryption.java:72)
at org.apache.cxf.rs.security.jose.jwe.AbstractJweDecryption.decrypt(AbstractJweDecryption.java:57)
at org.apache.cxf.rs.security.jose.jwe.JweJsonConsumer.decryptWith(JweJsonConsumer.java:64)
```
This PR will fix the Jwe Compression by setting the 'nowrap' parameter for both Deflater and Inflater to 'true' …

Fix Jwe compression

---

services/xkms/xkms-x509-handlers/pom.xml

* Bump tycho-packaging-plugin from 0.26.0 to 2.7.5
Bumps [tycho-packaging-plugin](https://github.com/eclipse/tycho) from 0.26.0 to 2.7.5.
- [Release notes](https://github.com/eclipse/tycho/releases)
- [Changelog](https://github.com/eclipse-tycho/tycho/blob/master/RELEASE_NOTES.md)
- [Commits](https://github.com/eclipse/tycho/compare/tycho-0.26.0...tycho-2.7.5)
---
updated-dependencies:
- dependency-name: org.eclipse.tycho:tycho-packaging-plugin dependency-type: direct:production update-type: version-update:semver-major ...
Signed-off-by: dependabot[bot] <support@github.com>
* Add tycho-maven-plugin (needed by tycho-packaging-plugin)
---------
Signed-off-by: dependabot[bot] <support@github.com>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com> …

Bump tycho-packaging-plugin from 0.26.0 to 2.7.5 (#1126)

---

core/src/main/java/org/apache/cxf/attachment/AttachmentDataSource.java
core/src/main/java/org/apache/cxf/attachment/AttachmentDeserializer.java
core/src/main/java/org/apache/cxf/attachment/AttachmentUtil.java
core/src/main/java/org/apache/cxf/message/MessageUtils.java
core/src/test/java/org/apache/cxf/attachment/AttachmentDeserializerTest.java
rt/frontend/jaxrs/src/main/java/org/apache/cxf/jaxrs/ext/MessageContextImpl.java
rt/ws/security/src/main/java/org/apache/cxf/ws/security/wss4j/AttachmentCallbackHandler.java

Introducing new contextual property `org.apache.cxf.attachment.content-type` (`AttachmentUtil.ATTACHMENT_CONTENT_TYPE`) to use in case when content type is not present for attachment.

CXF-8669: Multipart annotation not working 3.4.6 onwards

---

rt/transports/http-hc/src/main/java/org/apache/cxf/transport/http/asyncclient/AsyncHTTPConduit.java
rt/transports/http-hc/src/test/java/org/apache/cxf/transport/http/asyncclient/AsyncHTTPConduitTest.java
rt/transports/http-hc5/src/main/java/org/apache/cxf/transport/http/asyncclient/hc5/AsyncHTTPConduit.java
rt/transports/http-hc5/src/test/java/org/apache/cxf/transport/http/asyncclient/hc5/AsyncHTTPConduitTest.java

AsyncHTTPConduit removes query-parameters when path is empty

CXF-8822: AsyncHTTPConduit removes query-parameters when path is empty

---

rt/transports/http-hc5/src/main/java/org/apache/cxf/transport/http/asyncclient/hc5/CXFHttpAsyncResponseConsumer.java
rt/transports/http-hc5/src/main/java/org/apache/cxf/transport/http/asyncclient/hc5/SharedInputBuffer.java

Fix org.apache.cxf.transport.http.asyncclient.hc5.AsyncHTTPConduitTest.testResponseSameBufferSize

CXF-8815: Fix org.apache.cxf.transport.http.asyncclient.hc5.AsyncHTTPConduitTest.testResponseSameBufferSize

---

rt/transports/http/src/main/java/org/apache/cxf/transport/http/HttpClientHTTPConduit.java
systests/jaxrs/src/test/java/org/apache/cxf/systest/jaxrs/reactive/AbstractCompletableFutureServer.java
systests/jaxrs/src/test/java/org/apache/cxf/systest/jaxrs/reactive/AbstractJAXRSCompletionStageTest.java
systests/jaxrs/src/test/java/org/apache/cxf/systest/jaxrs/reactive/CompletableFutureHttpServer.java
systests/jaxrs/src/test/java/org/apache/cxf/systest/jaxrs/reactive/CompletableFutureHttpsServer.java
systests/jaxrs/src/test/java/org/apache/cxf/systest/jaxrs/reactive/JAXRSCompletionStageHttpTest.java
systests/jaxrs/src/test/java/org/apache/cxf/systest/jaxrs/reactive/JAXRSCompletionStageHttpsTest.java
systests/jaxrs/src/test/java/org/apache/cxf/systest/jaxrs/reactive/reactive-https-client.xml
systests/jaxrs/src/test/java/org/apache/cxf/systest/jaxrs/reactive/reactive-https-server.xml

Fix NullPointerException when reactive clients are configured with SSL/TLS, add tests

Fix NullPointerException when reactive clients are configured with SSL/TLS, add tests

---

integration/cdi/src/main/java/org/apache/cxf/cdi/JAXRSCdiResourceExtension.java
systests/cdi/cdi-owb/cdi-producers-owb/src/test/java/org/apache/cxf/systest/jaxrs/cdi/BookStoreFeed.java
systests/cdi/cdi-owb/cdi-producers-owb/src/test/java/org/apache/cxf/systest/jaxrs/cdi/BookStoreProducerApplication.java
systests/cdi/cdi-owb/cdi-producers-owb/src/test/java/org/apache/cxf/systest/jaxrs/cdi/ServerFactoryDebugExtension.java
systests/cdi/cdi-owb/cdi-producers-owb/src/test/java/org/apache/cxf/systest/jaxrs/cdi/jetty/JettyEmbeddedTest.java
systests/cdi/cdi-owb/cdi-producers-owb/src/test/java/org/apache/cxf/systest/jaxrs/cdi/jetty/JettyWarTest.java
systests/cdi/cdi-owb/cdi-producers-owb/src/test/java/org/apache/cxf/systest/jaxrs/cdi/tomcat/TomcatWarTest.java

CDI beans produced by @Produces methods are generated twice

CXF-8824: CDI beans produced by @Produces methods are generated twice

---

pom.xml

Discovered when looking at the merge request proposal generated by Renovate Bot:
Where `(source)` points to https://gitbox.apache.org/repos/asf?p=cxf.git;a=summary (404).
My suggested change is taken from the CXF item in the list of repos on https://gitbox.apache.org/repos/asf.

Fix SCM URL in POM

---

rt/wsdl/pom.xml
rt/wsdl/src/test/java/org/apache/cxf/wsdl/interceptors/DocLiteralInInterceptorTest.java
rt/wsdl/src/test/java/org/apache/cxf/wsdl/service/factory/ReflectionServiceFactorBeanTest.java
rt/wsdl/src/test/java/org/apache/cxf/wsdl11/ServiceWSDLBuilderTest.java
rt/wsdl/src/test/java/org/apache/cxf/wsdl11/WSDLServiceBuilderTest.java

Get rid of EasyMock in `cxf-rt-wsdl`

CXF-8854: Get rid of EasyMock in cxf-rt-wsdl

---

rt/transports/http/pom.xml
rt/transports/http/src/test/java/org/apache/cxf/transport/http/DestinationRegistryImplTest.java
rt/transports/http/src/test/java/org/apache/cxf/transport/http/HTTPConduitURLEasyMockTest.java
rt/transports/http/src/test/java/org/apache/cxf/transport/http/HeadersTest.java
rt/transports/http/src/test/java/org/apache/cxf/transport/http/policy/PolicyUtilsTest.java
rt/transports/http/src/test/java/org/apache/cxf/transport/servlet/BaseUrlHelperTest.java
rt/transports/http/src/test/java/org/apache/cxf/transport/servlet/ServletControllerTest.java

Get rid of EasyMock in cxf-rt-transports-http

CXF-8890: Get rid of EasyMock in cxf-rt-transports-http

---

rt/transports/http-jetty/pom.xml
rt/transports/http-jetty/src/test/java/org/apache/cxf/transport/http_jetty/JettyHTTPDestinationTest.java
rt/transports/http-jetty/src/test/java/org/apache/cxf/transport/http_jetty/JettyHTTPServerEngineTest.java

Get rid of EasyMock in cxf-rt-transports-http-jetty

CXF-8876: Get rid of EasyMock in cxf-rt-transports-http-jetty

---

rt/ws/addr/pom.xml
rt/ws/addr/src/test/java/org/apache/cxf/ws/addressing/impl/ContextUtilsTest.java
rt/ws/addr/src/test/java/org/apache/cxf/ws/addressing/impl/MAPAggregatorTest.java
rt/ws/addr/src/test/java/org/apache/cxf/ws/addressing/soap/DecoupledFaultHandlerTest.java
rt/ws/addr/src/test/java/org/apache/cxf/ws/addressing/soap/MAPCodecTest.java

Get rid of EasyMock in cxf-rt-ws-addr

CXF-8862: Get rid of EasyMock in cxf-rt-ws-addr

---

rt/frontend/jaxws/pom.xml
rt/frontend/jaxws/src/test/java/org/apache/cxf/jaxws/JAXWSMethodInvokerTest.java
rt/frontend/jaxws/src/test/java/org/apache/cxf/jaxws/handler/AbstractProtocolHandlerInterceptorTest.java
rt/frontend/jaxws/src/test/java/org/apache/cxf/jaxws/handler/HandlerChainBuilderTest.java
rt/frontend/jaxws/src/test/java/org/apache/cxf/jaxws/handler/LogicalHandlerInterceptorTest.java
rt/frontend/jaxws/src/test/java/org/apache/cxf/jaxws/handler/soap/SOAPHandlerInterceptorTest.java
rt/frontend/jaxws/src/test/java/org/apache/cxf/jaxws/support/JaxWsServiceConfigurationTest.java
rt/frontend/jaxws/src/test/java/org/apache/cxf/transport/http_jaxws_spi/HttpHandlerImplTest.java
rt/frontend/jaxws/src/test/java/org/apache/cxf/transport/http_jaxws_spi/JAXWSHttpSpiDestinationTest.java
rt/frontend/jaxws/src/test/java/org/apache/cxf/transport/http_jaxws_spi/JAXWSHttpSpiTransportFactoryTest.java

Get rid of EasyMock in cxf-rt-frontend-jaxws

CXF-8857: Get rid of EasyMock in cxf-rt-frontend-jaxws

---

rt/databinding/aegis/pom.xml
rt/databinding/aegis/src/test/java/org/apache/cxf/aegis/type/mtom/DataSourceTypeTest.java

Get rid of EasyMock in cxf-rt-databinding-aegis

CXF-8847: Get rid of EasyMock in cxf-rt-databinding-aegis

---

rt/transports/http-netty/netty-server/pom.xml
rt/transports/http-netty/netty-server/src/test/java/org/apache/cxf/transport/http/netty/server/NettyHttpDestinationTest.java
rt/transports/http-netty/netty-server/src/test/java/org/apache/cxf/transport/http/netty/server/NettyHttpServerEngineTest.java

Get rid of EasyMock in cxf-rt-transports-http-netty-server

CXF-8878: Get rid of EasyMock in cxf-rt-transports-http-netty-server

---

rt/transports/websocket/pom.xml
rt/transports/websocket/src/test/java/org/apache/cxf/transport/websocket/jetty/JettyWebSocketDestinationTest.java

Get rid of EasyMock in cxf-rt-transports-websocket

CXF-8863: Get rid of EasyMock in cxf-rt-transports-websocket

---

rt/transports/http-netty/netty-client/pom.xml

Get rid of EasyMock in cxf-rt-transports-http-netty-client

CXF-8877: Get rid of EasyMock in cxf-rt-transports-http-netty-client

---

rt/ws/security/pom.xml
rt/ws/security/src/test/java/org/apache/cxf/ws/security/wss4j/AttachmentCallbackHandlerTest.java
rt/ws/security/src/test/java/org/apache/cxf/ws/security/wss4j/SecurityVerificationOutTest.java

Get rid of EasyMock in cxf-rt-ws-security

CXF-8859: Get rid of EasyMock in cxf-rt-ws-security

---

rt/ws/rm/pom.xml
rt/ws/rm/src/test/java/org/apache/cxf/ws/rm/AbstractEndpointTest.java
rt/ws/rm/src/test/java/org/apache/cxf/ws/rm/AbstractRMInterceptorTest.java
rt/ws/rm/src/test/java/org/apache/cxf/ws/rm/DestinationSequenceTest.java
rt/ws/rm/src/test/java/org/apache/cxf/ws/rm/DestinationTest.java
rt/ws/rm/src/test/java/org/apache/cxf/ws/rm/ManagedRMManagerTest.java
rt/ws/rm/src/test/java/org/apache/cxf/ws/rm/ProxyTest.java
rt/ws/rm/src/test/java/org/apache/cxf/ws/rm/RMContextUtilsTest.java
rt/ws/rm/src/test/java/org/apache/cxf/ws/rm/RMEndpointTest.java
rt/ws/rm/src/test/java/org/apache/cxf/ws/rm/RMInInterceptorTest.java
rt/ws/rm/src/test/java/org/apache/cxf/ws/rm/RMManagerTest.java
rt/ws/rm/src/test/java/org/apache/cxf/ws/rm/RMOutInterceptorTest.java
rt/ws/rm/src/test/java/org/apache/cxf/ws/rm/RMUtilsTest.java
rt/ws/rm/src/test/java/org/apache/cxf/ws/rm/ServantTest.java
rt/ws/rm/src/test/java/org/apache/cxf/ws/rm/SourceSequenceTest.java
rt/ws/rm/src/test/java/org/apache/cxf/ws/rm/persistence/jdbc/RMTxStoreTest.java
rt/ws/rm/src/test/java/org/apache/cxf/ws/rm/persistence/jdbc/RMTxStoreTestBase.java
rt/ws/rm/src/test/java/org/apache/cxf/ws/rm/persistence/jdbc/RMTxStoreTwoSchemasTest.java
rt/ws/rm/src/test/java/org/apache/cxf/ws/rm/policy/PolicyUtilsTest.java
rt/ws/rm/src/test/java/org/apache/cxf/ws/rm/soap/RetransmissionQueueImplTest.java
rt/ws/rm/src/test/java/org/apache/cxf/ws/rm/soap/SoapFaultFactoryTest.java

Get rid of EasyMock in cxf-rt-ws-rm

CXF-8860: Get rid of EasyMock in cxf-rt-ws-rm

---

rt/transports/http-hc/pom.xml
rt/transports/http-hc/src/test/java/org/apache/cxf/transport/http/asyncclient/ActivatorTest.java

Get rid of EasyMock in cxf-rt-transports-http-hc

CXF-8917: Get rid of EasyMock in cxf-rt-transports-http-hc

---

rt/frontend/jaxrs/src/main/java/org/apache/cxf/jaxrs/utils/JAXRSUtils.java

JAXRSUtils has a LazyClass reference to `javax.activation.Datasource`. Since we are using jakarta namespace for cxf4, we need to fix it.
The wrong reference is a problem for
`com.sun.ts.tests.jaxrs.spec.provider.standardnotnull.JAXRSClient#java#clientDataSourceProviderTest_from_standalone`
if running the ee9.1 plattform tck for TomEE.

CXF-8919 - JAXRSUtils references javax.activation.Datasource

---

core/src/test/java/org/apache/cxf/helpers/NameSpaceTest.java
core/src/test/java/org/apache/cxf/io/CachedStreamTestBase.java
core/src/test/java/org/apache/cxf/version/VersionTest.java
integration/jca/src/test/java/org/apache/cxf/jca/cxf/handlers/ObjectMethodInvocationHandlerTest.java
integration/jca/src/test/java/org/apache/cxf/jca/outbound/ManagedConnectionImplTest.java
rt/ws/rm/src/test/java/org/apache/cxf/ws/rm/DestinationSequenceTest.java
rt/ws/rm/src/test/java/org/apache/cxf/ws/rm/RMManagerTest.java
rt/ws/rm/src/test/java/org/apache/cxf/ws/rm/SourceSequenceTest.java
services/sts/sts-core/src/test/java/org/apache/cxf/sts/token/renewer/SAMLTokenRenewerTest.java
services/sts/systests/advanced/src/test/java/org/apache/cxf/systest/sts/renew/SAMLRenewUnitTest.java
systests/jaxrs/src/test/java/org/apache/cxf/systest/jaxrs/failover/AbstractFailoverTest.java
systests/jaxws/src/test/java/org/apache/cxf/systest/jaxws/CXF7990Test.java
systests/jaxws/src/test/java/org/apache/cxf/systest/jaxws/JaxWsClientThreadTest.java
systests/uncategorized/src/test/java/org/apache/cxf/systest/type_test/AbstractTypeTestClient3.java
tools/wsdlto/test/src/test/java/org/apache/cxf/tools/wsdlto/jaxws/CodeGenTest.java

I am working on research that investigates test smell refactoring in which we identify alternative implementations of test cases, study how commonly used these refactorings are, and assess how acceptable they are in practice. 
For example, the smell in [NameSpaceTest.java](https://github.com/apache/cxf/pull/1395/files#diff-222a3706aae4f8dd30c4e5e1953ed3d6fca3d04085e56e4bce43466369ed282c) occurs when inappropriate assertions, such as `assertFalse(nsDecl2.equals(nsDecl1));` are used, while there exist better alternatives, such as `assertNotEquals(nsDecl1, nsDecl2);`.
We would like to get your feedback on these particular test smells and their refactorings. Thanks in advance for your input.

Refactor assertFalse(equals()) using assertNotEquals & Refactor assertTrue(equals()) using assertEquals

---

rt/transports/http/src/main/java/org/apache/cxf/transport/http/HTTPConduit.java

There are additional potential references to the `HttpClientFacade` hidden in the property change listeners of `HTTPClientPolicy`. To prevent those from keeping the SelectorManager thread alive, the `HTTPConduit` now registers itself as a listener only via a `WeakReference`, so the conduit can be garbage collected even if the client policy is still referenced inside the SelectorManager thread.
This is an alternative to PR #1380, the `WeakReference` approach taken here allows the `HTTPClientPolicy` to change dynamically.

CXF-8885: Eliminate hard refs to `HttpClient` via `HTTPClientPolicy`

---

services/xkms/xkms-x509-handlers/pom.xml
services/xkms/xkms-x509-handlers/src/test/java/org/apache/cxf/xkms/x509/handlers/X509LocatorTest.java

Get rid of EasyMock in cxf-services-xkms-x509-handlers

CXF-8853: Get rid of EasyMock in cxf-services-xkms-x509-handlers

---

rt/features/logging/src/main/java/org/apache/cxf/ext/logging/LoggingOutInterceptor.java
rt/features/logging/src/test/java/org/apache/cxf/ext/logging/FaultTest.java
rt/features/logging/src/test/java/org/apache/cxf/ext/logging/LogEventSenderMock.java

Fixing CXF-8925 the same way LoggingInInterceptor prevents double logging, by using the LIVE_LOGGING_PROP to disable logging once the message has been handled once.

[CXF-8925] Prevent double logging on fault in out chain

---

tools/wsdlto/frontend/jaxws/src/main/java/org/apache/cxf/tools/wsdlto/frontend/jaxws/template/service.vm

The cxf-codegen-plugin converts a WSDL into java classes, among them the class for the Jax-WS Service.
In the template some class members have the modifiers "public final static". The java standard recommends them to be in the order "public static final"
> If two or more (distinct) field modifiers appear in a field
declaration, it is customary, though not required, that they appear in the order consistent with that shown above in the production for FieldModifier. –
https://docs.oracle.com/javase/specs/jls/se20/html/jls-8.html#jls-8.3.1
If the generated source code is checked in to source control it is common that it will be analyzed using checkstyle, Teamscale and other linters. To reduce linter complaints the order should be changed.

CXF-8928: Reduce code quality warnings in generated code

---

maven-plugins/codegen-plugin/pom.xml
maven-plugins/corba/pom.xml
maven-plugins/java2wadl-plugin/pom.xml
maven-plugins/wadl2java-plugin/pom.xml

Plugins are not working on JDK11 and eagerly bring Spring dependencies
```
[INFO] Plugin Resolved: cxf-codegen-plugin-4.0.3.jar
[INFO]     Plugin Dependency Resolved: plexus-utils-3.5.1.jar
[INFO]     Plugin Dependency Resolved: plexus-archiver-4.8.0.jar
[INFO]     Plugin Dependency Resolved: cxf-core-4.0.3.jar
[INFO]     Plugin Dependency Resolved: cxf-tools-common-4.0.3.jar
[INFO]     Plugin Dependency Resolved: cxf-tools-wsdlto-core-4.0.3.jar
[INFO]     Plugin Dependency Resolved: cxf-tools-wsdlto-databinding-jaxb-4.0.3.jar
[INFO]     Plugin Dependency Resolved: cxf-tools-wsdlto-frontend-jaxws-4.0.3.jar
[INFO]     Plugin Dependency Resolved: cxf-tools-wsdlto-frontend-javascript-4.0.3.jar
[INFO]     Plugin Dependency Resolved: spring-core-6.0.11.jar
[INFO]     Plugin Dependency …
```

CXF-8932: Plugins are not working on JDK11 and eagerly bring Spring dependencies

---

rt/transports/http-jetty/src/main/java/org/apache/cxf/transport/http_jetty/JettyHTTPServerEngine.java

I have been trying to update one of our apps using the Jetty backend to use http2. While doing this I've noticed that the protocol negotiation is in the wrong order which results in http/1.1 always being preferred where the client includes this in the ALPN handshake. This means that both browsers and cURL will never successfully negotiate h2/http2.
https://issues.apache.org/jira/browse/CXF-8936
[output-jetty-original.txt](https://github.com/apache/cxf/files/12729574/output-jetty-original.txt)
[output-netty.txt](https://github.com/apache/cxf/files/12729575/output-netty.txt)

CXF-8936 Fix h2 protocol negotiation in Jetty Transport

---

rt/features/logging/src/main/java/org/apache/cxf/ext/logging/event/DefaultLogEventMapper.java

[CXF-8939] java.lang.NullPointerException: Cannot invoke "java.util.List.size()" because the return value of "java.util.Map$Entry.getValue()" is null
https://issues.apache.org/jira/browse/CXF-8939

[CXF-8939] NullPointerException: Cannot invoke "java.util.List.size()"

---

rt/transports/http-jetty/src/main/java/org/apache/cxf/transport/http_jetty/JettyHTTPServerEngine.java
rt/transports/http-jetty/src/main/java/org/apache/cxf/transport/http_jetty/JettyHTTPServerEngineFactory.java

Always create MBeanServer instance per Jetty Server instance and destroy server properly at shutdown

CXF-8954: Always create MBeanServer instance per Jetty Server instance and destroy server properly at shutdown

---

rt/transports/http-hc/src/main/java/org/apache/cxf/transport/http/asyncclient/AsyncHTTPConduit.java
rt/transports/http-hc/src/main/java/org/apache/cxf/transport/http/asyncclient/AsyncHttpResponseWrapperFactory.java
rt/transports/http-hc/src/test/java/org/apache/cxf/transport/http/asyncclient/AsyncHTTPConduitTest.java
rt/transports/http-hc5/src/main/java/org/apache/cxf/transport/http/asyncclient/hc5/AsyncHTTPConduit.java
rt/transports/http-hc5/src/main/java/org/apache/cxf/transport/http/asyncclient/hc5/AsyncHttpResponseWrapperFactory.java
rt/transports/http-hc5/src/test/java/org/apache/cxf/transport/http/asyncclient/hc5/AsyncHTTPConduitTest.java

Allow wrapping AsyncHTTPConduit response processing (using new AsyncHttpResponseWrapperFactory bus extension)

CXF-8911: Allow wrapping AsyncHTTPConduit response processing (using new AsyncHttpResponseWrapperFactory bus extension)

---

core/src/main/java/org/apache/cxf/io/CachedOutputStream.java
core/src/test/java/org/apache/cxf/attachment/AttachmentUtilTest.java
core/src/test/java/org/apache/cxf/io/CachedOutputStreamTest.java
core/src/test/java/org/apache/cxf/io/CachedStreamTestBase.java

**Description**
Fixed the order dependent flaky test in AttachmentUtilTest.java in core module.
**Root Cause**
The polluter that caused the flakiness in `AttachmentUtilTest.java` was the test class `CachedOutputStreamTest.java`. In `AttachmentUtilTest`, there were multiple tests that used Mockito.spy() to verify the behavior of `CachedOutputStream` object. In those tests, the spy `CachedOutputStream` object "cos" was generated (`CachedOutputStream cos = spy(CachedOutputStream.class`). Then after this, there was a line `verify(cos).setThreshold(102400L)`. Therefore, after the cos being initialized, we need to make sure the setThreshold has been called once. However, it doesn't execute as expected, and the root cause is that 
1. the threshold is not provided when calling …

[CXF-8959] Fixed order dependent flakiness in AttachmentUtilTest.java in core module

---

rt/transports/http-netty/netty-client/src/main/java/org/apache/cxf/transport/http/netty/client/NettyHttpClientRequest.java
rt/transports/http-netty/netty-client/src/test/java/org/apache/cxf/transport/http/netty/client/NettyHttpClientRequestTest.java
systests/transport-hc5/src/test/java/org/apache/cxf/systest/hc5/http2/AbstractApacheClientServerHttp2Test.java
systests/transport-hc5/src/test/java/org/apache/cxf/systest/hc5/http2/BookStore.java
systests/transport-netty/src/test/java/org/apache/cxf/systest/http2/netty/AbstractNettyClientServerHttp2Test.java
systests/transport-netty/src/test/java/org/apache/cxf/systest/http2/netty/BookStore.java

Used getRawPath of URI instead of getPath to ensure that URL encoding is happening for the path as well

[CXF-8965] Apache CXF Netty Integration, URI not encoded

---

rt/frontend/jaxrs/src/test/java/org/apache/cxf/jaxrs/utils/JAXBUtilsTest.java

Fixed the flaky test `extendedXmlJavaTypeAdapter` and `simpleXmlJavaTypeAdapter`  inside `JAXBUtilsTest.java` class. 
https://github.com/apache/cxf/blob/b608027f5f352affd3d2228ae4733b47049f2590/rt/frontend/jaxrs/src/test/java/org/apache/cxf/jaxrs/utils/JAXBUtilsTest.java#L38
https://github.com/apache/cxf/blob/b608027f5f352affd3d2228ae4733b47049f2590/rt/frontend/jaxrs/src/test/java/org/apache/cxf/jaxrs/utils/JAXBUtilsTest.java#L43
The tests `extendedXmlJavaTypeAdapter` and `simpleXmlJavaTypeAdapter` have been reported flaky when run with the [NonDex](https://github.com/TestingResearchIllinois/NonDex) tool. The tests failed due to the non-deterministic ordering of fields returned by getDeclaredFields(). The getDeclaredFields() method returns an array of Field objects representing all the …

fix flaky tests

---

systests/cdi/cdi-owb/cdi-producers-owb/src/test/java/org/apache/cxf/systest/jaxrs/cdi/unwrapper/ClassUnwrapperTest.java

The test class `ClassUnwrapperTest` tries to load the `lifecycle`, `bus` and `event` before every test runs in this test class.
For `event`, the test class `ServletContextEvent` creates it with a mocked class and it is only used when starting the application using `lifecycle`.
For `lifecycle`, it is only used to start an application with the `event` and called with `getBeanManager()`.
For `bus`, it is only used to get certain properties of certain class name.
For all these three fields, the two tests inside the `ClassUnwrapperTest` are not trying to modify them but just accessing them. Repeatly creating `lifecycle`, `bus` and `event` object will increase the cost of running tests. When run on our own machine, the test runtime can jump from `5.4858 s` to `4.5919 s` after applying the …

only load the lifecycle, bus and event once to make test faster

---

integration/tracing/tracing-opentelemetry/src/main/java/org/apache/cxf/tracing/opentelemetry/OpenTelemetryClientFeature.java

https://issues.apache.org/jira/browse/CXF-8968

CXF-8968: OpenTelemetryClientFeature cannot be used as a CDI bean unless it has a no-args constructor

---

pom.xml

At the moment, we always generate SBOMs on every build, it significantly slows the builds down. The suggestion is to generate SBOMs at deploy / release time only, when we really need those artifacts to be published (somewhat Inspired by Apache Camel approach https://github.com/apache/camel/blob/main/pom.xml#L801)

Scoped SBOM (cyclonedx-maven-plugin) to release and deploy Apache Maven profiles only

---

maven-plugins/codegen-plugin/pom.xml

Remove Maven profile 'ibmjdk' containing invalid Xerces dependency declaration. Dependency to Xerces was removed with CXF-8912.

CXF-8978: Codegen plugin fails with IBM JDK

---

rt/transports/http/src/main/java/org/apache/cxf/transport/http/Headers.java
rt/transports/http/src/main/java/org/apache/cxf/transport/http/HttpClientHTTPConduit.java
systests/jaxrs/src/test/java/org/apache/cxf/systest/jaxrs/EmptyBookServer.java
systests/jaxrs/src/test/java/org/apache/cxf/systest/jaxrs/EmptyBookStore.java
systests/jaxrs/src/test/java/org/apache/cxf/systest/jaxrs/JAXRSClientServerEmptyBookTest.java

Add support of `set.content.type.for.empty.request` contextual property to `HttpClientHTTPConduit`

CXF-8962: HttpClientHTTPConduit sets Content-Type Header for DELETE requests with empty body

---

rt/features/logging/src/main/java/org/apache/cxf/ext/logging/MaskSensitiveHelper.java
rt/features/logging/src/test/java/org/apache/cxf/ext/logging/MaskSensitiveHelperTest.java

This is a proposal fix for CXF-8982. The request also contains a new test case to assess it works as expected without breaking anything else.
By changing the regexp, the MaskSensitiveHelper supports masking XML element values where the element contains a namespace prefix without changing the semantics or the intention of the class.

[CXF-8982] add optional namespace prefix in template

---

services/sts/systests/basic/src/test/java/org/apache/cxf/systest/sts/stsclient/AbstractSTSTokenTest.java
services/sts/systests/basic/src/test/java/org/apache/cxf/systest/sts/transport/TransportBindingTest.java

AbstractSTSTokenTest and TransportBindingTests no longer need to set https protocol to TLSv1 on IBM Java.
Current builds of CXF 4.0.x on IBM Java will fail the AbstractSTSTokenTest and TransportBindingTests due to their use of TLSv1. Note: IBM JDKs disable TLSv1 by default since around Java 8 (https://community.ibm.com/community/user/wasdevops/blogs/hiroko-takamiya1/2021/06/19/ibm-java-80630-disables-tlsv1-tlsv11-by-default-ho).
Removing the test case IBM control flag allows the default TLS to pass the tests.
Patch tested on:
CentOS Stream 9 on POWER with IBM Semeru 17, RedHat OpenJDK 17, and Eclipse Adoptium (Temurin) 17.
Windows 11 Pro on x64 Intel with IBM Semeru 17, and Azul Zulu 17.
MacOS 14.4.1 on AArch64 with IBM Semeru 17, and Amazon Corretto 17.

[CXF-8997] AbstractSTSToken and TransportBinding Tests use TLSv1 on IBM

---

core/pom.xml
core/src/main/java/org/apache/cxf/common/util/CglibProxyHelper.java
core/src/test/java/org/apache/cxf/common/injection/ResourceInjectorTest.java
core/src/test/java/org/apache/cxf/common/util/ClassHelperTest.java
distribution/javadoc/pom.xml
distribution/src/main/release/samples/ruby_spring_support/pom.xml
parent/pom.xml
rt/rs/client/pom.xml
rt/rs/microprofile-client/pom.xml
systests/jaxrs/pom.xml
systests/rs-security/pom.xml
systests/transport-hc5/pom.xml
systests/uncategorized/pom.xml

The cglib [1] is not actively developed anymore and haven't seen any releases since 2019. It does not work with baselines of JDK-17 or above (since it shades old ASM version):
```
java.lang.IllegalArgumentException: Unsupported class file major version 61 at net.sf.cglib.asm.$ClassReader.<init>(ClassReader.java:195) at net.sf.cglib.asm.$ClassReader.<init>(ClassReader.java:176) at net.sf.cglib.asm.$ClassReader.<init>(ClassReader.java:162) at net.sf.cglib.asm.$ClassReader.<init>(ClassReader.java:283) at net.sf.cglib.core.DuplicatesPredicate.<init>(DuplicatesPredicate.java:93) at net.sf.cglib.proxy.Enhancer.getMethods(Enhancer.java:557) at net.sf.cglib.proxy.Enhancer.generateClass(Enhancer.java:575) at net.sf.cglib.core.DefaultGeneratorStrategy.generate(DefaultGeneratorStrategy.java:25) at …
```

CXF-8993: Migrate from net.sf.cglib (cglib) to org.springframework.cglib (spring)

---

rt/rs/security/jose-parent/jose/src/main/java/org/apache/cxf/rs/security/jose/common/JoseConstants.java
rt/rs/security/jose-parent/jose/src/main/java/org/apache/cxf/rs/security/jose/jwe/JweUtils.java
rt/rs/security/jose-parent/jose/src/main/java/org/apache/cxf/rs/security/jose/jwe/PbesHmacAesWrapKeyDecryptionAlgorithm.java
rt/rs/security/jose-parent/jose/src/test/java/org/apache/cxf/rs/security/jose/jwe/JwePbeHmacAesWrapTest.java

Default to 1_000_000 as the max value allowed by default for the Jose P2C parameter as per https://bitbucket.org/connect2id/nimbus-jose-jwt/commits/3b3b77e

Put a max default configurable limit on the Jose P2C parameter

---

rt/rs/extensions/search/src/main/java/org/apache/cxf/jaxrs/ext/search/Beanspector.java

JAXRS Bean introspection utility Beanspector relies on Class.getMethods natural order.
For most JVMs the Beanspector Tests will pass, however IBM Java does not return methods in the same ordering. Note: Class.getMethods does not provide a prescribed ordering of methods.
When CXF 4.0.x main branch is built, we'll observe Apache CXF JAX-RS Extensions: Search fails test cases.
We can improve this behaviour by detecting when IBM Java is in use, and having IBM process declared methods first, then process remaining methods. This will make IBM behave more like other JVMs. 
Branch Tested on: 
Windows 11 Pro (Intel) with IBM Semeru 17.
MacOS 14.4.1 (AArch64) with IBM Semeru 17, Bellsoft 17, and Zulu 17.
CentOS Stream 9  (POWER) with IBM Semeru 17, RedHat OpenJDK 17, and Temurin 17.

[CXF-8996] JAXRS Bean introspection utility Beanspector improvement

---

rt/transports/http/src/main/java/org/apache/cxf/transport/http/HttpClientHTTPConduit.java
systests/jaxrs/src/test/java/org/apache/cxf/systest/jaxrs/JAXRS20ClientServerBookTest.java
systests/transports/src/test/java/org/apache/cxf/systest/https/conduit/HTTPSConduitTest.java

Concurrent `WebClient` usage causes massive thread overhead. The suggested fix is to share the `HttpClient` instance (with reference counting) between many `HTTPConduit`s based on:
- client policy 
- TLS client parameters 
The shared `HttpClient` instances (references) are stored in the static cache capped at 100 (I believe the value is reasonably high taking into account that creation of many client `HTTPConduit`s, each with different policy and TLS settings is highly unlikely). The cache is thread safe and uses array list under the hood (switching to `ConcurrentHashMap` or alike was considered but requires more coding efforts and larger heap footprint which for a collection of 100 elements seems to be not beneficial). 
The client per conduit behaviour  could be forced by setting …

CXF-8951: Concurrent WebClient usage causes massive thread overhead

---

core/src/main/java/org/apache/cxf/transport/common/gzip/GZIPOutInterceptor.java

I use a custom feature to retry a client request if it fails. Unfortunately, on each attempt, the `Content-Encoding` header is modified to add `gzip`, giving `Content-Encoding: gzip,gzip` on the 2nd attempt.
I've added a small check before adding the value to the header, to make sure it's not already defined with the expected value.

Add check to prevent redundant values in headers when using GZIPOutInterceptor

---

benchmark/performance/base/pom.xml
benchmark/performance/soap_http_doc_lit/pom.xml
benchmark/performance/soap_http_doc_lit/src/main/java/org/apache/cxf/performance/complex_type/common/KeystorePasswordCallback.java

Tested on:
MacOS 14.4.1, M2 Max, IBM Semeru 17 & Azul Zulu 17, Maven 3.9.5.
Windows 11 Pro, Intel, IBM Semeru 17, Maven 3.9.5
Ubuntu 22.04 LTS, Intel, Eclipse Adoptium 17, Maven 3.9.5
CentOS Stream 9, PPC64LE, Eclipse Adoptium 17 & IBM Semeru 17, Maven 3.9.6

[CXF-9010] Update benchmark soap http doc lit suite for CXF 4.1.x

---

tools/wsdlto/frontend/jaxws/src/main/java/org/apache/cxf/tools/wsdlto/frontend/jaxws/template/service.vm

- Modified `service.vm` template to use `URI.create` factory method to parse `$wsdlLocation`.
- Convert back to `URI` since `jakarta.xml.ws.Service` only accepts a `URL`
Targets `main`, but I think it can be backported to `4.0.x-fixes` as well.

CXF-9011: WSDLTo JAXWS Frontend service.vm Velocity template uses deprecated URL constructor

---

rt/transports/http/src/main/java/org/apache/cxf/transport/http/HttpClientHTTPConduit.java

JDK 21+:  HttpClientHTTPConduit thread locked during shutdown

CXF-8987: JDK 21+: HttpClientHTTPConduit thread locked during shutdown

---

rt/frontend/jaxws/src/test/java/org/apache/cxf/jaxws/spi/ProviderImplTest.java
rt/frontend/jaxws/src/test/java/org/apache/cxf/jaxws/spi/WrapperClassCreatorProxyServiceTest.java
rt/frontend/jaxws/src/test/java/org/apache/cxf/jaxws/spi/WrapperClassLoaderTest.java

The provided unit test enhancement helps provide wider coverage of ProviderImpl, and introduces coverage to the WrapperClassLoader.  
In ProviderImpl we add test cases for most methods - we do not dive too deep into underlying objects/services - those have their own unit tests to assert correctness.
In the case of WrapperClassLoader we mock the class loader behavoir in order to exercise the generate and createWrapperClass functionality.

[CXF-9019] Jaxws spi unit test coverage enhancement.

---

rt/rs/extensions/json-basic/src/main/java/org/apache/cxf/jaxrs/json/basic/JsonMapObjectReaderWriter.java

The JsonMapObjectReaderWriter class maintains a list of [ESCAPED_CHARS](https://github.com/apache/cxf/blob/main/rt/rs/extensions/json-basic/src/main/java/org/apache/cxf/jaxrs/json/basic/JsonMapObjectReaderWriter.java#L45-L56) which includes special characters that need to be escaped like the newline (`\n`) and tab (`\t`) characters. This list also includes `\h`, but I can't find any links to official documentation about this character needing to be escaped. 
According to this [SO post](https://stackoverflow.com/a/27516892) which details escaped characters in JSON, it also does not include `\h` in this list. 
I'm opening a PR to discuss removing this from the list. 
Issue in OpenSearch where this issue is discussed: https://github.com/opensearch-project/security/issues/2531#issuecomment-211 …

Remove h from ESCAPED_CHARS in JsonMapObjectReaderWriter

---

rt/transports/http-netty/netty-client/src/main/java/org/apache/cxf/transport/http/netty/client/NettyHttpClientPipelineFactory.java
rt/transports/http-netty/netty-client/src/main/java/org/apache/cxf/transport/http/netty/client/NettyHttpConduit.java
systests/transport-netty/pom.xml
systests/transport-netty/src/test/java/org/apache/cxf/systest/http2/netty/jaxws/JAXWSAsyncClientTest.java

Async operations fails (netty-conduit)

CXF-9009: Async operations fails (netty-conduit)

---

rt/transports/http/src/main/java/org/apache/cxf/transport/http/HttpClientHTTPConduit.java
systests/jaxrs/src/test/java/org/apache/cxf/systest/jaxrs/JAXRS20ClientServerBookTest.java

The original issue was describing the case when WebClient instance is created per thread. However, there is another case when single instance of WebClient is used from many thread, that also led to  massive thread overhead.

CXF-8951: Concurrent WebClient usage causes massive thread overhead (the case when single instance of WebClient is used from many threads)

---

core/src/main/java/org/apache/cxf/helpers/DOMUtils.java
systests/transport-hc5/pom.xml
systests/transport-hc5/src/test/java/org/apache/cxf/systest/hc5/jaxws/JAXWSAsyncClientTest.java
systests/transport-hc5/src/test/resources/org/apache/cxf/systest/hc5/jaxws/greeting.wsdl

NullPointerException in XMLStreamDataWriter.writeNode

CXF-9007: NullPointerException in XMLStreamDataWriter.writeNode

---

parent/pom.xml

The current Artemis version is pulling a vulnerable Commons Configuration2 version into the lib folder...

Updating Artemis to 2.35.0

---

rt/features/logging/src/main/java/org/apache/cxf/ext/logging/event/DefaultLogEventMapper.java

As reported by [JDK 23 release notes](https://jdk.java.net/23/release-notes#JDK-8296244):
> The terminally deprecated method Subject.getSubject(AccessControlContext) has been re-specified to throw UnsupportedOperationException if invoked when a Security Manager is not allowed.
The proposed change allows to run flawlessly under JDK 23.

Allow JDK23 compatibility for Subject#getSubject

---

rt/management/src/test/java/org/apache/cxf/management/InstrumentationManagerTest.java
services/sts/sts-core/src/test/java/org/apache/cxf/sts/operation/ValidateJWTTransformationTest.java
systests/jaxws/src/test/java/org/apache/cxf/systest/dispatch/DispatchClientServerTest.java

Fixes https://issues.apache.org/jira/browse/CXF-9042
Some unit tests are non-idempotent, as they pass in the first run but fail in the second run in the same environment. A fix is necessary since unit tests shall be self-contained, ensuring that the state of the system under test is consistent at the beginning of each test. In practice, fixing non-idempotent tests can help proactively avoid state pollution that results in test order dependency (which could cause problems under test selection, prioritization or parallelization).
Using the `NIOInspector` plugin that supports rerunning JUnit tests in the same environment. Use `org.apache.cxf.management.InstrumentationManagerTest#testWorkQueueInstrumentation` as an example:
```
cd rt/management
mvn edu.illinois:NIOInspector:rerun …
```

[CXF-9042] Fixed non-idempotent unit tests

---

maven-plugins/java2wadl-plugin/pom.xml

Fix enforcer violation due to update to latest maven-javadoc-plugin 3.10.0:
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-enforcer-plugin:3.5.0:enforce (enforce-maven) on project cxf-coverage-report: 
[ERROR] Rule 2: org.apache.maven.enforcer.rules.dependency.BannedDependencies failed with message:
[ERROR] org.apache.cxf:cxf-coverage-report:pom:4.1.0-SNAPSHOT
[ERROR]    org.apache.cxf:cxf-java2wadl-plugin:jar:4.1.0-SNAPSHOT
[ERROR]       org.apache.maven.plugins:maven-javadoc-plugin:jar:3.10.0
[ERROR]          org.apache.maven.doxia:doxia-site-renderer:jar:2.0.0-M19
[ERROR]             org.eclipse.sisu:org.eclipse.sisu.plexus:jar:0.9.0.M2
[ERROR]                javax.annotation:javax.annotation-api:jar:1.2 <--- banned via the exclude/include list
[ERROR] -> [Help 1] …
```

Fix enforcer violation due to update to latest maven-javadoc-plugin 3.10.0

---

integration/tracing/tracing-opentelemetry/pom.xml
integration/tracing/tracing-opentelemetry/src/main/java/org/apache/cxf/tracing/opentelemetry/AbstractOpenTelemetryClientProvider.java
integration/tracing/tracing-opentelemetry/src/main/java/org/apache/cxf/tracing/opentelemetry/AbstractOpenTelemetryProvider.java
integration/tracing/tracing-opentelemetry/src/main/java/org/apache/cxf/tracing/opentelemetry/OpenTelemetryStartInterceptor.java
integration/tracing/tracing-opentelemetry/src/main/java/org/apache/cxf/tracing/opentelemetry/jaxrs/OpenTelemetryProvider.java
systests/tracing/src/test/java/org/apache/cxf/systest/jaxrs/tracing/opentelemetry/OpenTelemetryTracingTest.java
systests/tracing/src/test/java/org/apache/cxf/systest/jaxws/tracing/opentelemetry/OpenTelemetryTracingTest.java

* Add missing span attributes to comply with [OpenTelemetry semantic conventions](https://opentelemetry.io/docs/specs/semconv/http/http-spans/)
* Test the span attribute names and values
* Couldn't add the attributes "network.protocol.version" for the client http span, because we didn't find a way to find its value.
Link to the Jira ticket: [CXF-9055 Follow OpenTelemetry semantic conventions for trace span and its attributes ](https://issues.apache.org/jira/browse/CXF-9055)

CXF-9055 Follow OpenTelemetry semconv for trace span and its attributes

---

distribution/src/main/release/samples/jax_rs/tracing_micrometer/pom.xml
distribution/src/main/release/samples/jax_rs/tracing_opentelemetry/pom.xml
distribution/src/main/release/samples/jax_rs/tracing_opentracing/pom.xml
distribution/src/main/release/samples/pom.xml

Extract Openfeign version to samples/pom.xml in order to simplify dependency updates / backports

Extract Openfeign version to samples/pom.xml in order to simplify dependency updates / backports

---

tools/wsdlto/frontend/jaxws/src/main/java/org/apache/cxf/tools/wsdlto/frontend/jaxws/template/service.vm

This silences a Java 20+ warning also for those who still use CXF 3.x.
This is not my commit, I just backmerged it from `main`. Alternatively to merging this PR, you could merge from `main` too.

Backmerge commit 17d58fb767 to branch `3.6.x-fixes`: Use URI factory to parse WSDL location (#1858)

---

tools/wsdlto/frontend/jaxws/src/main/java/org/apache/cxf/tools/wsdlto/frontend/jaxws/template/service.vm

- Modified `service.vm` template  to only import `java.net.URI` when necessary to avoid unused import warnings

CXF-9060 Only import java.net.URI when necessary to avoid unused import warnings

---

rt/transports/http/src/main/java/org/apache/cxf/transport/http/HTTPConduit.java
rt/transports/http/src/main/java/org/apache/cxf/transport/http/HttpClientHTTPConduit.java

HttpConduit should flush output stream ahead of closing connections when HttpClient is autocloseable.
When running WebClient in a load test (single host) we'll observe low throughput.
When we adjust the HttpConduit to flush output stream ahead of connection close, we observe significant throughput improvement. 
Given this appears to affect just autocloseable HttpClient, we select to flush the output stead only when the JVM provides the autocloseable HttpClient variety.
Tested on:
Ubuntu 22.04 LTS with Java 17 and 21.
CentOS Stream 9 (PPC64LE) with Java 17 and 21.
Windows 11 Pro (x64) with Java 17 and 21.
MacOS 14.6.1 with Java 17 and 21.
Notes: 
Azul Zulu and Eclipse Adoptium used for OpenJDK builds.
IBM Semeru used for OpenJ9 coverage.

[CXF-9059] HttpConduit should flush output stream 

---

core/pom.xml
core/src/main/java/org/apache/cxf/bus/extension/ExtensionManagerBus.java
core/src/main/java/org/apache/cxf/io/CachedConstants.java
core/src/main/java/org/apache/cxf/io/CachedOutputStream.java
core/src/main/java/org/apache/cxf/io/CachedOutputStreamCleaner.java
core/src/main/java/org/apache/cxf/io/DelayedCachedOutputStreamCleaner.java
core/src/main/resources/META-INF/cxf/bus-extensions.txt
core/src/test/java/org/apache/cxf/io/DelayedCachedOutputStreamCleanerTest.java
parent/pom.xml
systests/jaxws/src/test/java/org/apache/cxf/systest/jaxws/ClientServerTest.java

`CachedOutputStream` doesn't delete temp files. it turned out to be very challenging to handle all the edge (and non-edge) cases where `CachedOutputStream`s  (or derived) streams stay unclosed. This change does not solve the root cause of the problem but offers at least a mitigation strategy in a shape of `CachedOutputStreamCleaner` that tracks unclosed `CachedOutputStream`s  (or derived) streams and periodically tries to close those out.

CXF-7396: CachedOutputStream doesn't delete temp files

---

rt/features/logging/src/main/java/org/apache/cxf/ext/logging/MaskSensitiveHelper.java
rt/features/logging/src/test/java/org/apache/cxf/ext/logging/MaskSensitiveHelperTest.java

- Update the regex pattern in `MATCH_PATTERN_XML_TEMPLATE` to strictly match the element name, avoiding incorrect matches with similar names.
- Add new test cases in `MaskSensitiveHelperTest` to verify the correct masking of sensitive data within wrapper elements.

[CXF-9067] Fix MaskSensitiveHelper incorrectly matching wrapper element

---

integration/cdi/src/main/java/org/apache/cxf/cdi/CdiServerConfigurableFactory.java
integration/cdi/src/main/java/org/apache/cxf/cdi/JAXRSCdiResourceExtension.java

BeanManager#fireEvent got deprecated in CDI-2.0 (2016) and in CDI-4.0 it gets finally removed.
Note that this patch is only for CXF-4.0.x. The changes are already applied in CXF-4.1.0 on the main branch.

CXF-9071 rework deprecated CDI method

---

rt/transports/http/src/main/java/org/apache/cxf/transport/http/HttpClientHTTPConduit.java
systests/transports/src/test/java/org/apache/cxf/systest/https/conduit/HTTPSConduitTest.java

Fix problem in https communication, when Java HttpClient is used and custom SSLContext is registered in TLSClientParameters. See [CXF-9074]( https://issues.apache.org/jira/browse/CXF-9074)

[CXF-9074] Fix problem with custom SSLContext in TLSClientParameters

---

rt/transports/http-hc/src/main/java/org/apache/cxf/transport/http/asyncclient/AsyncHTTPConduit.java
rt/transports/http-hc/src/main/java/org/apache/cxf/transport/http/asyncclient/URLConnectionAsyncHTTPConduit.java
rt/transports/http-hc5/src/main/java/org/apache/cxf/transport/http/asyncclient/hc5/AsyncHTTPConduit.java
rt/transports/http-hc5/src/main/java/org/apache/cxf/transport/http/asyncclient/hc5/URLConnectionAsyncHTTPConduit.java

AsyncHTTPConduit doesn't close copied wrappedStream on close

CXF-9064: AsyncHTTPConduit doesn't close copied wrappedStream on close

---

core/src/main/java/org/apache/cxf/endpoint/ClientImpl.java

Hi,
We are facing a random crash in our tests in `ClientImpl` with the following stacktrace:
```
Caused by: java.lang.NullPointerException: Cannot invoke "java.util.Map.put(Object, Object)" because "this.responseContext" is null
at org.apache.cxf.endpoint.ClientImpl.setResponseContext(ClientImpl.java:288)
at org.apache.cxf.endpoint.ClientImpl.doInvoke(ClientImpl.java:546)
at org.apache.cxf.endpoint.ClientImpl.invoke(ClientImpl.java:441)
at org.apache.cxf.endpoint.ClientImpl.invoke(ClientImpl.java:356)
at org.apache.cxf.endpoint.ClientImpl.invoke(ClientImpl.java:314)
at org.apache.cxf.endpoint.ClientImpl.invoke(ClientImpl.java:334)
at org.apache.cxf.endpoint.ClientImpl.invoke(ClientImpl.java:320)
...
```
The bug seems to appear "randomly" after many calls being sent through the WebService …

Fixes NPE if ClientImpl has been closed/destroyed before the end of invokation

---

core/src/main/java/org/apache/cxf/interceptor/ClientFaultConverter.java
systests/jaxws/src/test/java/org/apache/cxf/systest/jaxws/ClientServerExceptionServer.java
systests/jaxws/src/test/java/org/apache/cxf/systest/jaxws/ClientServerExceptionTest.java
systests/jaxws/src/test/java/org/apache/cxf/systest/jaxws/SayException.java

Exception message is not unmarshalled with JDK17+ (limit the fix to JDK standard library exceptions)

CXF-9076: Exception message is not unmarshalled with JDK17+ (limit the fix to JDK standard library exceptions)

---

parent/pom.xml
systests/jaxws/src/test/java/org/apache/cxf/systest/jaxws/ClientServerTest.java

Replace use of Google Guava with JDK API.
Replace `com.google.common.io.Files.createTempDir` with `java.nio.file.Files.createTempDirectory`.
See
https://sonarsource.github.io/rspec/#/rspec/S4738
"Java features should be preferred to Guava"

CXF-9085: Java features should be preferred to Guava

---

parent/pom.xml
systests/rs-security/src/test/java/org/apache/cxf/systest/jaxrs/security/jose/jwejws/JAXRSJweJwsTest.java
systests/rs-security/src/test/java/org/apache/cxf/systest/jaxrs/security/jose/jwejws/JAXRSJwsJsonTest.java
systests/rs-security/src/test/java/org/apache/cxf/systest/jaxrs/security/jose/jwejws/JweJwsAlgorithmTest.java
systests/rs-security/src/test/java/org/apache/cxf/systest/jaxrs/security/jose/jwejws/JweJwsReferenceTest.java
systests/rs-security/src/test/java/org/apache/cxf/systest/jaxrs/security/jose/jwejws/JwsHTTPHeaderTest.java
systests/rs-security/src/test/java/org/apache/cxf/systest/jaxrs/security/jose/jwt/JWTAlgorithmTest.java
systests/rs-security/src/test/java/org/apache/cxf/systest/jaxrs/security/jose/jwt/JWTAuthnAuthzTest.java
systests/rs-security/src/test/java/org/apache/cxf/systest/jaxrs/security/jose/jwt/JWTPropertiesTest.java
systests/rs-security/src/test/resources/org/apache/cxf/systest/jaxrs/security/jose/jwejws/server.xml
systests/rs-security/src/test/resources/org/apache/cxf/systest/jaxrs/security/jose/jwejws/serverJwsJson.xml

Update Jackson to 2.18.2

---

systests/transport-hc5/pom.xml
systests/transport-hc5/src/test/java/org/apache/cxf/systest/hc5/https/clientauth/ClientAuthTest.java
systests/transport-hc5/src/test/resources/org/apache/cxf/systest/hc5/https/clientauth/client-auth-server.xml
systests/transport-hc5/src/test/resources/org/apache/cxf/systest/hc5/https/clientauth/client-auth-tls-1.3.xml

Client does not send entire payload (if size ~> 2500 bytes) when hc5, TLS1.3 are used

CXF-9093: Client does not send entire payload (if size ~> 2500 bytes) when hc5, TLS1.3 are used

---

core/src/main/java/org/apache/cxf/common/util/PackageUtils.java
core/src/test/java/org/apache/cxf/common/util/PackageUtilsTest.java

Required by
https://jakarta.ee/specifications/xml-binding/4.0/jakarta-xml-binding-spec-4.0#mapping-from-a-namespace-uri

[CXF-8910] Add https to special handling in package name derivation

---

tools/validator/src/main/java/org/apache/cxf/tools/validator/internal/Stax2DOM.java

coverity SAST tool is saying that the if here is unnecessary and that the return value is the same with or without the if.   
Error: IDENTICAL_BRANCHES (CWE-398):
tools/validator/src/main/java/org/apache/cxf/tools/validator/internal/Stax2DOM.java:49:13: implicit_else: The code from the above if-then branch is identical to the code after the if statement.
tools/validator/src/main/java/org/apache/cxf/tools/validator/internal/Stax2DOM.java:46:13: identical_branches: The same code is executed when the condition "wsdlURI.toString().startsWith("http")" is true or false, because the code in the if-then branch and after the if statement is identical. Should the if statement be removed?
```
```

If is unnecessary - return value is same with or without the if

---

rt/frontend/jaxws/src/main/java/org/apache/cxf/jaxws/WrapperClassGenerator.java
rt/frontend/jaxws/src/main/java/org/apache/cxf/jaxws/spi/WrapperClassLoader.java
rt/frontend/jaxws/src/main/java/org/apache/cxf/jaxws/spi/WrapperClassNamingConvention.java
rt/frontend/jaxws/src/main/resources/META-INF/cxf/bus-extensions.txt
rt/frontend/jaxws/src/test/java/org/apache/cxf/jaxws/spi/WrapperClassLoaderTest.java
systests/jaxws/src/test/java/org/apache/cxf/systest/jaxws/CXF9003Test.java

https://issues.apache.org/jira/browse/CXF-9003

CXF-9003: Name clash when two SEIs have a same name method in the same Java package

---

core/src/main/java/org/apache/cxf/io/DelayedCachedOutputStreamCleaner.java

Log the hashCode instead of toString to avoid dumping all the file content in memory and in log because of https://github.com/apache/cxf/blob/main/core/src/main/java/org/apache/cxf/io/CachedOutputStream.java#L423
This cause OOM on our app.
```
Exception in thread "DelayedCachedOutputStreamCleaner" java.lang.OutOfMemoryError: Java heap space
at java.base/java.util.Arrays.copyOf(Arrays.java:3541)                                                                     
at java.base/java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:242)                        
at java.base/java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:744)                                        
at java.base/java.lang.StringBuilder.append(StringBuilder.java:233) …
```

fix: do not log complete stream causing OOM

---

core/src/main/java/org/apache/cxf/configuration/jsse/SSLContextServerParameters.java
rt/frontend/jaxrs/src/main/java/org/apache/cxf/jaxrs/impl/RuntimeDelegateImpl.java
rt/transports/http-jetty/src/main/java/org/apache/cxf/transport/http_jetty/JettyHTTPDestination.java
rt/transports/http-jetty/src/main/java/org/apache/cxf/transport/http_jetty/JettyHTTPServerEngine.java
rt/transports/http-jetty/src/main/java/org/apache/cxf/transport/http_jetty/JettyHTTPServerEngineFactory.java
rt/transports/http-netty/netty-server/src/main/java/org/apache/cxf/transport/http/netty/server/NettyHttpServerEngineFactory.java
rt/transports/http-undertow/src/main/java/org/apache/cxf/transport/http_undertow/UndertowHTTPServerEngine.java
rt/transports/http-undertow/src/main/java/org/apache/cxf/transport/http_undertow/UndertowHTTPServerEngineFactory.java
rt/transports/http/src/main/java/org/apache/cxf/transport/http/HTTPServerEngineFactoryParametersProvider.java
rt/transports/http/src/main/java/org/apache/cxf/transport/https/SSLUtils.java
systests/jaxrs/src/test/java/org/apache/cxf/systest/jaxrs/bootstrap/SeBootstrapTest.java

Support SeBootstrap HTTPS configuration (JAX-RS 3.1 spec)

CXF-9039: Support SeBootstrap HTTPS configuration

---

core/src/main/java/org/apache/cxf/interceptor/LoggingInInterceptor.java
core/src/main/java/org/apache/cxf/interceptor/LoggingOutInterceptor.java
rt/frontend/jaxrs/src/main/java/org/apache/cxf/jaxrs/impl/UriBuilderImpl.java
rt/frontend/jaxrs/src/main/java/org/apache/cxf/jaxrs/utils/HttpUtils.java
rt/javascript/javascript-rt/src/main/java/org/apache/cxf/javascript/service/ServiceJavascriptBuilder.java
rt/rs/description/src/main/java/org/apache/cxf/jaxrs/model/wadl/WadlGenerator.java
rt/rs/extensions/search/src/main/java/org/apache/cxf/jaxrs/ext/search/SimpleSearchCondition.java
rt/rs/security/jose-parent/jose-jaxrs/src/main/java/org/apache/cxf/rs/security/jose/jaxrs/AbstractJweJsonWriterProvider.java
rt/rs/security/xml/src/main/java/org/apache/cxf/rs/security/saml/AbstractSamlInHandler.java
rt/security/src/main/java/org/apache/cxf/rt/security/crypto/CryptoUtils.java
services/sts/sts-core/src/test/java/org/apache/cxf/sts/token/provider/JWTProviderLifetimeTest.java
systests/jaxrs/src/test/java/org/apache/cxf/systest/jaxrs/JAXRSClientServerSpringBookTest.java
systests/ldap/src/test/java/org/apache/cxf/systest/ldap/sts/LDAPClaimsTest.java
systests/transport-jms/src/test/java/org/apache/cxf/jms/testsuite/util/JMSTestUtil.java
tools/corba/src/main/java/org/apache/cxf/tools/corba/processors/idl/IDLToWSDLProcessor.java
tools/corba/src/main/java/org/apache/cxf/tools/corba/processors/idl/ScopedNameVisitor.java

Some PMD cleanup

---

core/src/main/java/org/apache/cxf/io/CachedOutputStream.java
core/src/main/java/org/apache/cxf/io/CachedOutputStreamCleaner.java
core/src/main/java/org/apache/cxf/io/DelayedCachedOutputStreamCleaner.java
rt/rs/client/src/test/java/org/apache/cxf/jaxrs/client/logging/RESTLoggingTest.java
rt/rs/client/src/test/java/org/apache/cxf/jaxrs/client/logging/TestServiceRest.java

Fix extensive memory usage with enabled LoggingFeature, cherry-picking some changes from https://github.com/apache/cxf/pull/2275

CXF-9110: Fix extensive memory usage with enabled LoggingFeature

---

rt/rs/client/src/main/java/org/apache/cxf/jaxrs/client/AbstractClient.java
rt/rs/client/src/main/java/org/apache/cxf/jaxrs/client/WebClient.java
rt/rs/client/src/test/java/org/apache/cxf/jaxrs/client/JAXRSClientFactoryBeanTest.java
rt/rs/client/src/test/java/org/apache/cxf/jaxrs/client/WebClientTest.java

WebClient.fromClient() broken due to garbage collection

CXF-8992: WebClient.fromClient() broken due to garbage collection

---

parent/pom.xml

──────────────────────────┤
│ org.apache.mina:mina-core (mina-core-2.1.5.jar) │ CVE-2024-52046 │ CRITICAL │ fixed  │ 2.1.5             │ 2.2.4, 2.1.10, 2.0.27 │ mina-core: Apache MINA: applications using unbounded │
│                                                 │                │          │        │                   │                       │ deserialization may allow RCE                        │
│                                                 │                │          │        │                   │                       │ https://avd.aquasec.com/nvd/cve-2024-52046           │
└─────────────────────────────────────────────────┴────────────────┴──────────┴─

Updating Mina to 2.1.10

---

rt/ws/security/src/main/java/org/apache/cxf/ws/security/cache/jcache/JCacheReplayCache.java
rt/ws/security/src/main/java/org/apache/cxf/ws/security/tokenstore/TokenStoreFactory.java
rt/ws/security/src/main/java/org/apache/cxf/ws/security/tokenstore/jcache/JCacheTokenStore.java
rt/ws/security/src/main/java/org/apache/cxf/ws/security/utils/JCacheSupport.java
rt/ws/security/src/main/java/org/apache/cxf/ws/security/utils/JCacheUtil.java
rt/ws/security/src/main/java/org/apache/cxf/ws/security/wss4j/WSS4JUtils.java
services/sts/sts-core/src/main/java/org/apache/cxf/sts/cache/jcache/JCacheIdentityCache.java
services/xkms/xkms-client/src/main/java/org/apache/cxf/xkms/cache/jcache/JCacheXKMSClientCache.java

`cxf-rt-ws-security` fails if JCache is not on the classpath

CXF-9117: cxf-rt-ws-security fails if JCache is not on the classpath

---

rt/transports/http/src/main/java/org/apache/cxf/transport/http/HttpClientHTTPConduit.java
systests/transports/src/test/java/org/apache/cxf/systest/http/jaxws/JAXWSAsyncClientTest.java

Race Condition in HttpClientHttpConduit Causes Writing Thread to Hang Forever

CXF-9115: Race Condition in HttpClientHttpConduit Causes Writing Thread to Hang Forever

---

core/src/main/java/org/apache/cxf/io/CachedOutputStream.java
systests/transports/src/test/java/org/apache/cxf/systest/http/jaxws/JAXWSClientTest.java

Thread leaks when throwing exception in LoggingOutInterceptor and sending large SOAP message

CXF-9100: thread leaks when throwing exception in LoggingOutInterceptor and sending large SOAP message

---

rt/features/logging/src/main/java/org/apache/cxf/ext/logging/AbstractLoggingInterceptor.java
rt/features/logging/src/main/java/org/apache/cxf/ext/logging/event/DefaultLogEventMapper.java
rt/features/logging/src/test/java/org/apache/cxf/ext/logging/LoggingInInterceptorTest.java
rt/features/logging/src/test/java/org/apache/cxf/ext/logging/TestEventSender.java

CXF-8985: headers masking implementation not replaceable (in DefaultLogEventMapper)

CXF-8985: headers masking implementation not replaceable (in DefaultLogEventMapper)

---

rt/rs/client/src/main/java/org/apache/cxf/jaxrs/client/ClientProxyImpl.java
systests/jaxrs/src/test/java/org/apache/cxf/systest/jaxrs/JAXRSMultipartTest.java
systests/jaxrs/src/test/java/org/apache/cxf/systest/jaxrs/MultipartStore.java

This supports interfaces generated by openapi jaxrs-cxf generator

[CXF-9134] Do not wrap Attachment into another Attachment

---

rt/databinding/jaxb/src/main/java/org/apache/cxf/jaxb/io/DataWriterImpl.java

I experienced a side effect with the solution created for CXF-1194/CXF-7438 which can result in the following error:
> org.apache.cxf.interceptor.Fault: Marshalling Error: Cannot invoke "javax.xml.namespace.QName.getLocalPart()" because the return value of "org.apache.cxf.jaxb.attachment.JAXBAttachmentMarshaller.getLastMTOMElementName()" is null
> 	at org.apache.cxf.jaxb.JAXBEncoderDecoder.marshall(JAXBEncoderDecoder.java:269)
> 	at org.apache.cxf.jaxb.io.DataWriterImpl.write(DataWriterImpl.java:238)
> 	at org.apache.cxf.interceptor.AbstractOutDatabindingInterceptor.writeParts(AbstractOutDatabindingInterceptor.java:137)
> 	at org.apache.cxf.wsdl.interceptors.BareOutInterceptor.handleMessage(BareOutInterceptor.java:68)
> 	at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterc …

Added null check to DataWriterImpl when calling getLastMTOMElementName

---

systests/tracing/src/test/java/org/apache/cxf/systest/jaxrs/tracing/opentelemetry/OpenTelemetryTracingTest.java
systests/tracing/src/test/java/org/apache/cxf/systest/jaxrs/tracing/opentracing/OpenTracingTracingTest.java

https://issues.apache.org/jira/browse/CXF-9142
Change the async tracing tests so that the order of the responses no longer matters.

CXF-9142 Change async tracing tests to be order-agnostic

---

core/src/main/java/org/apache/cxf/io/AbstractWrappedOutputStream.java
rt/transports/http/src/main/java/org/apache/cxf/transport/http/HTTPConduit.java
rt/transports/http/src/main/java/org/apache/cxf/transport/http/HttpClientHTTPConduit.java

If the wrappedStream corresponds to pout then it should be nulled as well. this fixes a memoryleak caused when pout is a PipedOutputStream, as the pipe holds a strong reference to the client thread which must be nulled to avoid MemoryLeaks in class like ThreadLocalClientState, which utilizes the same thread as a key for weakhashmap which in turn points to this very outputstream. this means that the thread is both the key and within the value of an entry of the weakhashamp, and as per the javadoc of said class, the GC cannot detect these cycles. to break this cycle, not only pout but also the wrappedStream needs to be nulled.
An alternative, simpler solution would be to always null the wrappedStream, but I did not debug the code enough to be sure if this is safe in all usecases like the …

CXF-9146 Fix MemoryLeak in HttpClientHttpConduit

---

integration/spring-boot/autoconfigure/src/main/java/org/apache/cxf/spring/boot/autoconfigure/ssl/CxfClientSslProperties.java
integration/spring-boot/autoconfigure/src/main/java/org/apache/cxf/spring/boot/autoconfigure/ssl/CxfSslBundlesAutoConfiguration.java
integration/spring-boot/autoconfigure/src/main/java/org/apache/cxf/spring/boot/autoconfigure/ssl/SslBundleHttpConduitConfigurer.java
integration/spring-boot/autoconfigure/src/main/resources/META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports
systests/spring-boot/pom.xml
systests/spring-boot/src/test/java/org/apache/cxf/systest/spring/boot/ssl/SpringClientSslBundleTest.java
systests/spring-boot/src/test/resources/application-ssl.yml

The CXF client can wire Spring Boot SSL bundle configuration automatically if Spring Boot SSL bundle available in the configuration and if cxf.client.ssl.enabled property is true(default is false so keep the CXF client behaviour as is).  We can select the bundle name per application or per server address match.

[CXF-9159]CXF client to support spring boot SSL bundles
